// <copyright file="AdminAppsRequestsController.cs" company="APIMatic">
// SlackWebApi.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using APIMatic.Core;
using APIMatic.Core.Utilities;
using SlackWebApi.Standard.Exceptions;
using SlackWebApi.Standard.Http.Response;
using System.Net.Http;
using System.Threading;
using System.Threading.Tasks;

namespace SlackWebApi.Standard.Controllers
{
    /// <summary>
    /// AdminAppsRequestsController.
    /// </summary>
    public class AdminAppsRequestsController : BaseController
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="AdminAppsRequestsController"/> class.
        /// </summary>
        internal AdminAppsRequestsController(GlobalConfiguration globalConfiguration) : base(globalConfiguration) { }

        /// <summary>
        /// List app requests for a team/workspace.
        /// </summary>
        /// <param name="token">Required parameter: Authentication token. Requires scope: `admin.apps:read`.</param>
        /// <param name="limit">Optional parameter: The maximum number of items to return. Must be between 1 - 1000 both inclusive..</param>
        /// <param name="cursor">Optional parameter: Set `cursor` to `next_cursor` returned by the previous call to list items in the next page.</param>
        /// <param name="teamId">Optional parameter: .</param>
        /// <returns>Returns the ApiResponse of Models.DefaultSuccessTemplate response from the API call.</returns>
        public ApiResponse<Models.DefaultSuccessTemplate> AdminAppsRequestsList(
                string token,
                int? limit = null,
                string cursor = null,
                string teamId = null)
            => CoreHelper.RunTask(AdminAppsRequestsListAsync(token, limit, cursor, teamId));

        /// <summary>
        /// List app requests for a team/workspace.
        /// </summary>
        /// <param name="token">Required parameter: Authentication token. Requires scope: `admin.apps:read`.</param>
        /// <param name="limit">Optional parameter: The maximum number of items to return. Must be between 1 - 1000 both inclusive..</param>
        /// <param name="cursor">Optional parameter: Set `cursor` to `next_cursor` returned by the previous call to list items in the next page.</param>
        /// <param name="teamId">Optional parameter: .</param>
        /// <param name="cancellationToken"> cancellationToken. </param>
        /// <returns>Returns the ApiResponse of Models.DefaultSuccessTemplate response from the API call.</returns>
        public async Task<ApiResponse<Models.DefaultSuccessTemplate>> AdminAppsRequestsListAsync(
                string token,
                int? limit = null,
                string cursor = null,
                string teamId = null,
                CancellationToken cancellationToken = default)
            => await CreateApiCall<Models.DefaultSuccessTemplate>()
              .RequestBuilder(requestBuilder => requestBuilder
                  .Setup(HttpMethod.Get, "/admin.apps.requests.list")
                  .WithAuth("slackAuth")
                  .Parameters(parameters => parameters
                      .Query(query => query.Setup("token", token).Required())
                      .Header(header => header.Setup("Content-Type", "application/x-www-form-urlencoded"))
                      .Query(query => query.Setup("limit", limit))
                      .Query(query => query.Setup("cursor", cursor))
                      .Query(query => query.Setup("team_id", teamId))))
              .ResponseHandler(responseHandler => responseHandler
                  .ErrorCase("0", CreateErrorCase("Typical error response", (errorReason, context) => new DefaultErrorTemplateException(errorReason, context))))
              .ExecuteAsync(cancellationToken).ConfigureAwait(false);
    }
}