// <copyright file="AdminConversationsRestrictAccessController.cs" company="APIMatic">
// SlackWebApi.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using APIMatic.Core;
using APIMatic.Core.Utilities;
using SlackWebApi.Standard.Exceptions;
using SlackWebApi.Standard.Http.Response;
using System.Net.Http;
using System.Threading;
using System.Threading.Tasks;

namespace SlackWebApi.Standard.Controllers
{
    /// <summary>
    /// AdminConversationsRestrictAccessController.
    /// </summary>
    public class AdminConversationsRestrictAccessController : BaseController
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="AdminConversationsRestrictAccessController"/> class.
        /// </summary>
        internal AdminConversationsRestrictAccessController(GlobalConfiguration globalConfiguration) : base(globalConfiguration) { }

        /// <summary>
        /// Add an allowlist of IDP groups for accessing a channel.
        /// </summary>
        /// <param name="token">Required parameter: Authentication token. Requires scope: `admin.conversations:write`.</param>
        /// <param name="groupId">Required parameter: The [IDP Group](https://slack.com/help/articles/115001435788-Connect-identity-provider-groups-to-your-Enterprise-Grid-org) ID to be an allowlist for the private channel..</param>
        /// <param name="channelId">Required parameter: The channel to link this group to..</param>
        /// <param name="teamId">Optional parameter: The workspace where the channel exists. This argument is required for channels only tied to one workspace, and optional for channels that are shared across an organization..</param>
        /// <returns>Returns the ApiResponse of Models.DefaultSuccessTemplate response from the API call.</returns>
        public ApiResponse<Models.DefaultSuccessTemplate> AdminConversationsRestrictAccessAddGroup(
                string token,
                string groupId,
                string channelId,
                string teamId = null)
            => CoreHelper.RunTask(AdminConversationsRestrictAccessAddGroupAsync(token, groupId, channelId, teamId));

        /// <summary>
        /// Add an allowlist of IDP groups for accessing a channel.
        /// </summary>
        /// <param name="token">Required parameter: Authentication token. Requires scope: `admin.conversations:write`.</param>
        /// <param name="groupId">Required parameter: The [IDP Group](https://slack.com/help/articles/115001435788-Connect-identity-provider-groups-to-your-Enterprise-Grid-org) ID to be an allowlist for the private channel..</param>
        /// <param name="channelId">Required parameter: The channel to link this group to..</param>
        /// <param name="teamId">Optional parameter: The workspace where the channel exists. This argument is required for channels only tied to one workspace, and optional for channels that are shared across an organization..</param>
        /// <param name="cancellationToken"> cancellationToken. </param>
        /// <returns>Returns the ApiResponse of Models.DefaultSuccessTemplate response from the API call.</returns>
        public async Task<ApiResponse<Models.DefaultSuccessTemplate>> AdminConversationsRestrictAccessAddGroupAsync(
                string token,
                string groupId,
                string channelId,
                string teamId = null,
                CancellationToken cancellationToken = default)
            => await CreateApiCall<Models.DefaultSuccessTemplate>()
              .RequestBuilder(requestBuilder => requestBuilder
                  .Setup(HttpMethod.Post, "/admin.conversations.restrictAccess.addGroup")
                  .WithAuth("slackAuth")
                  .Parameters(parameters => parameters
                      .Form(form => form.Setup("token", token).Required())
                      .Form(form => form.Setup("group_id", groupId).Required())
                      .Form(form => form.Setup("channel_id", channelId).Required())
                      .Header(header => header.Setup("Content-Type", "application/x-www-form-urlencoded"))
                      .Form(form => form.Setup("team_id", teamId))))
              .ResponseHandler(responseHandler => responseHandler
                  .ErrorCase("0", CreateErrorCase("Typical error response", (errorReason, context) => new DefaultErrorTemplateException(errorReason, context))))
              .ExecuteAsync(cancellationToken).ConfigureAwait(false);

        /// <summary>
        /// List all IDP Groups linked to a channel.
        /// </summary>
        /// <param name="token">Required parameter: Authentication token. Requires scope: `admin.conversations:read`.</param>
        /// <param name="channelId">Required parameter: .</param>
        /// <param name="teamId">Optional parameter: The workspace where the channel exists. This argument is required for channels only tied to one workspace, and optional for channels that are shared across an organization..</param>
        /// <returns>Returns the ApiResponse of Models.DefaultSuccessTemplate response from the API call.</returns>
        public ApiResponse<Models.DefaultSuccessTemplate> AdminConversationsRestrictAccessListGroups(
                string token,
                string channelId,
                string teamId = null)
            => CoreHelper.RunTask(AdminConversationsRestrictAccessListGroupsAsync(token, channelId, teamId));

        /// <summary>
        /// List all IDP Groups linked to a channel.
        /// </summary>
        /// <param name="token">Required parameter: Authentication token. Requires scope: `admin.conversations:read`.</param>
        /// <param name="channelId">Required parameter: .</param>
        /// <param name="teamId">Optional parameter: The workspace where the channel exists. This argument is required for channels only tied to one workspace, and optional for channels that are shared across an organization..</param>
        /// <param name="cancellationToken"> cancellationToken. </param>
        /// <returns>Returns the ApiResponse of Models.DefaultSuccessTemplate response from the API call.</returns>
        public async Task<ApiResponse<Models.DefaultSuccessTemplate>> AdminConversationsRestrictAccessListGroupsAsync(
                string token,
                string channelId,
                string teamId = null,
                CancellationToken cancellationToken = default)
            => await CreateApiCall<Models.DefaultSuccessTemplate>()
              .RequestBuilder(requestBuilder => requestBuilder
                  .Setup(HttpMethod.Get, "/admin.conversations.restrictAccess.listGroups")
                  .WithAuth("slackAuth")
                  .Parameters(parameters => parameters
                      .Query(query => query.Setup("token", token).Required())
                      .Query(query => query.Setup("channel_id", channelId).Required())
                      .Header(header => header.Setup("Content-Type", "application/x-www-form-urlencoded"))
                      .Query(query => query.Setup("team_id", teamId))))
              .ResponseHandler(responseHandler => responseHandler
                  .ErrorCase("0", CreateErrorCase("Typical error response", (errorReason, context) => new DefaultErrorTemplateException(errorReason, context))))
              .ExecuteAsync(cancellationToken).ConfigureAwait(false);

        /// <summary>
        /// Remove a linked IDP group linked from a private channel.
        /// </summary>
        /// <param name="token">Required parameter: Authentication token. Requires scope: `admin.conversations:write`.</param>
        /// <param name="teamId">Required parameter: The workspace where the channel exists. This argument is required for channels only tied to one workspace, and optional for channels that are shared across an organization..</param>
        /// <param name="groupId">Required parameter: The [IDP Group](https://slack.com/help/articles/115001435788-Connect-identity-provider-groups-to-your-Enterprise-Grid-org) ID to remove from the private channel..</param>
        /// <param name="channelId">Required parameter: The channel to remove the linked group from..</param>
        /// <returns>Returns the ApiResponse of Models.DefaultSuccessTemplate response from the API call.</returns>
        public ApiResponse<Models.DefaultSuccessTemplate> AdminConversationsRestrictAccessRemoveGroup(
                string token,
                string teamId,
                string groupId,
                string channelId)
            => CoreHelper.RunTask(AdminConversationsRestrictAccessRemoveGroupAsync(token, teamId, groupId, channelId));

        /// <summary>
        /// Remove a linked IDP group linked from a private channel.
        /// </summary>
        /// <param name="token">Required parameter: Authentication token. Requires scope: `admin.conversations:write`.</param>
        /// <param name="teamId">Required parameter: The workspace where the channel exists. This argument is required for channels only tied to one workspace, and optional for channels that are shared across an organization..</param>
        /// <param name="groupId">Required parameter: The [IDP Group](https://slack.com/help/articles/115001435788-Connect-identity-provider-groups-to-your-Enterprise-Grid-org) ID to remove from the private channel..</param>
        /// <param name="channelId">Required parameter: The channel to remove the linked group from..</param>
        /// <param name="cancellationToken"> cancellationToken. </param>
        /// <returns>Returns the ApiResponse of Models.DefaultSuccessTemplate response from the API call.</returns>
        public async Task<ApiResponse<Models.DefaultSuccessTemplate>> AdminConversationsRestrictAccessRemoveGroupAsync(
                string token,
                string teamId,
                string groupId,
                string channelId,
                CancellationToken cancellationToken = default)
            => await CreateApiCall<Models.DefaultSuccessTemplate>()
              .RequestBuilder(requestBuilder => requestBuilder
                  .Setup(HttpMethod.Post, "/admin.conversations.restrictAccess.removeGroup")
                  .WithAuth("slackAuth")
                  .Parameters(parameters => parameters
                      .Form(form => form.Setup("token", token).Required())
                      .Form(form => form.Setup("team_id", teamId).Required())
                      .Form(form => form.Setup("group_id", groupId).Required())
                      .Form(form => form.Setup("channel_id", channelId).Required())
                      .Header(header => header.Setup("Content-Type", "application/x-www-form-urlencoded"))))
              .ResponseHandler(responseHandler => responseHandler
                  .ErrorCase("0", CreateErrorCase("Typical error response", (errorReason, context) => new DefaultErrorTemplateException(errorReason, context))))
              .ExecuteAsync(cancellationToken).ConfigureAwait(false);
    }
}