// <copyright file="ApiController.cs" company="APIMatic">
// SlackWebApi.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using APIMatic.Core;
using APIMatic.Core.Utilities;
using SlackWebApi.Standard.Exceptions;
using SlackWebApi.Standard.Http.Response;
using System.Net.Http;
using System.Threading;
using System.Threading.Tasks;

namespace SlackWebApi.Standard.Controllers
{
    /// <summary>
    /// ApiController.
    /// </summary>
    public class ApiController : BaseController
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ApiController"/> class.
        /// </summary>
        internal ApiController(GlobalConfiguration globalConfiguration) : base(globalConfiguration) { }

        /// <summary>
        /// Checks API calling code.
        /// </summary>
        /// <param name="error">Optional parameter: Error response to return.</param>
        /// <param name="foo">Optional parameter: example property to return.</param>
        /// <returns>Returns the ApiResponse of Models.ApiTestSuccessSchema response from the API call.</returns>
        public ApiResponse<Models.ApiTestSuccessSchema> ApiTest(
                string error = null,
                string foo = null)
            => CoreHelper.RunTask(ApiTestAsync(error, foo));

        /// <summary>
        /// Checks API calling code.
        /// </summary>
        /// <param name="error">Optional parameter: Error response to return.</param>
        /// <param name="foo">Optional parameter: example property to return.</param>
        /// <param name="cancellationToken"> cancellationToken. </param>
        /// <returns>Returns the ApiResponse of Models.ApiTestSuccessSchema response from the API call.</returns>
        public async Task<ApiResponse<Models.ApiTestSuccessSchema>> ApiTestAsync(
                string error = null,
                string foo = null,
                CancellationToken cancellationToken = default)
            => await CreateApiCall<Models.ApiTestSuccessSchema>()
              .RequestBuilder(requestBuilder => requestBuilder
                  .Setup(HttpMethod.Get, "/api.test")
                  .WithAuth("slackAuth")
                  .Parameters(parameters => parameters
                      .Header(header => header.Setup("Content-Type", "application/x-www-form-urlencoded"))
                      .Query(query => query.Setup("error", error))
                      .Query(query => query.Setup("foo", foo))))
              .ResponseHandler(responseHandler => responseHandler
                  .ErrorCase("0", CreateErrorCase("Artificial error response", (errorReason, context) => new ApiTestErrorSchemaException(errorReason, context))))
              .ExecuteAsync(cancellationToken).ConfigureAwait(false);
    }
}