// <copyright file="AppsPermissionsResourcesController.cs" company="APIMatic">
// SlackWebApi.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using APIMatic.Core;
using APIMatic.Core.Utilities;
using SlackWebApi.Standard.Exceptions;
using SlackWebApi.Standard.Http.Response;
using System.Net.Http;
using System.Threading;
using System.Threading.Tasks;

namespace SlackWebApi.Standard.Controllers
{
    /// <summary>
    /// AppsPermissionsResourcesController.
    /// </summary>
    public class AppsPermissionsResourcesController : BaseController
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="AppsPermissionsResourcesController"/> class.
        /// </summary>
        internal AppsPermissionsResourcesController(GlobalConfiguration globalConfiguration) : base(globalConfiguration) { }

        /// <summary>
        /// Returns list of resource grants this app has on a team.
        /// </summary>
        /// <param name="token">Required parameter: Authentication token. Requires scope: `none`.</param>
        /// <param name="cursor">Optional parameter: Paginate through collections of data by setting the `cursor` parameter to a `next_cursor` attribute returned by a previous request's `response_metadata`. Default value fetches the first "page" of the collection. See [pagination](/docs/pagination) for more detail..</param>
        /// <param name="limit">Optional parameter: The maximum number of items to return..</param>
        /// <returns>Returns the ApiResponse of Models.AppsPermissionsResourcesListSuccessSchema response from the API call.</returns>
        public ApiResponse<Models.AppsPermissionsResourcesListSuccessSchema> AppsPermissionsResourcesList(
                string token,
                string cursor = null,
                int? limit = null)
            => CoreHelper.RunTask(AppsPermissionsResourcesListAsync(token, cursor, limit));

        /// <summary>
        /// Returns list of resource grants this app has on a team.
        /// </summary>
        /// <param name="token">Required parameter: Authentication token. Requires scope: `none`.</param>
        /// <param name="cursor">Optional parameter: Paginate through collections of data by setting the `cursor` parameter to a `next_cursor` attribute returned by a previous request's `response_metadata`. Default value fetches the first "page" of the collection. See [pagination](/docs/pagination) for more detail..</param>
        /// <param name="limit">Optional parameter: The maximum number of items to return..</param>
        /// <param name="cancellationToken"> cancellationToken. </param>
        /// <returns>Returns the ApiResponse of Models.AppsPermissionsResourcesListSuccessSchema response from the API call.</returns>
        public async Task<ApiResponse<Models.AppsPermissionsResourcesListSuccessSchema>> AppsPermissionsResourcesListAsync(
                string token,
                string cursor = null,
                int? limit = null,
                CancellationToken cancellationToken = default)
            => await CreateApiCall<Models.AppsPermissionsResourcesListSuccessSchema>()
              .RequestBuilder(requestBuilder => requestBuilder
                  .Setup(HttpMethod.Get, "/apps.permissions.resources.list")
                  .WithAuth("slackAuth")
                  .Parameters(parameters => parameters
                      .Query(query => query.Setup("token", token).Required())
                      .Header(header => header.Setup("Content-Type", "application/x-www-form-urlencoded"))
                      .Query(query => query.Setup("cursor", cursor))
                      .Query(query => query.Setup("limit", limit))))
              .ResponseHandler(responseHandler => responseHandler
                  .ErrorCase("0", CreateErrorCase("Typical error response", (errorReason, context) => new AppsPermissionsResourcesListErrorSchemaException(errorReason, context))))
              .ExecuteAsync(cancellationToken).ConfigureAwait(false);
    }
}