// <copyright file="AppsEventAuthorizationsController.cs" company="APIMatic">
// SlackWebApi.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using APIMatic.Core;
using APIMatic.Core.Utilities;
using SlackWebApi.Standard.Exceptions;
using SlackWebApi.Standard.Http.Response;
using System.Net.Http;
using System.Threading;
using System.Threading.Tasks;

namespace SlackWebApi.Standard.Controllers
{
    /// <summary>
    /// AppsEventAuthorizationsController.
    /// </summary>
    public class AppsEventAuthorizationsController : BaseController
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="AppsEventAuthorizationsController"/> class.
        /// </summary>
        internal AppsEventAuthorizationsController(GlobalConfiguration globalConfiguration) : base(globalConfiguration) { }

        /// <summary>
        /// Get a list of authorizations for the given event context. Each authorization represents an app installation that the event is visible to.
        /// </summary>
        /// <param name="token">Required parameter: Authentication token. Requires scope: `authorizations:read`.</param>
        /// <param name="eventContext">Required parameter: .</param>
        /// <param name="cursor">Optional parameter: .</param>
        /// <param name="limit">Optional parameter: .</param>
        /// <returns>Returns the ApiResponse of Models.DefaultSuccessTemplate response from the API call.</returns>
        public ApiResponse<Models.DefaultSuccessTemplate> AppsEventAuthorizationsList(
                string token,
                string eventContext,
                string cursor = null,
                int? limit = null)
            => CoreHelper.RunTask(AppsEventAuthorizationsListAsync(token, eventContext, cursor, limit));

        /// <summary>
        /// Get a list of authorizations for the given event context. Each authorization represents an app installation that the event is visible to.
        /// </summary>
        /// <param name="token">Required parameter: Authentication token. Requires scope: `authorizations:read`.</param>
        /// <param name="eventContext">Required parameter: .</param>
        /// <param name="cursor">Optional parameter: .</param>
        /// <param name="limit">Optional parameter: .</param>
        /// <param name="cancellationToken"> cancellationToken. </param>
        /// <returns>Returns the ApiResponse of Models.DefaultSuccessTemplate response from the API call.</returns>
        public async Task<ApiResponse<Models.DefaultSuccessTemplate>> AppsEventAuthorizationsListAsync(
                string token,
                string eventContext,
                string cursor = null,
                int? limit = null,
                CancellationToken cancellationToken = default)
            => await CreateApiCall<Models.DefaultSuccessTemplate>()
              .RequestBuilder(requestBuilder => requestBuilder
                  .Setup(HttpMethod.Get, "/apps.event.authorizations.list")
                  .WithAuth("slackAuth")
                  .Parameters(parameters => parameters
                      .Header(header => header.Setup("token", token).Required())
                      .Query(query => query.Setup("event_context", eventContext).Required())
                      .Header(header => header.Setup("Content-Type", "application/x-www-form-urlencoded"))
                      .Query(query => query.Setup("cursor", cursor))
                      .Query(query => query.Setup("limit", limit))))
              .ResponseHandler(responseHandler => responseHandler
                  .ErrorCase("0", CreateErrorCase("Typical error response", (errorReason, context) => new DefaultErrorTemplateException(errorReason, context))))
              .ExecuteAsync(cancellationToken).ConfigureAwait(false);
    }
}