// <copyright file="CallsParticipantsController.cs" company="APIMatic">
// SlackWebApi.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using APIMatic.Core;
using APIMatic.Core.Utilities;
using SlackWebApi.Standard.Exceptions;
using SlackWebApi.Standard.Http.Response;
using System.Net.Http;
using System.Threading;
using System.Threading.Tasks;

namespace SlackWebApi.Standard.Controllers
{
    /// <summary>
    /// CallsParticipantsController.
    /// </summary>
    public class CallsParticipantsController : BaseController
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="CallsParticipantsController"/> class.
        /// </summary>
        internal CallsParticipantsController(GlobalConfiguration globalConfiguration) : base(globalConfiguration) { }

        /// <summary>
        /// Registers new participants added to a Call.
        /// </summary>
        /// <param name="token">Required parameter: Authentication token. Requires scope: `calls:write`.</param>
        /// <param name="id">Required parameter: `id` returned by the [`calls.add`](/methods/calls.add) method..</param>
        /// <param name="users">Required parameter: The list of users to add as participants in the Call. [Read more on how to specify users here](/apis/calls#users)..</param>
        /// <returns>Returns the ApiResponse of Models.DefaultSuccessTemplate response from the API call.</returns>
        public ApiResponse<Models.DefaultSuccessTemplate> CallsParticipantsAdd(
                string token,
                string id,
                string users)
            => CoreHelper.RunTask(CallsParticipantsAddAsync(token, id, users));

        /// <summary>
        /// Registers new participants added to a Call.
        /// </summary>
        /// <param name="token">Required parameter: Authentication token. Requires scope: `calls:write`.</param>
        /// <param name="id">Required parameter: `id` returned by the [`calls.add`](/methods/calls.add) method..</param>
        /// <param name="users">Required parameter: The list of users to add as participants in the Call. [Read more on how to specify users here](/apis/calls#users)..</param>
        /// <param name="cancellationToken"> cancellationToken. </param>
        /// <returns>Returns the ApiResponse of Models.DefaultSuccessTemplate response from the API call.</returns>
        public async Task<ApiResponse<Models.DefaultSuccessTemplate>> CallsParticipantsAddAsync(
                string token,
                string id,
                string users,
                CancellationToken cancellationToken = default)
            => await CreateApiCall<Models.DefaultSuccessTemplate>()
              .RequestBuilder(requestBuilder => requestBuilder
                  .Setup(HttpMethod.Post, "/calls.participants.add")
                  .WithAuth("slackAuth")
                  .Parameters(parameters => parameters
                      .Header(header => header.Setup("token", token).Required())
                      .Form(form => form.Setup("id", id).Required())
                      .Form(form => form.Setup("users", users).Required())
                      .Header(header => header.Setup("Content-Type", "application/x-www-form-urlencoded"))))
              .ResponseHandler(responseHandler => responseHandler
                  .ErrorCase("0", CreateErrorCase("Typical error response", (errorReason, context) => new DefaultErrorTemplateException(errorReason, context))))
              .ExecuteAsync(cancellationToken).ConfigureAwait(false);

        /// <summary>
        /// Registers participants removed from a Call.
        /// </summary>
        /// <param name="token">Required parameter: Authentication token. Requires scope: `calls:write`.</param>
        /// <param name="id">Required parameter: `id` returned by the [`calls.add`](/methods/calls.add) method..</param>
        /// <param name="users">Required parameter: The list of users to remove as participants in the Call. [Read more on how to specify users here](/apis/calls#users)..</param>
        /// <returns>Returns the ApiResponse of Models.DefaultSuccessTemplate response from the API call.</returns>
        public ApiResponse<Models.DefaultSuccessTemplate> CallsParticipantsRemove(
                string token,
                string id,
                string users)
            => CoreHelper.RunTask(CallsParticipantsRemoveAsync(token, id, users));

        /// <summary>
        /// Registers participants removed from a Call.
        /// </summary>
        /// <param name="token">Required parameter: Authentication token. Requires scope: `calls:write`.</param>
        /// <param name="id">Required parameter: `id` returned by the [`calls.add`](/methods/calls.add) method..</param>
        /// <param name="users">Required parameter: The list of users to remove as participants in the Call. [Read more on how to specify users here](/apis/calls#users)..</param>
        /// <param name="cancellationToken"> cancellationToken. </param>
        /// <returns>Returns the ApiResponse of Models.DefaultSuccessTemplate response from the API call.</returns>
        public async Task<ApiResponse<Models.DefaultSuccessTemplate>> CallsParticipantsRemoveAsync(
                string token,
                string id,
                string users,
                CancellationToken cancellationToken = default)
            => await CreateApiCall<Models.DefaultSuccessTemplate>()
              .RequestBuilder(requestBuilder => requestBuilder
                  .Setup(HttpMethod.Post, "/calls.participants.remove")
                  .WithAuth("slackAuth")
                  .Parameters(parameters => parameters
                      .Header(header => header.Setup("token", token).Required())
                      .Form(form => form.Setup("id", id).Required())
                      .Form(form => form.Setup("users", users).Required())
                      .Header(header => header.Setup("Content-Type", "application/x-www-form-urlencoded"))))
              .ResponseHandler(responseHandler => responseHandler
                  .ErrorCase("0", CreateErrorCase("Typical error response", (errorReason, context) => new DefaultErrorTemplateException(errorReason, context))))
              .ExecuteAsync(cancellationToken).ConfigureAwait(false);
    }
}