// <copyright file="ChatScheduledMessagesController.cs" company="APIMatic">
// SlackWebApi.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using APIMatic.Core;
using APIMatic.Core.Utilities;
using SlackWebApi.Standard.Exceptions;
using SlackWebApi.Standard.Http.Response;
using System.Net.Http;
using System.Threading;
using System.Threading.Tasks;

namespace SlackWebApi.Standard.Controllers
{
    /// <summary>
    /// ChatScheduledMessagesController.
    /// </summary>
    public class ChatScheduledMessagesController : BaseController
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ChatScheduledMessagesController"/> class.
        /// </summary>
        internal ChatScheduledMessagesController(GlobalConfiguration globalConfiguration) : base(globalConfiguration) { }

        /// <summary>
        /// Returns a list of scheduled messages.
        /// </summary>
        /// <param name="token">Optional parameter: Authentication token. Requires scope: `none`.</param>
        /// <param name="channel">Optional parameter: The channel of the scheduled messages.</param>
        /// <param name="latest">Optional parameter: A UNIX timestamp of the latest value in the time range.</param>
        /// <param name="oldest">Optional parameter: A UNIX timestamp of the oldest value in the time range.</param>
        /// <param name="limit">Optional parameter: Maximum number of original entries to return..</param>
        /// <param name="cursor">Optional parameter: For pagination purposes, this is the `cursor` value returned from a previous call to `chat.scheduledmessages.list` indicating where you want to start this call from..</param>
        /// <returns>Returns the ApiResponse of Models.ChatScheduledMessagesListSchema response from the API call.</returns>
        public ApiResponse<Models.ChatScheduledMessagesListSchema> ChatScheduledMessagesList(
                string token = null,
                string channel = null,
                double? latest = null,
                double? oldest = null,
                int? limit = null,
                string cursor = null)
            => CoreHelper.RunTask(ChatScheduledMessagesListAsync(token, channel, latest, oldest, limit, cursor));

        /// <summary>
        /// Returns a list of scheduled messages.
        /// </summary>
        /// <param name="token">Optional parameter: Authentication token. Requires scope: `none`.</param>
        /// <param name="channel">Optional parameter: The channel of the scheduled messages.</param>
        /// <param name="latest">Optional parameter: A UNIX timestamp of the latest value in the time range.</param>
        /// <param name="oldest">Optional parameter: A UNIX timestamp of the oldest value in the time range.</param>
        /// <param name="limit">Optional parameter: Maximum number of original entries to return..</param>
        /// <param name="cursor">Optional parameter: For pagination purposes, this is the `cursor` value returned from a previous call to `chat.scheduledmessages.list` indicating where you want to start this call from..</param>
        /// <param name="cancellationToken"> cancellationToken. </param>
        /// <returns>Returns the ApiResponse of Models.ChatScheduledMessagesListSchema response from the API call.</returns>
        public async Task<ApiResponse<Models.ChatScheduledMessagesListSchema>> ChatScheduledMessagesListAsync(
                string token = null,
                string channel = null,
                double? latest = null,
                double? oldest = null,
                int? limit = null,
                string cursor = null,
                CancellationToken cancellationToken = default)
            => await CreateApiCall<Models.ChatScheduledMessagesListSchema>()
              .RequestBuilder(requestBuilder => requestBuilder
                  .Setup(HttpMethod.Get, "/chat.scheduledMessages.list")
                  .WithAuth("slackAuth")
                  .Parameters(parameters => parameters
                      .Header(header => header.Setup("Content-Type", "application/x-www-form-urlencoded"))
                      .Header(header => header.Setup("token", token))
                      .Query(query => query.Setup("channel", channel))
                      .Query(query => query.Setup("latest", latest))
                      .Query(query => query.Setup("oldest", oldest))
                      .Query(query => query.Setup("limit", limit))
                      .Query(query => query.Setup("cursor", cursor))))
              .ResponseHandler(responseHandler => responseHandler
                  .ErrorCase("0", CreateErrorCase("Typical error response if the channel passed is invalid", (errorReason, context) => new ChatScheduledMessagesListErrorSchemaException(errorReason, context))))
              .ExecuteAsync(cancellationToken).ConfigureAwait(false);
    }
}