// <copyright file="DialogController.cs" company="APIMatic">
// SlackWebApi.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using APIMatic.Core;
using APIMatic.Core.Utilities;
using SlackWebApi.Standard.Exceptions;
using SlackWebApi.Standard.Http.Response;
using System.Net.Http;
using System.Threading;
using System.Threading.Tasks;

namespace SlackWebApi.Standard.Controllers
{
    /// <summary>
    /// DialogController.
    /// </summary>
    public class DialogController : BaseController
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="DialogController"/> class.
        /// </summary>
        internal DialogController(GlobalConfiguration globalConfiguration) : base(globalConfiguration) { }

        /// <summary>
        /// Open a dialog with a user.
        /// </summary>
        /// <param name="token">Required parameter: Authentication token. Requires scope: `none`.</param>
        /// <param name="dialog">Required parameter: The dialog definition. This must be a JSON-encoded string..</param>
        /// <param name="triggerId">Required parameter: Exchange a trigger to post to the user..</param>
        /// <returns>Returns the ApiResponse of Models.DialogOpenSchema response from the API call.</returns>
        public ApiResponse<Models.DialogOpenSchema> DialogOpen(
                string token,
                string dialog,
                string triggerId)
            => CoreHelper.RunTask(DialogOpenAsync(token, dialog, triggerId));

        /// <summary>
        /// Open a dialog with a user.
        /// </summary>
        /// <param name="token">Required parameter: Authentication token. Requires scope: `none`.</param>
        /// <param name="dialog">Required parameter: The dialog definition. This must be a JSON-encoded string..</param>
        /// <param name="triggerId">Required parameter: Exchange a trigger to post to the user..</param>
        /// <param name="cancellationToken"> cancellationToken. </param>
        /// <returns>Returns the ApiResponse of Models.DialogOpenSchema response from the API call.</returns>
        public async Task<ApiResponse<Models.DialogOpenSchema>> DialogOpenAsync(
                string token,
                string dialog,
                string triggerId,
                CancellationToken cancellationToken = default)
            => await CreateApiCall<Models.DialogOpenSchema>()
              .RequestBuilder(requestBuilder => requestBuilder
                  .Setup(HttpMethod.Get, "/dialog.open")
                  .WithAuth("slackAuth")
                  .Parameters(parameters => parameters
                      .Header(header => header.Setup("token", token).Required())
                      .Query(query => query.Setup("dialog", dialog).Required())
                      .Query(query => query.Setup("trigger_id", triggerId).Required())
                      .Header(header => header.Setup("Content-Type", "application/x-www-form-urlencoded"))))
              .ResponseHandler(responseHandler => responseHandler
                  .ErrorCase("0", CreateErrorCase("Typical error response, before getting to any possible validation errors.", (errorReason, context) => new DialogOpenErrorSchemaException(errorReason, context))))
              .ExecuteAsync(cancellationToken).ConfigureAwait(false);
    }
}