// <copyright file="FilesCommentsController.cs" company="APIMatic">
// SlackWebApi.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using APIMatic.Core;
using APIMatic.Core.Utilities;
using SlackWebApi.Standard.Exceptions;
using SlackWebApi.Standard.Http.Response;
using System.Net.Http;
using System.Threading;
using System.Threading.Tasks;

namespace SlackWebApi.Standard.Controllers
{
    /// <summary>
    /// FilesCommentsController.
    /// </summary>
    public class FilesCommentsController : BaseController
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="FilesCommentsController"/> class.
        /// </summary>
        internal FilesCommentsController(GlobalConfiguration globalConfiguration) : base(globalConfiguration) { }

        /// <summary>
        /// Deletes an existing comment on a file.
        /// </summary>
        /// <param name="token">Optional parameter: Authentication token. Requires scope: `files:write:user`.</param>
        /// <param name="file">Optional parameter: File to delete a comment from..</param>
        /// <param name="id">Optional parameter: The comment to delete..</param>
        /// <returns>Returns the ApiResponse of Models.FilesCommentsDeleteSchema response from the API call.</returns>
        public ApiResponse<Models.FilesCommentsDeleteSchema> FilesCommentsDelete(
                string token = null,
                string file = null,
                string id = null)
            => CoreHelper.RunTask(FilesCommentsDeleteAsync(token, file, id));

        /// <summary>
        /// Deletes an existing comment on a file.
        /// </summary>
        /// <param name="token">Optional parameter: Authentication token. Requires scope: `files:write:user`.</param>
        /// <param name="file">Optional parameter: File to delete a comment from..</param>
        /// <param name="id">Optional parameter: The comment to delete..</param>
        /// <param name="cancellationToken"> cancellationToken. </param>
        /// <returns>Returns the ApiResponse of Models.FilesCommentsDeleteSchema response from the API call.</returns>
        public async Task<ApiResponse<Models.FilesCommentsDeleteSchema>> FilesCommentsDeleteAsync(
                string token = null,
                string file = null,
                string id = null,
                CancellationToken cancellationToken = default)
            => await CreateApiCall<Models.FilesCommentsDeleteSchema>()
              .RequestBuilder(requestBuilder => requestBuilder
                  .Setup(HttpMethod.Post, "/files.comments.delete")
                  .WithAuth("slackAuth")
                  .Parameters(parameters => parameters
                      .Header(header => header.Setup("Content-Type", "application/x-www-form-urlencoded"))
                      .Header(header => header.Setup("token", token))
                      .Form(form => form.Setup("file", file))
                      .Form(form => form.Setup("id", id))))
              .ResponseHandler(responseHandler => responseHandler
                  .ErrorCase("0", CreateErrorCase("Standard failure response when used with an invalid token", (errorReason, context) => new FilesCommentsDeleteErrorSchemaException(errorReason, context))))
              .ExecuteAsync(cancellationToken).ConfigureAwait(false);
    }
}