// <copyright file="MigrationController.cs" company="APIMatic">
// SlackWebApi.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using APIMatic.Core;
using APIMatic.Core.Utilities;
using SlackWebApi.Standard.Exceptions;
using SlackWebApi.Standard.Http.Response;
using System.Net.Http;
using System.Threading;
using System.Threading.Tasks;

namespace SlackWebApi.Standard.Controllers
{
    /// <summary>
    /// MigrationController.
    /// </summary>
    public class MigrationController : BaseController
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="MigrationController"/> class.
        /// </summary>
        internal MigrationController(GlobalConfiguration globalConfiguration) : base(globalConfiguration) { }

        /// <summary>
        /// For Enterprise Grid workspaces, map local user IDs to global user IDs.
        /// </summary>
        /// <param name="token">Required parameter: Authentication token. Requires scope: `tokens.basic`.</param>
        /// <param name="users">Required parameter: A comma-separated list of user ids, up to 400 per request.</param>
        /// <param name="teamId">Optional parameter: Specify team_id starts with `T` in case of Org Token.</param>
        /// <param name="toOld">Optional parameter: Specify `true` to convert `W` global user IDs to workspace-specific `U` IDs. Defaults to `false`..</param>
        /// <returns>Returns the ApiResponse of Models.MigrationExchangeSuccessSchema response from the API call.</returns>
        public ApiResponse<Models.MigrationExchangeSuccessSchema> MigrationExchange(
                string token,
                string users,
                string teamId = null,
                bool? toOld = null)
            => CoreHelper.RunTask(MigrationExchangeAsync(token, users, teamId, toOld));

        /// <summary>
        /// For Enterprise Grid workspaces, map local user IDs to global user IDs.
        /// </summary>
        /// <param name="token">Required parameter: Authentication token. Requires scope: `tokens.basic`.</param>
        /// <param name="users">Required parameter: A comma-separated list of user ids, up to 400 per request.</param>
        /// <param name="teamId">Optional parameter: Specify team_id starts with `T` in case of Org Token.</param>
        /// <param name="toOld">Optional parameter: Specify `true` to convert `W` global user IDs to workspace-specific `U` IDs. Defaults to `false`..</param>
        /// <param name="cancellationToken"> cancellationToken. </param>
        /// <returns>Returns the ApiResponse of Models.MigrationExchangeSuccessSchema response from the API call.</returns>
        public async Task<ApiResponse<Models.MigrationExchangeSuccessSchema>> MigrationExchangeAsync(
                string token,
                string users,
                string teamId = null,
                bool? toOld = null,
                CancellationToken cancellationToken = default)
            => await CreateApiCall<Models.MigrationExchangeSuccessSchema>()
              .RequestBuilder(requestBuilder => requestBuilder
                  .Setup(HttpMethod.Get, "/migration.exchange")
                  .WithAuth("slackAuth")
                  .Parameters(parameters => parameters
                      .Query(query => query.Setup("token", token).Required())
                      .Query(query => query.Setup("users", users).Required())
                      .Header(header => header.Setup("Content-Type", "application/x-www-form-urlencoded"))
                      .Query(query => query.Setup("team_id", teamId))
                      .Query(query => query.Setup("to_old", toOld))))
              .ResponseHandler(responseHandler => responseHandler
                  .ErrorCase("0", CreateErrorCase("Typical error response when there are no mappings to provide", (errorReason, context) => new MigrationExchangeErrorSchemaException(errorReason, context))))
              .ExecuteAsync(cancellationToken).ConfigureAwait(false);
    }
}