// <copyright file="ReactionsController.cs" company="APIMatic">
// SlackWebApi.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using APIMatic.Core;
using APIMatic.Core.Utilities;
using SlackWebApi.Standard.Exceptions;
using SlackWebApi.Standard.Http.Response;
using System.Net.Http;
using System.Threading;
using System.Threading.Tasks;

namespace SlackWebApi.Standard.Controllers
{
    /// <summary>
    /// ReactionsController.
    /// </summary>
    public class ReactionsController : BaseController
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ReactionsController"/> class.
        /// </summary>
        internal ReactionsController(GlobalConfiguration globalConfiguration) : base(globalConfiguration) { }

        /// <summary>
        /// Adds a reaction to an item.
        /// </summary>
        /// <param name="channel">Required parameter: Channel where the message to add reaction to was posted..</param>
        /// <param name="name">Required parameter: Reaction (emoji) name..</param>
        /// <param name="timestamp">Required parameter: Timestamp of the message to add reaction to..</param>
        /// <param name="token">Required parameter: Authentication token. Requires scope: `reactions:write`.</param>
        /// <returns>Returns the ApiResponse of Models.ReactionsAddSchema response from the API call.</returns>
        public ApiResponse<Models.ReactionsAddSchema> ReactionsAdd(
                string channel,
                string name,
                string timestamp,
                string token)
            => CoreHelper.RunTask(ReactionsAddAsync(channel, name, timestamp, token));

        /// <summary>
        /// Adds a reaction to an item.
        /// </summary>
        /// <param name="channel">Required parameter: Channel where the message to add reaction to was posted..</param>
        /// <param name="name">Required parameter: Reaction (emoji) name..</param>
        /// <param name="timestamp">Required parameter: Timestamp of the message to add reaction to..</param>
        /// <param name="token">Required parameter: Authentication token. Requires scope: `reactions:write`.</param>
        /// <param name="cancellationToken"> cancellationToken. </param>
        /// <returns>Returns the ApiResponse of Models.ReactionsAddSchema response from the API call.</returns>
        public async Task<ApiResponse<Models.ReactionsAddSchema>> ReactionsAddAsync(
                string channel,
                string name,
                string timestamp,
                string token,
                CancellationToken cancellationToken = default)
            => await CreateApiCall<Models.ReactionsAddSchema>()
              .RequestBuilder(requestBuilder => requestBuilder
                  .Setup(HttpMethod.Post, "/reactions.add")
                  .WithAuth("slackAuth")
                  .Parameters(parameters => parameters
                      .Form(form => form.Setup("channel", channel).Required())
                      .Form(form => form.Setup("name", name).Required())
                      .Form(form => form.Setup("timestamp", timestamp).Required())
                      .Header(header => header.Setup("token", token).Required())
                      .Header(header => header.Setup("Content-Type", "application/x-www-form-urlencoded"))))
              .ResponseHandler(responseHandler => responseHandler
                  .ErrorCase("0", CreateErrorCase("Typical error response", (errorReason, context) => new ReactionsAddErrorSchemaException(errorReason, context))))
              .ExecuteAsync(cancellationToken).ConfigureAwait(false);

        /// <summary>
        /// Gets reactions for an item.
        /// </summary>
        /// <param name="token">Required parameter: Authentication token. Requires scope: `reactions:read`.</param>
        /// <param name="channel">Optional parameter: Channel where the message to get reactions for was posted..</param>
        /// <param name="file">Optional parameter: File to get reactions for..</param>
        /// <param name="fileComment">Optional parameter: File comment to get reactions for..</param>
        /// <param name="full">Optional parameter: If true always return the complete reaction list..</param>
        /// <param name="timestamp">Optional parameter: Timestamp of the message to get reactions for..</param>
        /// <returns>Returns the ApiResponse of object response from the API call.</returns>
        public ApiResponse<object> ReactionsGet(
                string token,
                string channel = null,
                string file = null,
                string fileComment = null,
                bool? full = null,
                string timestamp = null)
            => CoreHelper.RunTask(ReactionsGetAsync(token, channel, file, fileComment, full, timestamp));

        /// <summary>
        /// Gets reactions for an item.
        /// </summary>
        /// <param name="token">Required parameter: Authentication token. Requires scope: `reactions:read`.</param>
        /// <param name="channel">Optional parameter: Channel where the message to get reactions for was posted..</param>
        /// <param name="file">Optional parameter: File to get reactions for..</param>
        /// <param name="fileComment">Optional parameter: File comment to get reactions for..</param>
        /// <param name="full">Optional parameter: If true always return the complete reaction list..</param>
        /// <param name="timestamp">Optional parameter: Timestamp of the message to get reactions for..</param>
        /// <param name="cancellationToken"> cancellationToken. </param>
        /// <returns>Returns the ApiResponse of object response from the API call.</returns>
        public async Task<ApiResponse<object>> ReactionsGetAsync(
                string token,
                string channel = null,
                string file = null,
                string fileComment = null,
                bool? full = null,
                string timestamp = null,
                CancellationToken cancellationToken = default)
            => await CreateApiCall<object>()
              .RequestBuilder(requestBuilder => requestBuilder
                  .Setup(HttpMethod.Get, "/reactions.get")
                  .WithAuth("slackAuth")
                  .Parameters(parameters => parameters
                      .Query(query => query.Setup("token", token).Required())
                      .Header(header => header.Setup("Content-Type", "application/x-www-form-urlencoded"))
                      .Query(query => query.Setup("channel", channel))
                      .Query(query => query.Setup("file", file))
                      .Query(query => query.Setup("file_comment", fileComment))
                      .Query(query => query.Setup("full", full))
                      .Query(query => query.Setup("timestamp", timestamp))))
              .ResponseHandler(responseHandler => responseHandler
                  .ErrorCase("0", CreateErrorCase("Typical error response", (errorReason, context) => new ReactionsGetErrorSchemaException(errorReason, context)))
                  .Deserializer(response => response))
              .ExecuteAsync(cancellationToken).ConfigureAwait(false);

        /// <summary>
        /// Lists reactions made by a user.
        /// </summary>
        /// <param name="token">Required parameter: Authentication token. Requires scope: `reactions:read`.</param>
        /// <param name="user">Optional parameter: Show reactions made by this user. Defaults to the authed user..</param>
        /// <param name="full">Optional parameter: If true always return the complete reaction list..</param>
        /// <param name="count">Optional parameter: .</param>
        /// <param name="page">Optional parameter: .</param>
        /// <param name="cursor">Optional parameter: Parameter for pagination. Set `cursor` equal to the `next_cursor` attribute returned by the previous request's `response_metadata`. This parameter is optional, but pagination is mandatory: the default value simply fetches the first "page" of the collection. See [pagination](/docs/pagination) for more details..</param>
        /// <param name="limit">Optional parameter: The maximum number of items to return. Fewer than the requested number of items may be returned, even if the end of the list hasn't been reached..</param>
        /// <returns>Returns the ApiResponse of Models.ReactionsListSchema response from the API call.</returns>
        public ApiResponse<Models.ReactionsListSchema> ReactionsList(
                string token,
                string user = null,
                bool? full = null,
                int? count = null,
                int? page = null,
                string cursor = null,
                int? limit = null)
            => CoreHelper.RunTask(ReactionsListAsync(token, user, full, count, page, cursor, limit));

        /// <summary>
        /// Lists reactions made by a user.
        /// </summary>
        /// <param name="token">Required parameter: Authentication token. Requires scope: `reactions:read`.</param>
        /// <param name="user">Optional parameter: Show reactions made by this user. Defaults to the authed user..</param>
        /// <param name="full">Optional parameter: If true always return the complete reaction list..</param>
        /// <param name="count">Optional parameter: .</param>
        /// <param name="page">Optional parameter: .</param>
        /// <param name="cursor">Optional parameter: Parameter for pagination. Set `cursor` equal to the `next_cursor` attribute returned by the previous request's `response_metadata`. This parameter is optional, but pagination is mandatory: the default value simply fetches the first "page" of the collection. See [pagination](/docs/pagination) for more details..</param>
        /// <param name="limit">Optional parameter: The maximum number of items to return. Fewer than the requested number of items may be returned, even if the end of the list hasn't been reached..</param>
        /// <param name="cancellationToken"> cancellationToken. </param>
        /// <returns>Returns the ApiResponse of Models.ReactionsListSchema response from the API call.</returns>
        public async Task<ApiResponse<Models.ReactionsListSchema>> ReactionsListAsync(
                string token,
                string user = null,
                bool? full = null,
                int? count = null,
                int? page = null,
                string cursor = null,
                int? limit = null,
                CancellationToken cancellationToken = default)
            => await CreateApiCall<Models.ReactionsListSchema>()
              .RequestBuilder(requestBuilder => requestBuilder
                  .Setup(HttpMethod.Get, "/reactions.list")
                  .WithAuth("slackAuth")
                  .Parameters(parameters => parameters
                      .Query(query => query.Setup("token", token).Required())
                      .Header(header => header.Setup("Content-Type", "application/x-www-form-urlencoded"))
                      .Query(query => query.Setup("user", user))
                      .Query(query => query.Setup("full", full))
                      .Query(query => query.Setup("count", count))
                      .Query(query => query.Setup("page", page))
                      .Query(query => query.Setup("cursor", cursor))
                      .Query(query => query.Setup("limit", limit))))
              .ResponseHandler(responseHandler => responseHandler
                  .ErrorCase("0", CreateErrorCase("Typical error response", (errorReason, context) => new ReactionsListErrorSchemaException(errorReason, context))))
              .ExecuteAsync(cancellationToken).ConfigureAwait(false);

        /// <summary>
        /// Removes a reaction from an item.
        /// </summary>
        /// <param name="token">Required parameter: Authentication token. Requires scope: `reactions:write`.</param>
        /// <param name="name">Required parameter: Reaction (emoji) name..</param>
        /// <param name="file">Optional parameter: File to remove reaction from..</param>
        /// <param name="fileComment">Optional parameter: File comment to remove reaction from..</param>
        /// <param name="channel">Optional parameter: Channel where the message to remove reaction from was posted..</param>
        /// <param name="timestamp">Optional parameter: Timestamp of the message to remove reaction from..</param>
        /// <returns>Returns the ApiResponse of Models.ReactionsRemoveSchema response from the API call.</returns>
        public ApiResponse<Models.ReactionsRemoveSchema> ReactionsRemove(
                string token,
                string name,
                string file = null,
                string fileComment = null,
                string channel = null,
                string timestamp = null)
            => CoreHelper.RunTask(ReactionsRemoveAsync(token, name, file, fileComment, channel, timestamp));

        /// <summary>
        /// Removes a reaction from an item.
        /// </summary>
        /// <param name="token">Required parameter: Authentication token. Requires scope: `reactions:write`.</param>
        /// <param name="name">Required parameter: Reaction (emoji) name..</param>
        /// <param name="file">Optional parameter: File to remove reaction from..</param>
        /// <param name="fileComment">Optional parameter: File comment to remove reaction from..</param>
        /// <param name="channel">Optional parameter: Channel where the message to remove reaction from was posted..</param>
        /// <param name="timestamp">Optional parameter: Timestamp of the message to remove reaction from..</param>
        /// <param name="cancellationToken"> cancellationToken. </param>
        /// <returns>Returns the ApiResponse of Models.ReactionsRemoveSchema response from the API call.</returns>
        public async Task<ApiResponse<Models.ReactionsRemoveSchema>> ReactionsRemoveAsync(
                string token,
                string name,
                string file = null,
                string fileComment = null,
                string channel = null,
                string timestamp = null,
                CancellationToken cancellationToken = default)
            => await CreateApiCall<Models.ReactionsRemoveSchema>()
              .RequestBuilder(requestBuilder => requestBuilder
                  .Setup(HttpMethod.Post, "/reactions.remove")
                  .WithAuth("slackAuth")
                  .Parameters(parameters => parameters
                      .Header(header => header.Setup("token", token).Required())
                      .Form(form => form.Setup("name", name).Required())
                      .Header(header => header.Setup("Content-Type", "application/x-www-form-urlencoded"))
                      .Form(form => form.Setup("file", file))
                      .Form(form => form.Setup("file_comment", fileComment))
                      .Form(form => form.Setup("channel", channel))
                      .Form(form => form.Setup("timestamp", timestamp))))
              .ResponseHandler(responseHandler => responseHandler
                  .ErrorCase("0", CreateErrorCase("Typical error response", (errorReason, context) => new ReactionsRemoveErrorSchemaException(errorReason, context))))
              .ExecuteAsync(cancellationToken).ConfigureAwait(false);
    }
}