// <copyright file="RtmController.cs" company="APIMatic">
// SlackWebApi.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using APIMatic.Core;
using APIMatic.Core.Utilities;
using SlackWebApi.Standard.Exceptions;
using SlackWebApi.Standard.Http.Response;
using System.Net.Http;
using System.Threading;
using System.Threading.Tasks;

namespace SlackWebApi.Standard.Controllers
{
    /// <summary>
    /// RtmController.
    /// </summary>
    public class RtmController : BaseController
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="RtmController"/> class.
        /// </summary>
        internal RtmController(GlobalConfiguration globalConfiguration) : base(globalConfiguration) { }

        /// <summary>
        /// Starts a Real Time Messaging session.
        /// </summary>
        /// <param name="token">Required parameter: Authentication token. Requires scope: `rtm:stream`.</param>
        /// <param name="batchPresenceAware">Optional parameter: Batch presence deliveries via subscription. Enabling changes the shape of `presence_change` events. See [batch presence](/docs/presence-and-status#batching)..</param>
        /// <param name="presenceSub">Optional parameter: Only deliver presence events when requested by subscription. See [presence subscriptions](/docs/presence-and-status#subscriptions)..</param>
        /// <returns>Returns the ApiResponse of Models.RtmConnectSchema response from the API call.</returns>
        public ApiResponse<Models.RtmConnectSchema> RtmConnect(
                string token,
                bool? batchPresenceAware = null,
                bool? presenceSub = null)
            => CoreHelper.RunTask(RtmConnectAsync(token, batchPresenceAware, presenceSub));

        /// <summary>
        /// Starts a Real Time Messaging session.
        /// </summary>
        /// <param name="token">Required parameter: Authentication token. Requires scope: `rtm:stream`.</param>
        /// <param name="batchPresenceAware">Optional parameter: Batch presence deliveries via subscription. Enabling changes the shape of `presence_change` events. See [batch presence](/docs/presence-and-status#batching)..</param>
        /// <param name="presenceSub">Optional parameter: Only deliver presence events when requested by subscription. See [presence subscriptions](/docs/presence-and-status#subscriptions)..</param>
        /// <param name="cancellationToken"> cancellationToken. </param>
        /// <returns>Returns the ApiResponse of Models.RtmConnectSchema response from the API call.</returns>
        public async Task<ApiResponse<Models.RtmConnectSchema>> RtmConnectAsync(
                string token,
                bool? batchPresenceAware = null,
                bool? presenceSub = null,
                CancellationToken cancellationToken = default)
            => await CreateApiCall<Models.RtmConnectSchema>()
              .RequestBuilder(requestBuilder => requestBuilder
                  .Setup(HttpMethod.Get, "/rtm.connect")
                  .WithAuth("slackAuth")
                  .Parameters(parameters => parameters
                      .Query(query => query.Setup("token", token).Required())
                      .Header(header => header.Setup("Content-Type", "application/x-www-form-urlencoded"))
                      .Query(query => query.Setup("batch_presence_aware", batchPresenceAware))
                      .Query(query => query.Setup("presence_sub", presenceSub))))
              .ResponseHandler(responseHandler => responseHandler
                  .ErrorCase("0", CreateErrorCase("Typical error response", (errorReason, context) => new RtmConnectErrorSchemaException(errorReason, context))))
              .ExecuteAsync(cancellationToken).ConfigureAwait(false);
    }
}