// <copyright file="StarsController.cs" company="APIMatic">
// SlackWebApi.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using APIMatic.Core;
using APIMatic.Core.Utilities;
using SlackWebApi.Standard.Exceptions;
using SlackWebApi.Standard.Http.Response;
using System.Net.Http;
using System.Threading;
using System.Threading.Tasks;

namespace SlackWebApi.Standard.Controllers
{
    /// <summary>
    /// StarsController.
    /// </summary>
    public class StarsController : BaseController
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="StarsController"/> class.
        /// </summary>
        internal StarsController(GlobalConfiguration globalConfiguration) : base(globalConfiguration) { }

        /// <summary>
        /// Adds a star to an item.
        /// </summary>
        /// <param name="token">Required parameter: Authentication token. Requires scope: `stars:write`.</param>
        /// <param name="channel">Optional parameter: Channel to add star to, or channel where the message to add star to was posted (used with `timestamp`)..</param>
        /// <param name="file">Optional parameter: File to add star to..</param>
        /// <param name="fileComment">Optional parameter: File comment to add star to..</param>
        /// <param name="timestamp">Optional parameter: Timestamp of the message to add star to..</param>
        /// <returns>Returns the ApiResponse of Models.StarsAddSchema response from the API call.</returns>
        public ApiResponse<Models.StarsAddSchema> StarsAdd(
                string token,
                string channel = null,
                string file = null,
                string fileComment = null,
                string timestamp = null)
            => CoreHelper.RunTask(StarsAddAsync(token, channel, file, fileComment, timestamp));

        /// <summary>
        /// Adds a star to an item.
        /// </summary>
        /// <param name="token">Required parameter: Authentication token. Requires scope: `stars:write`.</param>
        /// <param name="channel">Optional parameter: Channel to add star to, or channel where the message to add star to was posted (used with `timestamp`)..</param>
        /// <param name="file">Optional parameter: File to add star to..</param>
        /// <param name="fileComment">Optional parameter: File comment to add star to..</param>
        /// <param name="timestamp">Optional parameter: Timestamp of the message to add star to..</param>
        /// <param name="cancellationToken"> cancellationToken. </param>
        /// <returns>Returns the ApiResponse of Models.StarsAddSchema response from the API call.</returns>
        public async Task<ApiResponse<Models.StarsAddSchema>> StarsAddAsync(
                string token,
                string channel = null,
                string file = null,
                string fileComment = null,
                string timestamp = null,
                CancellationToken cancellationToken = default)
            => await CreateApiCall<Models.StarsAddSchema>()
              .RequestBuilder(requestBuilder => requestBuilder
                  .Setup(HttpMethod.Post, "/stars.add")
                  .WithAuth("slackAuth")
                  .Parameters(parameters => parameters
                      .Header(header => header.Setup("token", token).Required())
                      .Header(header => header.Setup("Content-Type", "application/x-www-form-urlencoded"))
                      .Form(form => form.Setup("channel", channel))
                      .Form(form => form.Setup("file", file))
                      .Form(form => form.Setup("file_comment", fileComment))
                      .Form(form => form.Setup("timestamp", timestamp))))
              .ResponseHandler(responseHandler => responseHandler
                  .ErrorCase("0", CreateErrorCase("Typical error response", (errorReason, context) => new StarsAddErrorSchemaException(errorReason, context))))
              .ExecuteAsync(cancellationToken).ConfigureAwait(false);

        /// <summary>
        /// Lists stars for a user.
        /// </summary>
        /// <param name="token">Optional parameter: Authentication token. Requires scope: `stars:read`.</param>
        /// <param name="count">Optional parameter: .</param>
        /// <param name="page">Optional parameter: .</param>
        /// <param name="cursor">Optional parameter: Parameter for pagination. Set `cursor` equal to the `next_cursor` attribute returned by the previous request's `response_metadata`. This parameter is optional, but pagination is mandatory: the default value simply fetches the first "page" of the collection. See [pagination](/docs/pagination) for more details..</param>
        /// <param name="limit">Optional parameter: The maximum number of items to return. Fewer than the requested number of items may be returned, even if the end of the list hasn't been reached..</param>
        /// <returns>Returns the ApiResponse of Models.StarsListSchema response from the API call.</returns>
        public ApiResponse<Models.StarsListSchema> StarsList(
                string token = null,
                string count = null,
                string page = null,
                string cursor = null,
                int? limit = null)
            => CoreHelper.RunTask(StarsListAsync(token, count, page, cursor, limit));

        /// <summary>
        /// Lists stars for a user.
        /// </summary>
        /// <param name="token">Optional parameter: Authentication token. Requires scope: `stars:read`.</param>
        /// <param name="count">Optional parameter: .</param>
        /// <param name="page">Optional parameter: .</param>
        /// <param name="cursor">Optional parameter: Parameter for pagination. Set `cursor` equal to the `next_cursor` attribute returned by the previous request's `response_metadata`. This parameter is optional, but pagination is mandatory: the default value simply fetches the first "page" of the collection. See [pagination](/docs/pagination) for more details..</param>
        /// <param name="limit">Optional parameter: The maximum number of items to return. Fewer than the requested number of items may be returned, even if the end of the list hasn't been reached..</param>
        /// <param name="cancellationToken"> cancellationToken. </param>
        /// <returns>Returns the ApiResponse of Models.StarsListSchema response from the API call.</returns>
        public async Task<ApiResponse<Models.StarsListSchema>> StarsListAsync(
                string token = null,
                string count = null,
                string page = null,
                string cursor = null,
                int? limit = null,
                CancellationToken cancellationToken = default)
            => await CreateApiCall<Models.StarsListSchema>()
              .RequestBuilder(requestBuilder => requestBuilder
                  .Setup(HttpMethod.Get, "/stars.list")
                  .WithAuth("slackAuth")
                  .Parameters(parameters => parameters
                      .Header(header => header.Setup("Content-Type", "application/x-www-form-urlencoded"))
                      .Query(query => query.Setup("token", token))
                      .Query(query => query.Setup("count", count))
                      .Query(query => query.Setup("page", page))
                      .Query(query => query.Setup("cursor", cursor))
                      .Query(query => query.Setup("limit", limit))))
              .ResponseHandler(responseHandler => responseHandler
                  .ErrorCase("0", CreateErrorCase("Typical error response", (errorReason, context) => new StarsListErrorSchemaException(errorReason, context))))
              .ExecuteAsync(cancellationToken).ConfigureAwait(false);

        /// <summary>
        /// Removes a star from an item.
        /// </summary>
        /// <param name="token">Required parameter: Authentication token. Requires scope: `stars:write`.</param>
        /// <param name="channel">Optional parameter: Channel to remove star from, or channel where the message to remove star from was posted (used with `timestamp`)..</param>
        /// <param name="file">Optional parameter: File to remove star from..</param>
        /// <param name="fileComment">Optional parameter: File comment to remove star from..</param>
        /// <param name="timestamp">Optional parameter: Timestamp of the message to remove star from..</param>
        /// <returns>Returns the ApiResponse of Models.StarsRemoveSchema response from the API call.</returns>
        public ApiResponse<Models.StarsRemoveSchema> StarsRemove(
                string token,
                string channel = null,
                string file = null,
                string fileComment = null,
                string timestamp = null)
            => CoreHelper.RunTask(StarsRemoveAsync(token, channel, file, fileComment, timestamp));

        /// <summary>
        /// Removes a star from an item.
        /// </summary>
        /// <param name="token">Required parameter: Authentication token. Requires scope: `stars:write`.</param>
        /// <param name="channel">Optional parameter: Channel to remove star from, or channel where the message to remove star from was posted (used with `timestamp`)..</param>
        /// <param name="file">Optional parameter: File to remove star from..</param>
        /// <param name="fileComment">Optional parameter: File comment to remove star from..</param>
        /// <param name="timestamp">Optional parameter: Timestamp of the message to remove star from..</param>
        /// <param name="cancellationToken"> cancellationToken. </param>
        /// <returns>Returns the ApiResponse of Models.StarsRemoveSchema response from the API call.</returns>
        public async Task<ApiResponse<Models.StarsRemoveSchema>> StarsRemoveAsync(
                string token,
                string channel = null,
                string file = null,
                string fileComment = null,
                string timestamp = null,
                CancellationToken cancellationToken = default)
            => await CreateApiCall<Models.StarsRemoveSchema>()
              .RequestBuilder(requestBuilder => requestBuilder
                  .Setup(HttpMethod.Post, "/stars.remove")
                  .WithAuth("slackAuth")
                  .Parameters(parameters => parameters
                      .Header(header => header.Setup("token", token).Required())
                      .Header(header => header.Setup("Content-Type", "application/x-www-form-urlencoded"))
                      .Form(form => form.Setup("channel", channel))
                      .Form(form => form.Setup("file", file))
                      .Form(form => form.Setup("file_comment", fileComment))
                      .Form(form => form.Setup("timestamp", timestamp))))
              .ResponseHandler(responseHandler => responseHandler
                  .ErrorCase("0", CreateErrorCase("Typical error response", (errorReason, context) => new StarsRemoveErrorSchemaException(errorReason, context))))
              .ExecuteAsync(cancellationToken).ConfigureAwait(false);
    }
}