// <copyright file="TeamProfileController.cs" company="APIMatic">
// SlackWebApi.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using APIMatic.Core;
using APIMatic.Core.Utilities;
using SlackWebApi.Standard.Exceptions;
using SlackWebApi.Standard.Http.Response;
using System.Net.Http;
using System.Threading;
using System.Threading.Tasks;

namespace SlackWebApi.Standard.Controllers
{
    /// <summary>
    /// TeamProfileController.
    /// </summary>
    public class TeamProfileController : BaseController
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="TeamProfileController"/> class.
        /// </summary>
        internal TeamProfileController(GlobalConfiguration globalConfiguration) : base(globalConfiguration) { }

        /// <summary>
        /// Retrieve a team's profile.
        /// </summary>
        /// <param name="token">Required parameter: Authentication token. Requires scope: `users.profile:read`.</param>
        /// <param name="visibility">Optional parameter: Filter by visibility..</param>
        /// <returns>Returns the ApiResponse of Models.TeamProfileGetSuccessSchema response from the API call.</returns>
        public ApiResponse<Models.TeamProfileGetSuccessSchema> TeamProfileGet(
                string token,
                string visibility = null)
            => CoreHelper.RunTask(TeamProfileGetAsync(token, visibility));

        /// <summary>
        /// Retrieve a team's profile.
        /// </summary>
        /// <param name="token">Required parameter: Authentication token. Requires scope: `users.profile:read`.</param>
        /// <param name="visibility">Optional parameter: Filter by visibility..</param>
        /// <param name="cancellationToken"> cancellationToken. </param>
        /// <returns>Returns the ApiResponse of Models.TeamProfileGetSuccessSchema response from the API call.</returns>
        public async Task<ApiResponse<Models.TeamProfileGetSuccessSchema>> TeamProfileGetAsync(
                string token,
                string visibility = null,
                CancellationToken cancellationToken = default)
            => await CreateApiCall<Models.TeamProfileGetSuccessSchema>()
              .RequestBuilder(requestBuilder => requestBuilder
                  .Setup(HttpMethod.Get, "/team.profile.get")
                  .WithAuth("slackAuth")
                  .Parameters(parameters => parameters
                      .Query(query => query.Setup("token", token).Required())
                      .Header(header => header.Setup("Content-Type", "application/x-www-form-urlencoded"))
                      .Query(query => query.Setup("visibility", visibility))))
              .ResponseHandler(responseHandler => responseHandler
                  .ErrorCase("0", CreateErrorCase("Typical error response", (errorReason, context) => new TeamProfileGetErrorSchemaException(errorReason, context))))
              .ExecuteAsync(cancellationToken).ConfigureAwait(false);
    }
}