// <copyright file="UsersProfileController.cs" company="APIMatic">
// SlackWebApi.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using APIMatic.Core;
using APIMatic.Core.Utilities;
using SlackWebApi.Standard.Exceptions;
using SlackWebApi.Standard.Http.Response;
using System.Net.Http;
using System.Threading;
using System.Threading.Tasks;

namespace SlackWebApi.Standard.Controllers
{
    /// <summary>
    /// UsersProfileController.
    /// </summary>
    public class UsersProfileController : BaseController
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="UsersProfileController"/> class.
        /// </summary>
        internal UsersProfileController(GlobalConfiguration globalConfiguration) : base(globalConfiguration) { }

        /// <summary>
        /// Retrieves a user's profile information.
        /// </summary>
        /// <param name="token">Required parameter: Authentication token. Requires scope: `users.profile:read`.</param>
        /// <param name="includeLabels">Optional parameter: Include labels for each ID in custom profile fields.</param>
        /// <param name="user">Optional parameter: User to retrieve profile info for.</param>
        /// <returns>Returns the ApiResponse of Models.UsersProfileGetSchema response from the API call.</returns>
        public ApiResponse<Models.UsersProfileGetSchema> UsersProfileGet(
                string token,
                bool? includeLabels = null,
                string user = null)
            => CoreHelper.RunTask(UsersProfileGetAsync(token, includeLabels, user));

        /// <summary>
        /// Retrieves a user's profile information.
        /// </summary>
        /// <param name="token">Required parameter: Authentication token. Requires scope: `users.profile:read`.</param>
        /// <param name="includeLabels">Optional parameter: Include labels for each ID in custom profile fields.</param>
        /// <param name="user">Optional parameter: User to retrieve profile info for.</param>
        /// <param name="cancellationToken"> cancellationToken. </param>
        /// <returns>Returns the ApiResponse of Models.UsersProfileGetSchema response from the API call.</returns>
        public async Task<ApiResponse<Models.UsersProfileGetSchema>> UsersProfileGetAsync(
                string token,
                bool? includeLabels = null,
                string user = null,
                CancellationToken cancellationToken = default)
            => await CreateApiCall<Models.UsersProfileGetSchema>()
              .RequestBuilder(requestBuilder => requestBuilder
                  .Setup(HttpMethod.Get, "/users.profile.get")
                  .WithAuth("slackAuth")
                  .Parameters(parameters => parameters
                      .Query(query => query.Setup("token", token).Required())
                      .Header(header => header.Setup("Content-Type", "application/x-www-form-urlencoded"))
                      .Query(query => query.Setup("include_labels", includeLabels))
                      .Query(query => query.Setup("user", user))))
              .ResponseHandler(responseHandler => responseHandler
                  .ErrorCase("0", CreateErrorCase("Typical error response", (errorReason, context) => new UsersProfileGetErrorSchemaException(errorReason, context))))
              .ExecuteAsync(cancellationToken).ConfigureAwait(false);

        /// <summary>
        /// Set the profile information for a user.
        /// </summary>
        /// <param name="token">Required parameter: Authentication token. Requires scope: `users.profile:write`.</param>
        /// <param name="name">Optional parameter: Name of a single key to set. Usable only if `profile` is not passed..</param>
        /// <param name="profile">Optional parameter: Collection of key:value pairs presented as a URL-encoded JSON hash. At most 50 fields may be set. Each field name is limited to 255 characters..</param>
        /// <param name="user">Optional parameter: ID of user to change. This argument may only be specified by team admins on paid teams..</param>
        /// <param name="mValue">Optional parameter: Value to set a single key to. Usable only if `profile` is not passed..</param>
        /// <returns>Returns the ApiResponse of Models.UsersProfileSetSchema response from the API call.</returns>
        public ApiResponse<Models.UsersProfileSetSchema> UsersProfileSet(
                string token,
                string name = null,
                string profile = null,
                string user = null,
                string mValue = null)
            => CoreHelper.RunTask(UsersProfileSetAsync(token, name, profile, user, mValue));

        /// <summary>
        /// Set the profile information for a user.
        /// </summary>
        /// <param name="token">Required parameter: Authentication token. Requires scope: `users.profile:write`.</param>
        /// <param name="name">Optional parameter: Name of a single key to set. Usable only if `profile` is not passed..</param>
        /// <param name="profile">Optional parameter: Collection of key:value pairs presented as a URL-encoded JSON hash. At most 50 fields may be set. Each field name is limited to 255 characters..</param>
        /// <param name="user">Optional parameter: ID of user to change. This argument may only be specified by team admins on paid teams..</param>
        /// <param name="mValue">Optional parameter: Value to set a single key to. Usable only if `profile` is not passed..</param>
        /// <param name="cancellationToken"> cancellationToken. </param>
        /// <returns>Returns the ApiResponse of Models.UsersProfileSetSchema response from the API call.</returns>
        public async Task<ApiResponse<Models.UsersProfileSetSchema>> UsersProfileSetAsync(
                string token,
                string name = null,
                string profile = null,
                string user = null,
                string mValue = null,
                CancellationToken cancellationToken = default)
            => await CreateApiCall<Models.UsersProfileSetSchema>()
              .RequestBuilder(requestBuilder => requestBuilder
                  .Setup(HttpMethod.Post, "/users.profile.set")
                  .WithAuth("slackAuth")
                  .Parameters(parameters => parameters
                      .Header(header => header.Setup("token", token).Required())
                      .Header(header => header.Setup("Content-Type", "application/x-www-form-urlencoded"))
                      .Form(form => form.Setup("name", name))
                      .Form(form => form.Setup("profile", profile))
                      .Form(form => form.Setup("user", user))
                      .Form(form => form.Setup("value", mValue))))
              .ResponseHandler(responseHandler => responseHandler
                  .ErrorCase("0", CreateErrorCase("Typical error response", (errorReason, context) => new UsersProfileSetErrorSchemaException(errorReason, context))))
              .ExecuteAsync(cancellationToken).ConfigureAwait(false);
    }
}