// <copyright file="ViewsController.cs" company="APIMatic">
// SlackWebApi.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using APIMatic.Core;
using APIMatic.Core.Utilities;
using SlackWebApi.Standard.Exceptions;
using SlackWebApi.Standard.Http.Response;
using System.Net.Http;
using System.Threading;
using System.Threading.Tasks;

namespace SlackWebApi.Standard.Controllers
{
    /// <summary>
    /// ViewsController.
    /// </summary>
    public class ViewsController : BaseController
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ViewsController"/> class.
        /// </summary>
        internal ViewsController(GlobalConfiguration globalConfiguration) : base(globalConfiguration) { }

        /// <summary>
        /// Open a view for a user.
        /// </summary>
        /// <param name="token">Required parameter: Authentication token. Requires scope: `none`.</param>
        /// <param name="triggerId">Required parameter: Exchange a trigger to post to the user..</param>
        /// <param name="view">Required parameter: A [view payload](/reference/surfaces/views). This must be a JSON-encoded string..</param>
        /// <returns>Returns the ApiResponse of Models.DefaultSuccessTemplate response from the API call.</returns>
        public ApiResponse<Models.DefaultSuccessTemplate> ViewsOpen(
                string token,
                string triggerId,
                string view)
            => CoreHelper.RunTask(ViewsOpenAsync(token, triggerId, view));

        /// <summary>
        /// Open a view for a user.
        /// </summary>
        /// <param name="token">Required parameter: Authentication token. Requires scope: `none`.</param>
        /// <param name="triggerId">Required parameter: Exchange a trigger to post to the user..</param>
        /// <param name="view">Required parameter: A [view payload](/reference/surfaces/views). This must be a JSON-encoded string..</param>
        /// <param name="cancellationToken"> cancellationToken. </param>
        /// <returns>Returns the ApiResponse of Models.DefaultSuccessTemplate response from the API call.</returns>
        public async Task<ApiResponse<Models.DefaultSuccessTemplate>> ViewsOpenAsync(
                string token,
                string triggerId,
                string view,
                CancellationToken cancellationToken = default)
            => await CreateApiCall<Models.DefaultSuccessTemplate>()
              .RequestBuilder(requestBuilder => requestBuilder
                  .Setup(HttpMethod.Get, "/views.open")
                  .WithAuth("slackAuth")
                  .Parameters(parameters => parameters
                      .Header(header => header.Setup("token", token).Required())
                      .Query(query => query.Setup("trigger_id", triggerId).Required())
                      .Query(query => query.Setup("view", view).Required())
                      .Header(header => header.Setup("Content-Type", "application/x-www-form-urlencoded"))))
              .ResponseHandler(responseHandler => responseHandler
                  .ErrorCase("0", CreateErrorCase("Typical error response, before getting to any possible validation errors.", (errorReason, context) => new DefaultErrorTemplateException(errorReason, context))))
              .ExecuteAsync(cancellationToken).ConfigureAwait(false);

        /// <summary>
        /// Publish a static view for a User.
        /// </summary>
        /// <param name="token">Required parameter: Authentication token. Requires scope: `none`.</param>
        /// <param name="userId">Required parameter: `id` of the user you want publish a view to..</param>
        /// <param name="view">Required parameter: A [view payload](/reference/surfaces/views). This must be a JSON-encoded string..</param>
        /// <param name="hash">Optional parameter: A string that represents view state to protect against possible race conditions..</param>
        /// <returns>Returns the ApiResponse of Models.DefaultSuccessTemplate response from the API call.</returns>
        public ApiResponse<Models.DefaultSuccessTemplate> ViewsPublish(
                string token,
                string userId,
                string view,
                string hash = null)
            => CoreHelper.RunTask(ViewsPublishAsync(token, userId, view, hash));

        /// <summary>
        /// Publish a static view for a User.
        /// </summary>
        /// <param name="token">Required parameter: Authentication token. Requires scope: `none`.</param>
        /// <param name="userId">Required parameter: `id` of the user you want publish a view to..</param>
        /// <param name="view">Required parameter: A [view payload](/reference/surfaces/views). This must be a JSON-encoded string..</param>
        /// <param name="hash">Optional parameter: A string that represents view state to protect against possible race conditions..</param>
        /// <param name="cancellationToken"> cancellationToken. </param>
        /// <returns>Returns the ApiResponse of Models.DefaultSuccessTemplate response from the API call.</returns>
        public async Task<ApiResponse<Models.DefaultSuccessTemplate>> ViewsPublishAsync(
                string token,
                string userId,
                string view,
                string hash = null,
                CancellationToken cancellationToken = default)
            => await CreateApiCall<Models.DefaultSuccessTemplate>()
              .RequestBuilder(requestBuilder => requestBuilder
                  .Setup(HttpMethod.Get, "/views.publish")
                  .WithAuth("slackAuth")
                  .Parameters(parameters => parameters
                      .Header(header => header.Setup("token", token).Required())
                      .Query(query => query.Setup("user_id", userId).Required())
                      .Query(query => query.Setup("view", view).Required())
                      .Header(header => header.Setup("Content-Type", "application/x-www-form-urlencoded"))
                      .Query(query => query.Setup("hash", hash))))
              .ResponseHandler(responseHandler => responseHandler
                  .ErrorCase("0", CreateErrorCase("Typical error response, before getting to any possible validation errors.", (errorReason, context) => new DefaultErrorTemplateException(errorReason, context))))
              .ExecuteAsync(cancellationToken).ConfigureAwait(false);

        /// <summary>
        /// Push a view onto the stack of a root view.
        /// </summary>
        /// <param name="token">Required parameter: Authentication token. Requires scope: `none`.</param>
        /// <param name="triggerId">Required parameter: Exchange a trigger to post to the user..</param>
        /// <param name="view">Required parameter: A [view payload](/reference/surfaces/views). This must be a JSON-encoded string..</param>
        /// <returns>Returns the ApiResponse of Models.DefaultSuccessTemplate response from the API call.</returns>
        public ApiResponse<Models.DefaultSuccessTemplate> ViewsPush(
                string token,
                string triggerId,
                string view)
            => CoreHelper.RunTask(ViewsPushAsync(token, triggerId, view));

        /// <summary>
        /// Push a view onto the stack of a root view.
        /// </summary>
        /// <param name="token">Required parameter: Authentication token. Requires scope: `none`.</param>
        /// <param name="triggerId">Required parameter: Exchange a trigger to post to the user..</param>
        /// <param name="view">Required parameter: A [view payload](/reference/surfaces/views). This must be a JSON-encoded string..</param>
        /// <param name="cancellationToken"> cancellationToken. </param>
        /// <returns>Returns the ApiResponse of Models.DefaultSuccessTemplate response from the API call.</returns>
        public async Task<ApiResponse<Models.DefaultSuccessTemplate>> ViewsPushAsync(
                string token,
                string triggerId,
                string view,
                CancellationToken cancellationToken = default)
            => await CreateApiCall<Models.DefaultSuccessTemplate>()
              .RequestBuilder(requestBuilder => requestBuilder
                  .Setup(HttpMethod.Get, "/views.push")
                  .WithAuth("slackAuth")
                  .Parameters(parameters => parameters
                      .Header(header => header.Setup("token", token).Required())
                      .Query(query => query.Setup("trigger_id", triggerId).Required())
                      .Query(query => query.Setup("view", view).Required())
                      .Header(header => header.Setup("Content-Type", "application/x-www-form-urlencoded"))))
              .ResponseHandler(responseHandler => responseHandler
                  .ErrorCase("0", CreateErrorCase("Typical error response.", (errorReason, context) => new DefaultErrorTemplateException(errorReason, context))))
              .ExecuteAsync(cancellationToken).ConfigureAwait(false);

        /// <summary>
        /// Update an existing view.
        /// </summary>
        /// <param name="token">Required parameter: Authentication token. Requires scope: `none`.</param>
        /// <param name="viewId">Optional parameter: A unique identifier of the view to be updated. Either `view_id` or `external_id` is required..</param>
        /// <param name="externalId">Optional parameter: A unique identifier of the view set by the developer. Must be unique for all views on a team. Max length of 255 characters. Either `view_id` or `external_id` is required..</param>
        /// <param name="view">Optional parameter: A [view object](/reference/surfaces/views). This must be a JSON-encoded string..</param>
        /// <param name="hash">Optional parameter: A string that represents view state to protect against possible race conditions..</param>
        /// <returns>Returns the ApiResponse of Models.DefaultSuccessTemplate response from the API call.</returns>
        public ApiResponse<Models.DefaultSuccessTemplate> ViewsUpdate(
                string token,
                string viewId = null,
                string externalId = null,
                string view = null,
                string hash = null)
            => CoreHelper.RunTask(ViewsUpdateAsync(token, viewId, externalId, view, hash));

        /// <summary>
        /// Update an existing view.
        /// </summary>
        /// <param name="token">Required parameter: Authentication token. Requires scope: `none`.</param>
        /// <param name="viewId">Optional parameter: A unique identifier of the view to be updated. Either `view_id` or `external_id` is required..</param>
        /// <param name="externalId">Optional parameter: A unique identifier of the view set by the developer. Must be unique for all views on a team. Max length of 255 characters. Either `view_id` or `external_id` is required..</param>
        /// <param name="view">Optional parameter: A [view object](/reference/surfaces/views). This must be a JSON-encoded string..</param>
        /// <param name="hash">Optional parameter: A string that represents view state to protect against possible race conditions..</param>
        /// <param name="cancellationToken"> cancellationToken. </param>
        /// <returns>Returns the ApiResponse of Models.DefaultSuccessTemplate response from the API call.</returns>
        public async Task<ApiResponse<Models.DefaultSuccessTemplate>> ViewsUpdateAsync(
                string token,
                string viewId = null,
                string externalId = null,
                string view = null,
                string hash = null,
                CancellationToken cancellationToken = default)
            => await CreateApiCall<Models.DefaultSuccessTemplate>()
              .RequestBuilder(requestBuilder => requestBuilder
                  .Setup(HttpMethod.Get, "/views.update")
                  .WithAuth("slackAuth")
                  .Parameters(parameters => parameters
                      .Header(header => header.Setup("token", token).Required())
                      .Header(header => header.Setup("Content-Type", "application/x-www-form-urlencoded"))
                      .Query(query => query.Setup("view_id", viewId))
                      .Query(query => query.Setup("external_id", externalId))
                      .Query(query => query.Setup("view", view))
                      .Query(query => query.Setup("hash", hash))))
              .ResponseHandler(responseHandler => responseHandler
                  .ErrorCase("0", CreateErrorCase("Typical error response.", (errorReason, context) => new DefaultErrorTemplateException(errorReason, context))))
              .ExecuteAsync(cancellationToken).ConfigureAwait(false);
    }
}