// <copyright file="SlackWebApiClient.cs" company="APIMatic">
// SlackWebApi.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using APIMatic.Core;
using APIMatic.Core.Authentication;
using APIMatic.Core.Utilities;
using APIMatic.Core.Utilities.Logger.Configuration;
using Microsoft.Extensions.Configuration;
using SlackWebApi.Standard.Authentication;
using SlackWebApi.Standard.Controllers;
using SlackWebApi.Standard.Http.Client;
using SlackWebApi.Standard.Logging;
using System;
using System.Collections.Generic;

namespace SlackWebApi.Standard
{
    /// <summary>
    /// The gateway for the SDK. This class acts as a factory for Controller and
    /// holds the configuration of the SDK.
    /// </summary>
    public sealed class SlackWebApiClient : IConfiguration
    {
        // A map of environments and their corresponding servers/baseurls
        private static readonly Dictionary<Environment, Dictionary<Enum, string>> EnvironmentsMap =
            new Dictionary<Environment, Dictionary<Enum, string>>
        {
            {
                Environment.Production, new Dictionary<Enum, string>
                {
                    { Server.Default, "https://slack.com/api" },
                    { Server.AuthServer, "https://slack.com/oauth" },
                }
            },
        };

        private readonly GlobalConfiguration globalConfiguration;
        private SdkLoggingConfiguration sdkLoggingConfiguration;
        private const string userAgent = "DotNet-SDK/1.0.0 [OS: {os-info}, Engine: {engine}/{engine-version}]";
        private readonly HttpCallback httpCallback;
        private readonly Lazy<AdminAppsController> adminApps;
        private readonly Lazy<AdminAppsApprovedController> adminAppsApproved;
        private readonly Lazy<AdminAppsRequestsController> adminAppsRequests;
        private readonly Lazy<AdminAppsRestrictedController> adminAppsRestricted;
        private readonly Lazy<AdminConversationsController> adminConversations;
        private readonly Lazy<AdminConversationsEkmController> adminConversationsEkm;
        private readonly Lazy<AdminConversationsRestrictAccessController> adminConversationsRestrictAccess;
        private readonly Lazy<AdminEmojiController> adminEmoji;
        private readonly Lazy<AdminInviteRequestsController> adminInviteRequests;
        private readonly Lazy<AdminInviteRequestsApprovedController> adminInviteRequestsApproved;
        private readonly Lazy<AdminInviteRequestsDeniedController> adminInviteRequestsDenied;
        private readonly Lazy<AdminTeamsAdminsController> adminTeamsAdmins;
        private readonly Lazy<AdminTeamsController> adminTeams;
        private readonly Lazy<AdminTeamsOwnersController> adminTeamsOwners;
        private readonly Lazy<AdminTeamsSettingsController> adminTeamsSettings;
        private readonly Lazy<AdminUsergroupsController> adminUsergroups;
        private readonly Lazy<AdminUsersController> adminUsers;
        private readonly Lazy<AdminUsersSessionController> adminUsersSession;
        private readonly Lazy<ApiController> api;
        private readonly Lazy<AppsEventAuthorizationsController> appsEventAuthorizations;
        private readonly Lazy<AppsPermissionsController> appsPermissions;
        private readonly Lazy<AppsPermissionsResourcesController> appsPermissionsResources;
        private readonly Lazy<AppsPermissionsScopesController> appsPermissionsScopes;
        private readonly Lazy<AppsPermissionsUsersController> appsPermissionsUsers;
        private readonly Lazy<AppsController> apps;
        private readonly Lazy<AuthController> auth;
        private readonly Lazy<BotsController> bots;
        private readonly Lazy<CallsController> calls;
        private readonly Lazy<CallsParticipantsController> callsParticipants;
        private readonly Lazy<ChatController> chat;
        private readonly Lazy<ChatScheduledMessagesController> chatScheduledMessages;
        private readonly Lazy<ConversationsController> conversations;
        private readonly Lazy<DialogController> dialog;
        private readonly Lazy<DndController> dnd;
        private readonly Lazy<EmojiController> emoji;
        private readonly Lazy<FilesCommentsController> filesComments;
        private readonly Lazy<FilesController> files;
        private readonly Lazy<FilesRemoteController> filesRemote;
        private readonly Lazy<MigrationController> migration;
        private readonly Lazy<OauthController> oauth;
        private readonly Lazy<OauthV2Controller> oauthV2;
        private readonly Lazy<PinsController> pins;
        private readonly Lazy<ReactionsController> reactions;
        private readonly Lazy<RemindersController> reminders;
        private readonly Lazy<RtmController> rtm;
        private readonly Lazy<SearchController> search;
        private readonly Lazy<StarsController> stars;
        private readonly Lazy<TeamController> team;
        private readonly Lazy<TeamProfileController> teamProfile;
        private readonly Lazy<UsergroupsController> usergroups;
        private readonly Lazy<UsergroupsUsersController> usergroupsUsers;
        private readonly Lazy<UsersController> users;
        private readonly Lazy<UsersProfileController> usersProfile;
        private readonly Lazy<ViewsController> views;
        private readonly Lazy<WorkflowsController> workflows;
        private readonly Lazy<OauthAuthorizationController> oauthAuthorization;

        private SlackWebApiClient(
            Environment environment,
            AuthorizationCodeAuthModel authorizationCodeAuthModel,
            HttpCallback httpCallback,
            IHttpClientConfiguration httpClientConfiguration,
            SdkLoggingConfiguration sdkLoggingConfiguration)
        {
            this.Environment = environment;
            this.httpCallback = httpCallback;
            this.HttpClientConfiguration = httpClientConfiguration;
            this.sdkLoggingConfiguration = sdkLoggingConfiguration;
            AuthorizationCodeAuthModel = authorizationCodeAuthModel;
            var authorizationCodeAuthManager = new AuthorizationCodeAuthManager(authorizationCodeAuthModel,
                () => globalConfiguration,
                () => OauthAuthorizationController);
            globalConfiguration = new GlobalConfiguration.Builder()
                .AuthManagers(new Dictionary<string, AuthManager> {
                    {"slackAuth", authorizationCodeAuthManager},
                })
                .ApiCallback(httpCallback)
                .HttpConfiguration(httpClientConfiguration)
                .ServerUrls(EnvironmentsMap[environment], Server.Default)
                .LoggingConfig(sdkLoggingConfiguration)
                .UserAgent(userAgent)
                .Build();
            AuthorizationCodeAuth = authorizationCodeAuthManager;

            this.adminApps = new Lazy<AdminAppsController>(
                () => new AdminAppsController(globalConfiguration));
            this.adminAppsApproved = new Lazy<AdminAppsApprovedController>(
                () => new AdminAppsApprovedController(globalConfiguration));
            this.adminAppsRequests = new Lazy<AdminAppsRequestsController>(
                () => new AdminAppsRequestsController(globalConfiguration));
            this.adminAppsRestricted = new Lazy<AdminAppsRestrictedController>(
                () => new AdminAppsRestrictedController(globalConfiguration));
            this.adminConversations = new Lazy<AdminConversationsController>(
                () => new AdminConversationsController(globalConfiguration));
            this.adminConversationsEkm = new Lazy<AdminConversationsEkmController>(
                () => new AdminConversationsEkmController(globalConfiguration));
            this.adminConversationsRestrictAccess = new Lazy<AdminConversationsRestrictAccessController>(
                () => new AdminConversationsRestrictAccessController(globalConfiguration));
            this.adminEmoji = new Lazy<AdminEmojiController>(
                () => new AdminEmojiController(globalConfiguration));
            this.adminInviteRequests = new Lazy<AdminInviteRequestsController>(
                () => new AdminInviteRequestsController(globalConfiguration));
            this.adminInviteRequestsApproved = new Lazy<AdminInviteRequestsApprovedController>(
                () => new AdminInviteRequestsApprovedController(globalConfiguration));
            this.adminInviteRequestsDenied = new Lazy<AdminInviteRequestsDeniedController>(
                () => new AdminInviteRequestsDeniedController(globalConfiguration));
            this.adminTeamsAdmins = new Lazy<AdminTeamsAdminsController>(
                () => new AdminTeamsAdminsController(globalConfiguration));
            this.adminTeams = new Lazy<AdminTeamsController>(
                () => new AdminTeamsController(globalConfiguration));
            this.adminTeamsOwners = new Lazy<AdminTeamsOwnersController>(
                () => new AdminTeamsOwnersController(globalConfiguration));
            this.adminTeamsSettings = new Lazy<AdminTeamsSettingsController>(
                () => new AdminTeamsSettingsController(globalConfiguration));
            this.adminUsergroups = new Lazy<AdminUsergroupsController>(
                () => new AdminUsergroupsController(globalConfiguration));
            this.adminUsers = new Lazy<AdminUsersController>(
                () => new AdminUsersController(globalConfiguration));
            this.adminUsersSession = new Lazy<AdminUsersSessionController>(
                () => new AdminUsersSessionController(globalConfiguration));
            this.api = new Lazy<ApiController>(
                () => new ApiController(globalConfiguration));
            this.appsEventAuthorizations = new Lazy<AppsEventAuthorizationsController>(
                () => new AppsEventAuthorizationsController(globalConfiguration));
            this.appsPermissions = new Lazy<AppsPermissionsController>(
                () => new AppsPermissionsController(globalConfiguration));
            this.appsPermissionsResources = new Lazy<AppsPermissionsResourcesController>(
                () => new AppsPermissionsResourcesController(globalConfiguration));
            this.appsPermissionsScopes = new Lazy<AppsPermissionsScopesController>(
                () => new AppsPermissionsScopesController(globalConfiguration));
            this.appsPermissionsUsers = new Lazy<AppsPermissionsUsersController>(
                () => new AppsPermissionsUsersController(globalConfiguration));
            this.apps = new Lazy<AppsController>(
                () => new AppsController(globalConfiguration));
            this.auth = new Lazy<AuthController>(
                () => new AuthController(globalConfiguration));
            this.bots = new Lazy<BotsController>(
                () => new BotsController(globalConfiguration));
            this.calls = new Lazy<CallsController>(
                () => new CallsController(globalConfiguration));
            this.callsParticipants = new Lazy<CallsParticipantsController>(
                () => new CallsParticipantsController(globalConfiguration));
            this.chat = new Lazy<ChatController>(
                () => new ChatController(globalConfiguration));
            this.chatScheduledMessages = new Lazy<ChatScheduledMessagesController>(
                () => new ChatScheduledMessagesController(globalConfiguration));
            this.conversations = new Lazy<ConversationsController>(
                () => new ConversationsController(globalConfiguration));
            this.dialog = new Lazy<DialogController>(
                () => new DialogController(globalConfiguration));
            this.dnd = new Lazy<DndController>(
                () => new DndController(globalConfiguration));
            this.emoji = new Lazy<EmojiController>(
                () => new EmojiController(globalConfiguration));
            this.filesComments = new Lazy<FilesCommentsController>(
                () => new FilesCommentsController(globalConfiguration));
            this.files = new Lazy<FilesController>(
                () => new FilesController(globalConfiguration));
            this.filesRemote = new Lazy<FilesRemoteController>(
                () => new FilesRemoteController(globalConfiguration));
            this.migration = new Lazy<MigrationController>(
                () => new MigrationController(globalConfiguration));
            this.oauth = new Lazy<OauthController>(
                () => new OauthController(globalConfiguration));
            this.oauthV2 = new Lazy<OauthV2Controller>(
                () => new OauthV2Controller(globalConfiguration));
            this.pins = new Lazy<PinsController>(
                () => new PinsController(globalConfiguration));
            this.reactions = new Lazy<ReactionsController>(
                () => new ReactionsController(globalConfiguration));
            this.reminders = new Lazy<RemindersController>(
                () => new RemindersController(globalConfiguration));
            this.rtm = new Lazy<RtmController>(
                () => new RtmController(globalConfiguration));
            this.search = new Lazy<SearchController>(
                () => new SearchController(globalConfiguration));
            this.stars = new Lazy<StarsController>(
                () => new StarsController(globalConfiguration));
            this.team = new Lazy<TeamController>(
                () => new TeamController(globalConfiguration));
            this.teamProfile = new Lazy<TeamProfileController>(
                () => new TeamProfileController(globalConfiguration));
            this.usergroups = new Lazy<UsergroupsController>(
                () => new UsergroupsController(globalConfiguration));
            this.usergroupsUsers = new Lazy<UsergroupsUsersController>(
                () => new UsergroupsUsersController(globalConfiguration));
            this.users = new Lazy<UsersController>(
                () => new UsersController(globalConfiguration));
            this.usersProfile = new Lazy<UsersProfileController>(
                () => new UsersProfileController(globalConfiguration));
            this.views = new Lazy<ViewsController>(
                () => new ViewsController(globalConfiguration));
            this.workflows = new Lazy<WorkflowsController>(
                () => new WorkflowsController(globalConfiguration));
            this.oauthAuthorization = new Lazy<OauthAuthorizationController>(
                () => new OauthAuthorizationController(globalConfiguration));
        }

        /// <summary>
        /// Gets AdminAppsController controller.
        /// </summary>
        public AdminAppsController AdminAppsController => this.adminApps.Value;

        /// <summary>
        /// Gets AdminAppsApprovedController controller.
        /// </summary>
        public AdminAppsApprovedController AdminAppsApprovedController => this.adminAppsApproved.Value;

        /// <summary>
        /// Gets AdminAppsRequestsController controller.
        /// </summary>
        public AdminAppsRequestsController AdminAppsRequestsController => this.adminAppsRequests.Value;

        /// <summary>
        /// Gets AdminAppsRestrictedController controller.
        /// </summary>
        public AdminAppsRestrictedController AdminAppsRestrictedController => this.adminAppsRestricted.Value;

        /// <summary>
        /// Gets AdminConversationsController controller.
        /// </summary>
        public AdminConversationsController AdminConversationsController => this.adminConversations.Value;

        /// <summary>
        /// Gets AdminConversationsEkmController controller.
        /// </summary>
        public AdminConversationsEkmController AdminConversationsEkmController => this.adminConversationsEkm.Value;

        /// <summary>
        /// Gets AdminConversationsRestrictAccessController controller.
        /// </summary>
        public AdminConversationsRestrictAccessController AdminConversationsRestrictAccessController => this.adminConversationsRestrictAccess.Value;

        /// <summary>
        /// Gets AdminEmojiController controller.
        /// </summary>
        public AdminEmojiController AdminEmojiController => this.adminEmoji.Value;

        /// <summary>
        /// Gets AdminInviteRequestsController controller.
        /// </summary>
        public AdminInviteRequestsController AdminInviteRequestsController => this.adminInviteRequests.Value;

        /// <summary>
        /// Gets AdminInviteRequestsApprovedController controller.
        /// </summary>
        public AdminInviteRequestsApprovedController AdminInviteRequestsApprovedController => this.adminInviteRequestsApproved.Value;

        /// <summary>
        /// Gets AdminInviteRequestsDeniedController controller.
        /// </summary>
        public AdminInviteRequestsDeniedController AdminInviteRequestsDeniedController => this.adminInviteRequestsDenied.Value;

        /// <summary>
        /// Gets AdminTeamsAdminsController controller.
        /// </summary>
        public AdminTeamsAdminsController AdminTeamsAdminsController => this.adminTeamsAdmins.Value;

        /// <summary>
        /// Gets AdminTeamsController controller.
        /// </summary>
        public AdminTeamsController AdminTeamsController => this.adminTeams.Value;

        /// <summary>
        /// Gets AdminTeamsOwnersController controller.
        /// </summary>
        public AdminTeamsOwnersController AdminTeamsOwnersController => this.adminTeamsOwners.Value;

        /// <summary>
        /// Gets AdminTeamsSettingsController controller.
        /// </summary>
        public AdminTeamsSettingsController AdminTeamsSettingsController => this.adminTeamsSettings.Value;

        /// <summary>
        /// Gets AdminUsergroupsController controller.
        /// </summary>
        public AdminUsergroupsController AdminUsergroupsController => this.adminUsergroups.Value;

        /// <summary>
        /// Gets AdminUsersController controller.
        /// </summary>
        public AdminUsersController AdminUsersController => this.adminUsers.Value;

        /// <summary>
        /// Gets AdminUsersSessionController controller.
        /// </summary>
        public AdminUsersSessionController AdminUsersSessionController => this.adminUsersSession.Value;

        /// <summary>
        /// Gets ApiController controller.
        /// </summary>
        public ApiController ApiController => this.api.Value;

        /// <summary>
        /// Gets AppsEventAuthorizationsController controller.
        /// </summary>
        public AppsEventAuthorizationsController AppsEventAuthorizationsController => this.appsEventAuthorizations.Value;

        /// <summary>
        /// Gets AppsPermissionsController controller.
        /// </summary>
        public AppsPermissionsController AppsPermissionsController => this.appsPermissions.Value;

        /// <summary>
        /// Gets AppsPermissionsResourcesController controller.
        /// </summary>
        public AppsPermissionsResourcesController AppsPermissionsResourcesController => this.appsPermissionsResources.Value;

        /// <summary>
        /// Gets AppsPermissionsScopesController controller.
        /// </summary>
        public AppsPermissionsScopesController AppsPermissionsScopesController => this.appsPermissionsScopes.Value;

        /// <summary>
        /// Gets AppsPermissionsUsersController controller.
        /// </summary>
        public AppsPermissionsUsersController AppsPermissionsUsersController => this.appsPermissionsUsers.Value;

        /// <summary>
        /// Gets AppsController controller.
        /// </summary>
        public AppsController AppsController => this.apps.Value;

        /// <summary>
        /// Gets AuthController controller.
        /// </summary>
        public AuthController AuthController => this.auth.Value;

        /// <summary>
        /// Gets BotsController controller.
        /// </summary>
        public BotsController BotsController => this.bots.Value;

        /// <summary>
        /// Gets CallsController controller.
        /// </summary>
        public CallsController CallsController => this.calls.Value;

        /// <summary>
        /// Gets CallsParticipantsController controller.
        /// </summary>
        public CallsParticipantsController CallsParticipantsController => this.callsParticipants.Value;

        /// <summary>
        /// Gets ChatController controller.
        /// </summary>
        public ChatController ChatController => this.chat.Value;

        /// <summary>
        /// Gets ChatScheduledMessagesController controller.
        /// </summary>
        public ChatScheduledMessagesController ChatScheduledMessagesController => this.chatScheduledMessages.Value;

        /// <summary>
        /// Gets ConversationsController controller.
        /// </summary>
        public ConversationsController ConversationsController => this.conversations.Value;

        /// <summary>
        /// Gets DialogController controller.
        /// </summary>
        public DialogController DialogController => this.dialog.Value;

        /// <summary>
        /// Gets DndController controller.
        /// </summary>
        public DndController DndController => this.dnd.Value;

        /// <summary>
        /// Gets EmojiController controller.
        /// </summary>
        public EmojiController EmojiController => this.emoji.Value;

        /// <summary>
        /// Gets FilesCommentsController controller.
        /// </summary>
        public FilesCommentsController FilesCommentsController => this.filesComments.Value;

        /// <summary>
        /// Gets FilesController controller.
        /// </summary>
        public FilesController FilesController => this.files.Value;

        /// <summary>
        /// Gets FilesRemoteController controller.
        /// </summary>
        public FilesRemoteController FilesRemoteController => this.filesRemote.Value;

        /// <summary>
        /// Gets MigrationController controller.
        /// </summary>
        public MigrationController MigrationController => this.migration.Value;

        /// <summary>
        /// Gets OauthController controller.
        /// </summary>
        public OauthController OauthController => this.oauth.Value;

        /// <summary>
        /// Gets OauthV2Controller controller.
        /// </summary>
        public OauthV2Controller OauthV2Controller => this.oauthV2.Value;

        /// <summary>
        /// Gets PinsController controller.
        /// </summary>
        public PinsController PinsController => this.pins.Value;

        /// <summary>
        /// Gets ReactionsController controller.
        /// </summary>
        public ReactionsController ReactionsController => this.reactions.Value;

        /// <summary>
        /// Gets RemindersController controller.
        /// </summary>
        public RemindersController RemindersController => this.reminders.Value;

        /// <summary>
        /// Gets RtmController controller.
        /// </summary>
        public RtmController RtmController => this.rtm.Value;

        /// <summary>
        /// Gets SearchController controller.
        /// </summary>
        public SearchController SearchController => this.search.Value;

        /// <summary>
        /// Gets StarsController controller.
        /// </summary>
        public StarsController StarsController => this.stars.Value;

        /// <summary>
        /// Gets TeamController controller.
        /// </summary>
        public TeamController TeamController => this.team.Value;

        /// <summary>
        /// Gets TeamProfileController controller.
        /// </summary>
        public TeamProfileController TeamProfileController => this.teamProfile.Value;

        /// <summary>
        /// Gets UsergroupsController controller.
        /// </summary>
        public UsergroupsController UsergroupsController => this.usergroups.Value;

        /// <summary>
        /// Gets UsergroupsUsersController controller.
        /// </summary>
        public UsergroupsUsersController UsergroupsUsersController => this.usergroupsUsers.Value;

        /// <summary>
        /// Gets UsersController controller.
        /// </summary>
        public UsersController UsersController => this.users.Value;

        /// <summary>
        /// Gets UsersProfileController controller.
        /// </summary>
        public UsersProfileController UsersProfileController => this.usersProfile.Value;

        /// <summary>
        /// Gets ViewsController controller.
        /// </summary>
        public ViewsController ViewsController => this.views.Value;

        /// <summary>
        /// Gets WorkflowsController controller.
        /// </summary>
        public WorkflowsController WorkflowsController => this.workflows.Value;

        /// <summary>
        /// Gets OauthAuthorizationController controller.
        /// </summary>
        public OauthAuthorizationController OauthAuthorizationController => this.oauthAuthorization.Value;

        /// <summary>
        /// Gets the configuration of the Http Client associated with this client.
        /// </summary>
        public IHttpClientConfiguration HttpClientConfiguration { get; }

        /// <summary>
        /// Gets Environment.
        /// Current API environment.
        /// </summary>
        public Environment Environment { get; }

        /// <summary>
        /// Gets http callback.
        /// </summary>
        public HttpCallback HttpCallback => this.httpCallback;

        /// <summary>
        /// Gets the credentials to use with AuthorizationCodeAuth.
        /// </summary>
        public IAuthorizationCodeAuth AuthorizationCodeAuth { get; private set; }

        /// <summary>
        /// Gets the credentials model to use with AuthorizationCodeAuth.
        /// </summary>
        public AuthorizationCodeAuthModel AuthorizationCodeAuthModel { get; private set; }

        /// <summary>
        /// Gets the URL for a particular alias in the current environment and appends
        /// it with template parameters.
        /// </summary>
        /// <param name="alias">Default value:DEFAULT.</param>
        /// <returns>Returns the baseurl.</returns>
        public string GetBaseUri(Server alias = Server.Default)
        {
            return globalConfiguration.ServerUrl(alias);
        }

        /// <summary>
        /// Creates an object of the SlackWebApiClient using the values provided for the builder.
        /// </summary>
        /// <returns>Builder.</returns>
        public Builder ToBuilder()
        {
            Builder builder = new Builder()
                .Environment(this.Environment)
                .HttpCallback(httpCallback)
                .LoggingConfig(sdkLoggingConfiguration)
                .HttpClientConfig(config => config.Build());

            if (AuthorizationCodeAuthModel != null)
            {
                builder.AuthorizationCodeAuth(AuthorizationCodeAuthModel.ToBuilder().Build());
            }

            return builder;
        }

        /// <inheritdoc/>
        public override string ToString()
        {
            return
                $"Environment = {this.Environment}, " +
                $"HttpClientConfiguration = {this.HttpClientConfiguration}, ";
        }

        /// <summary>
        /// Creates the client using builder.
        /// </summary>
        /// <returns> SlackWebApiClient.</returns>
        internal static SlackWebApiClient CreateFromEnvironment()
        {
            var builder = new Builder();

            string environment = System.Environment.GetEnvironmentVariable("SLACK_WEB_API_STANDARD_ENVIRONMENT");
            string oauthClientId = System.Environment.GetEnvironmentVariable("SLACK_WEB_API_STANDARD_OAUTH_CLIENT_ID");
            string oauthClientSecret = System.Environment.GetEnvironmentVariable("SLACK_WEB_API_STANDARD_OAUTH_CLIENT_SECRET");
            string oauthRedirectUri = System.Environment.GetEnvironmentVariable("SLACK_WEB_API_STANDARD_OAUTH_REDIRECT_URI");

            if (environment != null)
            {
                builder.Environment(CoreHelper.JsonDeserialize<Environment>($"\"{environment}\""));
            }

            if (oauthClientId != null && oauthClientSecret != null && oauthRedirectUri != null)
            {
                builder.AuthorizationCodeAuth(new AuthorizationCodeAuthModel
                .Builder(oauthClientId, oauthClientSecret, oauthRedirectUri)
                .Build());
            }

            return builder.Build();
        }

        /// <summary>
        /// Creates the client from configuration.
        /// </summary>
        /// <returns> SlackWebApiClient.</returns>
        public static SlackWebApiClient FromConfiguration(IConfigurationSection configuration) =>
            Builder.FromConfiguration(configuration).Build();

        /// <summary>
        /// Builder class.
        /// </summary>
        public class Builder
        {
            private Environment _environment = SlackWebApi.Standard.Environment.Production;
            private AuthorizationCodeAuthModel _authorizationCodeAuthModel = new AuthorizationCodeAuthModel();
            private HttpClientConfiguration.Builder _httpClientConfig = new HttpClientConfiguration.Builder();
            private HttpCallback _httpCallback;
            private SdkLoggingConfiguration _sdkLoggingConfiguration;

            /// <summary>
            /// Sets credentials for AuthorizationCodeAuth.
            /// </summary>
            /// <param name="authorizationCodeAuthModel">AuthorizationCodeAuthModel.</param>
            /// <returns>Builder.</returns>
            public Builder AuthorizationCodeAuth(AuthorizationCodeAuthModel authorizationCodeAuthModel)
            {
                _authorizationCodeAuthModel = authorizationCodeAuthModel ??
                    throw new ArgumentNullException(nameof(authorizationCodeAuthModel));
                return this;
            }

            /// <summary>
            /// Sets Environment.
            /// </summary>
            /// <param name="environment"> Environment. </param>
            /// <returns> Builder. </returns>
            public Builder Environment(Environment environment)
            {
                _environment = environment;
                return this;
            }

            /// <summary>
            /// Sets HttpClientConfig.
            /// </summary>
            /// <param name="action"> Action. </param>
            /// <returns>Builder.</returns>
            public Builder HttpClientConfig(Action<HttpClientConfiguration.Builder> action)
            {
                if (action is null)
                {
                    throw new ArgumentNullException(nameof(action));
                }

                action(_httpClientConfig);
                return this;
            }

            private Builder HttpClientConfig(HttpClientConfiguration.Builder httpClientConfigurationBuilder)
            {
                if (httpClientConfigurationBuilder != null)
                {
                    _httpClientConfig = httpClientConfigurationBuilder;
                }

                return this;
            }

            /// <summary>
            /// Sets the default logging configuration, using the Console logger.
            /// </summary>
            /// <returns>Builder.</returns>
            public Builder LoggingConfig()
            {
                _sdkLoggingConfiguration = SdkLoggingConfiguration.Console();
                return this;
            }

            /// <summary>
            /// Sets the logging configuration using the provided <paramref name="action"/>.
            /// </summary>
            /// <param name="action">The action to perform on the logging configuration builder.</param>
            /// <returns>Builder.</returns>
            /// <exception cref="ArgumentNullException">Thrown when <paramref name="action"/> is null.</exception>
            public Builder LoggingConfig(Action<LogBuilder> action)
            {
                if (action is null) throw new ArgumentNullException(nameof(action));
                var logBuilder =
                    LogBuilder.CreateFromConfig(_sdkLoggingConfiguration ?? SdkLoggingConfiguration.Console());
                action(logBuilder);
                _sdkLoggingConfiguration = logBuilder.Build();
                return this;
            }

            internal Builder LoggingConfig(SdkLoggingConfiguration configuration)
            {
                _sdkLoggingConfiguration = configuration;
                return this;
            }

            /// <summary>
            /// Sets the HttpCallback for the Builder.
            /// </summary>
            /// <param name="httpCallback"> http callback. </param>
            /// <returns>Builder.</returns>
            public Builder HttpCallback(HttpCallback httpCallback)
            {
                _httpCallback = httpCallback;
                return this;
            }

            /// <summary>
            /// Creates an object of the SlackWebApiClient using the values provided for the builder.
            /// </summary>
            /// <returns>SlackWebApiClient.</returns>
            public SlackWebApiClient Build()
            {
                if (_authorizationCodeAuthModel.OauthClientId == null || _authorizationCodeAuthModel.OauthClientSecret == null || _authorizationCodeAuthModel.OauthRedirectUri == null)
                {
                    _authorizationCodeAuthModel = null;
                }
                return new SlackWebApiClient(
                    _environment,
                    _authorizationCodeAuthModel,
                    _httpCallback,
                    _httpClientConfig.Build(),
                    _sdkLoggingConfiguration);
            }

            /// <summary>
            /// Creates the client builder from configuration.
            /// </summary>
            /// <returns> Builder.</returns>
            public static Builder FromConfiguration(IConfigurationSection config)
            {
                var builder = new Builder();
                var options = config.Get<SlackWebApiClientOptions>();
                if (options == null) return builder;
                if (options.Environment != null)
                    builder.Environment(options.Environment.Value);
                if (options.AuthorizationCodeAuth != null)
                    builder.AuthorizationCodeAuth(AuthorizationCodeAuthModel.FromOptions(options.AuthorizationCodeAuth));
                if (options.HttpClientConfig != null)
                    builder.HttpClientConfig(Http.Client.HttpClientConfiguration.FromOptions(options.HttpClientConfig));
                if (options.LoggingConfig != null)
                    builder.LoggingConfig(LogBuilder.FromOptions(options.LoggingConfig));
                return builder;
            }
        }

        public class SlackWebApiClientOptions
        {
            public Environment? Environment { get; set; }
            public AuthorizationCodeAuthModelOptions AuthorizationCodeAuth { get; set; }
            public HttpClientConfigurationOptions HttpClientConfig { get; set; }
            public LoggingConfigOptions LoggingConfig { get; set; }
        }
    }
}
