// <copyright file="ApiMethodUsersGetPresence.cs" company="APIMatic">
// SlackWebApi.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using SlackWebApi.Standard.Utilities;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;

namespace SlackWebApi.Standard.Models
{
    /// <summary>
    /// ApiMethodUsersGetPresence.
    /// </summary>
    public class ApiMethodUsersGetPresence
    {
        [JsonExtensionData]
        private readonly IDictionary<string, JToken> additionalProperties;

        private readonly IEnumerable<string> propertyName;

        /// <summary>
        /// Get or set the value associated with the specified key in the AdditionalProperties dictionary.
        /// </summary>
        /// <param name="key">The key of the value to get or set. This must be a valid key that is not reserved for internal properties.</param>
        /// <returns>The object value associated with the specified key in the AdditionalProperties dictionary.</returns>
        /// <exception cref="System.ArgumentNullException">
        /// Thrown when <paramref name="key"/> is null or an empty string.
        /// </exception>
        /// <exception cref="System.ArgumentException">
        /// Thrown when the specified <paramref name="key"/> conflicts with an internal property of the object.
        /// </exception>
        /// <exception cref="KeyNotFoundException">
        /// Thrown when the specified <paramref name="key"/> does not exist in the AdditionalProperties dictionary.
        /// </exception>
        [IndexerName("AdditionalPropertiesIndexer")]
        public object this[string key]
        {
            get => additionalProperties.GetValue<object>(key);
            set => additionalProperties.SetValue(key, value, propertyName);
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="ApiMethodUsersGetPresence"/> class.
        /// </summary>
        public ApiMethodUsersGetPresence()
        {
            this.additionalProperties = new Dictionary<string, JToken>();
            this.propertyName = this.GetPropertyNames();
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="ApiMethodUsersGetPresence"/> class.
        /// </summary>
        /// <param name="ok">ok.</param>
        /// <param name="presence">presence.</param>
        /// <param name="autoAway">auto_away.</param>
        /// <param name="connectionCount">connection_count.</param>
        /// <param name="lastActivity">last_activity.</param>
        /// <param name="manualAway">manual_away.</param>
        /// <param name="online">online.</param>
        public ApiMethodUsersGetPresence(
            string ok,
            string presence,
            bool? autoAway = null,
            int? connectionCount = null,
            int? lastActivity = null,
            bool? manualAway = null,
            bool? online = null)
        {
            this.additionalProperties = new Dictionary<string, JToken>();
            this.propertyName = this.GetPropertyNames();
            this.AutoAway = autoAway;
            this.ConnectionCount = connectionCount;
            this.LastActivity = lastActivity;
            this.ManualAway = manualAway;
            this.Ok = ok;
            this.Online = online;
            this.Presence = presence;
        }

        /// <summary>
        /// Gets or sets AutoAway.
        /// </summary>
        [JsonProperty("auto_away", NullValueHandling = NullValueHandling.Ignore)]
        public bool? AutoAway { get; set; }

        /// <summary>
        /// Gets or sets ConnectionCount.
        /// </summary>
        [JsonProperty("connection_count", NullValueHandling = NullValueHandling.Ignore)]
        public int? ConnectionCount { get; set; }

        /// <summary>
        /// Gets or sets LastActivity.
        /// </summary>
        [JsonProperty("last_activity", NullValueHandling = NullValueHandling.Ignore)]
        public int? LastActivity { get; set; }

        /// <summary>
        /// Gets or sets ManualAway.
        /// </summary>
        [JsonProperty("manual_away", NullValueHandling = NullValueHandling.Ignore)]
        public bool? ManualAway { get; set; }

        /// <summary>
        /// Gets or sets Ok.
        /// </summary>
        [JsonProperty("ok")]
        public string Ok { get; set; }

        /// <summary>
        /// Gets or sets Online.
        /// </summary>
        [JsonProperty("online", NullValueHandling = NullValueHandling.Ignore)]
        public bool? Online { get; set; }

        /// <summary>
        /// Gets or sets Presence.
        /// </summary>
        [JsonProperty("presence")]
        public string Presence { get; set; }

        /// <inheritdoc/>
        public override string ToString()
        {
            var toStringOutput = new List<string>();
            this.ToString(toStringOutput);
            return $"ApiMethodUsersGetPresence : ({string.Join(", ", toStringOutput)})";
        }

        /// <inheritdoc/>
        public override bool Equals(object obj)
        {
            if (obj is null) return false;
            if (ReferenceEquals(this, obj)) return true;

            return obj is ApiMethodUsersGetPresence other &&
                (this.AutoAway == null && other.AutoAway == null ||
                 this.AutoAway?.Equals(other.AutoAway) == true) &&
                (this.ConnectionCount == null && other.ConnectionCount == null ||
                 this.ConnectionCount?.Equals(other.ConnectionCount) == true) &&
                (this.LastActivity == null && other.LastActivity == null ||
                 this.LastActivity?.Equals(other.LastActivity) == true) &&
                (this.ManualAway == null && other.ManualAway == null ||
                 this.ManualAway?.Equals(other.ManualAway) == true) &&
                (this.Ok == null && other.Ok == null ||
                 this.Ok?.Equals(other.Ok) == true) &&
                (this.Online == null && other.Online == null ||
                 this.Online?.Equals(other.Online) == true) &&
                (this.Presence == null && other.Presence == null ||
                 this.Presence?.Equals(other.Presence) == true) &&
                (this.additionalProperties == null && other.additionalProperties == null ||
                 this.additionalProperties?.Count == other.additionalProperties?.Count &&
                 this.additionalProperties?.All(kv =>
                     other.additionalProperties.TryGetValue(kv.Key, out var value) &&
                     JToken.DeepEquals(kv.Value, value)) == true);
        }

        /// <summary>
        /// ToString overload.
        /// </summary>
        /// <param name="toStringOutput">List of strings.</param>
        protected void ToString(List<string> toStringOutput)
        {
            toStringOutput.Add($"AutoAway = {(this.AutoAway == null ? "null" : this.AutoAway.ToString())}");
            toStringOutput.Add($"ConnectionCount = {(this.ConnectionCount == null ? "null" : this.ConnectionCount.ToString())}");
            toStringOutput.Add($"LastActivity = {(this.LastActivity == null ? "null" : this.LastActivity.ToString())}");
            toStringOutput.Add($"ManualAway = {(this.ManualAway == null ? "null" : this.ManualAway.ToString())}");
            toStringOutput.Add($"Ok = {this.Ok ?? "null"}");
            toStringOutput.Add($"Online = {(this.Online == null ? "null" : this.Online.ToString())}");
            toStringOutput.Add($"Presence = {this.Presence ?? "null"}");

            additionalProperties?
                .Select(kvp => $"[{kvp.Key}] = {kvp.Value.ToString(Formatting.None)}")
                .ToList()
                .ForEach(toStringOutput.Add);
        }
    }
}