// <copyright file="Attachment.cs" company="APIMatic">
// SlackWebApi.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using SlackWebApi.Standard.Utilities;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;

namespace SlackWebApi.Standard.Models
{
    /// <summary>
    /// Attachment.
    /// </summary>
    public class Attachment
    {
        [JsonExtensionData]
        private readonly IDictionary<string, JToken> additionalProperties;

        private readonly IEnumerable<string> propertyName;

        /// <summary>
        /// Get or set the value associated with the specified key in the AdditionalProperties dictionary.
        /// </summary>
        /// <param name="key">The key of the value to get or set. This must be a valid key that is not reserved for internal properties.</param>
        /// <returns>The object value associated with the specified key in the AdditionalProperties dictionary.</returns>
        /// <exception cref="System.ArgumentNullException">
        /// Thrown when <paramref name="key"/> is null or an empty string.
        /// </exception>
        /// <exception cref="System.ArgumentException">
        /// Thrown when the specified <paramref name="key"/> conflicts with an internal property of the object.
        /// </exception>
        /// <exception cref="KeyNotFoundException">
        /// Thrown when the specified <paramref name="key"/> does not exist in the AdditionalProperties dictionary.
        /// </exception>
        [IndexerName("AdditionalPropertiesIndexer")]
        public object this[string key]
        {
            get => additionalProperties.GetValue<object>(key);
            set => additionalProperties.SetValue(key, value, propertyName);
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="Attachment"/> class.
        /// </summary>
        public Attachment()
        {
            this.additionalProperties = new Dictionary<string, JToken>();
            this.propertyName = this.GetPropertyNames();
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="Attachment"/> class.
        /// </summary>
        /// <param name="id">id.</param>
        /// <param name="fallback">fallback.</param>
        /// <param name="imageBytes">image_bytes.</param>
        /// <param name="imageHeight">image_height.</param>
        /// <param name="imageUrl">image_url.</param>
        /// <param name="imageWidth">image_width.</param>
        public Attachment(
            int id,
            string fallback = null,
            int? imageBytes = null,
            int? imageHeight = null,
            string imageUrl = null,
            int? imageWidth = null)
        {
            this.additionalProperties = new Dictionary<string, JToken>();
            this.propertyName = this.GetPropertyNames();
            this.Fallback = fallback;
            this.Id = id;
            this.ImageBytes = imageBytes;
            this.ImageHeight = imageHeight;
            this.ImageUrl = imageUrl;
            this.ImageWidth = imageWidth;
        }

        /// <summary>
        /// Gets or sets Fallback.
        /// </summary>
        [JsonProperty("fallback", NullValueHandling = NullValueHandling.Ignore)]
        public string Fallback { get; set; }

        /// <summary>
        /// Gets or sets Id.
        /// </summary>
        [JsonProperty("id")]
        public int Id { get; set; }

        /// <summary>
        /// Gets or sets ImageBytes.
        /// </summary>
        [JsonProperty("image_bytes", NullValueHandling = NullValueHandling.Ignore)]
        public int? ImageBytes { get; set; }

        /// <summary>
        /// Gets or sets ImageHeight.
        /// </summary>
        [JsonProperty("image_height", NullValueHandling = NullValueHandling.Ignore)]
        public int? ImageHeight { get; set; }

        /// <summary>
        /// Gets or sets ImageUrl.
        /// </summary>
        [JsonProperty("image_url", NullValueHandling = NullValueHandling.Ignore)]
        public string ImageUrl { get; set; }

        /// <summary>
        /// Gets or sets ImageWidth.
        /// </summary>
        [JsonProperty("image_width", NullValueHandling = NullValueHandling.Ignore)]
        public int? ImageWidth { get; set; }

        /// <inheritdoc/>
        public override string ToString()
        {
            var toStringOutput = new List<string>();
            this.ToString(toStringOutput);
            return $"Attachment : ({string.Join(", ", toStringOutput)})";
        }

        /// <inheritdoc/>
        public override bool Equals(object obj)
        {
            if (obj is null) return false;
            if (ReferenceEquals(this, obj)) return true;

            return obj is Attachment other &&
                (this.Fallback == null && other.Fallback == null ||
                 this.Fallback?.Equals(other.Fallback) == true) &&
                (this.Id.Equals(other.Id)) &&
                (this.ImageBytes == null && other.ImageBytes == null ||
                 this.ImageBytes?.Equals(other.ImageBytes) == true) &&
                (this.ImageHeight == null && other.ImageHeight == null ||
                 this.ImageHeight?.Equals(other.ImageHeight) == true) &&
                (this.ImageUrl == null && other.ImageUrl == null ||
                 this.ImageUrl?.Equals(other.ImageUrl) == true) &&
                (this.ImageWidth == null && other.ImageWidth == null ||
                 this.ImageWidth?.Equals(other.ImageWidth) == true) &&
                (this.additionalProperties == null && other.additionalProperties == null ||
                 this.additionalProperties?.Count == other.additionalProperties?.Count &&
                 this.additionalProperties?.All(kv =>
                     other.additionalProperties.TryGetValue(kv.Key, out var value) &&
                     JToken.DeepEquals(kv.Value, value)) == true);
        }

        /// <summary>
        /// ToString overload.
        /// </summary>
        /// <param name="toStringOutput">List of strings.</param>
        protected void ToString(List<string> toStringOutput)
        {
            toStringOutput.Add($"Fallback = {this.Fallback ?? "null"}");
            toStringOutput.Add($"Id = {this.Id}");
            toStringOutput.Add($"ImageBytes = {(this.ImageBytes == null ? "null" : this.ImageBytes.ToString())}");
            toStringOutput.Add($"ImageHeight = {(this.ImageHeight == null ? "null" : this.ImageHeight.ToString())}");
            toStringOutput.Add($"ImageUrl = {this.ImageUrl ?? "null"}");
            toStringOutput.Add($"ImageWidth = {(this.ImageWidth == null ? "null" : this.ImageWidth.ToString())}");

            additionalProperties?
                .Select(kvp => $"[{kvp.Key}] = {kvp.Value.ToString(Formatting.None)}")
                .ToList()
                .ForEach(toStringOutput.Add);
        }
    }
}