// <copyright file="AuthTestSuccessSchema.cs" company="APIMatic">
// SlackWebApi.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using SlackWebApi.Standard.Utilities;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;

namespace SlackWebApi.Standard.Models
{
    /// <summary>
    /// AuthTestSuccessSchema.
    /// </summary>
    public class AuthTestSuccessSchema
    {
        [JsonExtensionData]
        private readonly IDictionary<string, JToken> additionalProperties;

        private readonly IEnumerable<string> propertyName;

        /// <summary>
        /// Get or set the value associated with the specified key in the AdditionalProperties dictionary.
        /// </summary>
        /// <param name="key">The key of the value to get or set. This must be a valid key that is not reserved for internal properties.</param>
        /// <returns>The object value associated with the specified key in the AdditionalProperties dictionary.</returns>
        /// <exception cref="System.ArgumentNullException">
        /// Thrown when <paramref name="key"/> is null or an empty string.
        /// </exception>
        /// <exception cref="System.ArgumentException">
        /// Thrown when the specified <paramref name="key"/> conflicts with an internal property of the object.
        /// </exception>
        /// <exception cref="KeyNotFoundException">
        /// Thrown when the specified <paramref name="key"/> does not exist in the AdditionalProperties dictionary.
        /// </exception>
        [IndexerName("AdditionalPropertiesIndexer")]
        public object this[string key]
        {
            get => additionalProperties.GetValue<object>(key);
            set => additionalProperties.SetValue(key, value, propertyName);
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="AuthTestSuccessSchema"/> class.
        /// </summary>
        public AuthTestSuccessSchema()
        {
            this.additionalProperties = new Dictionary<string, JToken>();
            this.propertyName = this.GetPropertyNames();
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="AuthTestSuccessSchema"/> class.
        /// </summary>
        /// <param name="ok">ok.</param>
        /// <param name="team">team.</param>
        /// <param name="teamId">team_id.</param>
        /// <param name="url">url.</param>
        /// <param name="user">user.</param>
        /// <param name="userId">user_id.</param>
        /// <param name="botId">bot_id.</param>
        /// <param name="isEnterpriseInstall">is_enterprise_install.</param>
        public AuthTestSuccessSchema(
            string ok,
            string team,
            string teamId,
            string url,
            string user,
            string userId,
            string botId = null,
            bool? isEnterpriseInstall = null)
        {
            this.additionalProperties = new Dictionary<string, JToken>();
            this.propertyName = this.GetPropertyNames();
            this.BotId = botId;
            this.IsEnterpriseInstall = isEnterpriseInstall;
            this.Ok = ok;
            this.Team = team;
            this.TeamId = teamId;
            this.Url = url;
            this.User = user;
            this.UserId = userId;
        }

        /// <summary>
        /// Gets or sets BotId.
        /// </summary>
        [JsonProperty("bot_id", NullValueHandling = NullValueHandling.Ignore)]
        public string BotId { get; set; }

        /// <summary>
        /// Gets or sets IsEnterpriseInstall.
        /// </summary>
        [JsonProperty("is_enterprise_install", NullValueHandling = NullValueHandling.Ignore)]
        public bool? IsEnterpriseInstall { get; set; }

        /// <summary>
        /// Gets or sets Ok.
        /// </summary>
        [JsonProperty("ok")]
        public string Ok { get; set; }

        /// <summary>
        /// Gets or sets Team.
        /// </summary>
        [JsonProperty("team")]
        public string Team { get; set; }

        /// <summary>
        /// Gets or sets TeamId.
        /// </summary>
        [JsonProperty("team_id")]
        public string TeamId { get; set; }

        /// <summary>
        /// Gets or sets Url.
        /// </summary>
        [JsonProperty("url")]
        public string Url { get; set; }

        /// <summary>
        /// Gets or sets User.
        /// </summary>
        [JsonProperty("user")]
        public string User { get; set; }

        /// <summary>
        /// Gets or sets UserId.
        /// </summary>
        [JsonProperty("user_id")]
        public string UserId { get; set; }

        /// <inheritdoc/>
        public override string ToString()
        {
            var toStringOutput = new List<string>();
            this.ToString(toStringOutput);
            return $"AuthTestSuccessSchema : ({string.Join(", ", toStringOutput)})";
        }

        /// <inheritdoc/>
        public override bool Equals(object obj)
        {
            if (obj is null) return false;
            if (ReferenceEquals(this, obj)) return true;

            return obj is AuthTestSuccessSchema other &&
                (this.BotId == null && other.BotId == null ||
                 this.BotId?.Equals(other.BotId) == true) &&
                (this.IsEnterpriseInstall == null && other.IsEnterpriseInstall == null ||
                 this.IsEnterpriseInstall?.Equals(other.IsEnterpriseInstall) == true) &&
                (this.Ok == null && other.Ok == null ||
                 this.Ok?.Equals(other.Ok) == true) &&
                (this.Team == null && other.Team == null ||
                 this.Team?.Equals(other.Team) == true) &&
                (this.TeamId == null && other.TeamId == null ||
                 this.TeamId?.Equals(other.TeamId) == true) &&
                (this.Url == null && other.Url == null ||
                 this.Url?.Equals(other.Url) == true) &&
                (this.User == null && other.User == null ||
                 this.User?.Equals(other.User) == true) &&
                (this.UserId == null && other.UserId == null ||
                 this.UserId?.Equals(other.UserId) == true) &&
                (this.additionalProperties == null && other.additionalProperties == null ||
                 this.additionalProperties?.Count == other.additionalProperties?.Count &&
                 this.additionalProperties?.All(kv =>
                     other.additionalProperties.TryGetValue(kv.Key, out var value) &&
                     JToken.DeepEquals(kv.Value, value)) == true);
        }

        /// <summary>
        /// ToString overload.
        /// </summary>
        /// <param name="toStringOutput">List of strings.</param>
        protected void ToString(List<string> toStringOutput)
        {
            toStringOutput.Add($"BotId = {this.BotId ?? "null"}");
            toStringOutput.Add($"IsEnterpriseInstall = {(this.IsEnterpriseInstall == null ? "null" : this.IsEnterpriseInstall.ToString())}");
            toStringOutput.Add($"Ok = {this.Ok ?? "null"}");
            toStringOutput.Add($"Team = {this.Team ?? "null"}");
            toStringOutput.Add($"TeamId = {this.TeamId ?? "null"}");
            toStringOutput.Add($"Url = {this.Url ?? "null"}");
            toStringOutput.Add($"User = {this.User ?? "null"}");
            toStringOutput.Add($"UserId = {this.UserId ?? "null"}");

            additionalProperties?
                .Select(kvp => $"[{kvp.Key}] = {kvp.Value.ToString(Formatting.None)}")
                .ToList()
                .ForEach(toStringOutput.Add);
        }
    }
}