// <copyright file="ChatScheduleMessageSuccessSchema.cs" company="APIMatic">
// SlackWebApi.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using SlackWebApi.Standard.Utilities;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;

namespace SlackWebApi.Standard.Models
{
    /// <summary>
    /// ChatScheduleMessageSuccessSchema.
    /// </summary>
    public class ChatScheduleMessageSuccessSchema
    {
        [JsonExtensionData]
        private readonly IDictionary<string, JToken> additionalProperties;

        private readonly IEnumerable<string> propertyName;

        /// <summary>
        /// Get or set the value associated with the specified key in the AdditionalProperties dictionary.
        /// </summary>
        /// <param name="key">The key of the value to get or set. This must be a valid key that is not reserved for internal properties.</param>
        /// <returns>The object value associated with the specified key in the AdditionalProperties dictionary.</returns>
        /// <exception cref="System.ArgumentNullException">
        /// Thrown when <paramref name="key"/> is null or an empty string.
        /// </exception>
        /// <exception cref="System.ArgumentException">
        /// Thrown when the specified <paramref name="key"/> conflicts with an internal property of the object.
        /// </exception>
        /// <exception cref="KeyNotFoundException">
        /// Thrown when the specified <paramref name="key"/> does not exist in the AdditionalProperties dictionary.
        /// </exception>
        [IndexerName("AdditionalPropertiesIndexer")]
        public object this[string key]
        {
            get => additionalProperties.GetValue<object>(key);
            set => additionalProperties.SetValue(key, value, propertyName);
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="ChatScheduleMessageSuccessSchema"/> class.
        /// </summary>
        public ChatScheduleMessageSuccessSchema()
        {
            this.additionalProperties = new Dictionary<string, JToken>();
            this.propertyName = this.GetPropertyNames();
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="ChatScheduleMessageSuccessSchema"/> class.
        /// </summary>
        /// <param name="channel">channel.</param>
        /// <param name="message">message.</param>
        /// <param name="ok">ok.</param>
        /// <param name="postAt">post_at.</param>
        /// <param name="scheduledMessageId">scheduled_message_id.</param>
        public ChatScheduleMessageSuccessSchema(
            string channel,
            Models.Message message,
            string ok,
            int postAt,
            string scheduledMessageId)
        {
            this.additionalProperties = new Dictionary<string, JToken>();
            this.propertyName = this.GetPropertyNames();
            this.Channel = channel;
            this.Message = message;
            this.Ok = ok;
            this.PostAt = postAt;
            this.ScheduledMessageId = scheduledMessageId;
        }

        /// <summary>
        /// Gets or sets Channel.
        /// </summary>
        [JsonProperty("channel")]
        public string Channel { get; set; }

        /// <summary>
        /// Gets or sets Message.
        /// </summary>
        [JsonProperty("message")]
        public Models.Message Message { get; set; }

        /// <summary>
        /// Gets or sets Ok.
        /// </summary>
        [JsonProperty("ok")]
        public string Ok { get; set; }

        /// <summary>
        /// Gets or sets PostAt.
        /// </summary>
        [JsonProperty("post_at")]
        public int PostAt { get; set; }

        /// <summary>
        /// Gets or sets ScheduledMessageId.
        /// </summary>
        [JsonProperty("scheduled_message_id")]
        public string ScheduledMessageId { get; set; }

        /// <inheritdoc/>
        public override string ToString()
        {
            var toStringOutput = new List<string>();
            this.ToString(toStringOutput);
            return $"ChatScheduleMessageSuccessSchema : ({string.Join(", ", toStringOutput)})";
        }

        /// <inheritdoc/>
        public override bool Equals(object obj)
        {
            if (obj is null) return false;
            if (ReferenceEquals(this, obj)) return true;

            return obj is ChatScheduleMessageSuccessSchema other &&
                (this.Channel == null && other.Channel == null ||
                 this.Channel?.Equals(other.Channel) == true) &&
                (this.Message == null && other.Message == null ||
                 this.Message?.Equals(other.Message) == true) &&
                (this.Ok == null && other.Ok == null ||
                 this.Ok?.Equals(other.Ok) == true) &&
                (this.PostAt.Equals(other.PostAt)) &&
                (this.ScheduledMessageId == null && other.ScheduledMessageId == null ||
                 this.ScheduledMessageId?.Equals(other.ScheduledMessageId) == true) &&
                (this.additionalProperties == null && other.additionalProperties == null ||
                 this.additionalProperties?.Count == other.additionalProperties?.Count &&
                 this.additionalProperties?.All(kv =>
                     other.additionalProperties.TryGetValue(kv.Key, out var value) &&
                     JToken.DeepEquals(kv.Value, value)) == true);
        }

        /// <summary>
        /// ToString overload.
        /// </summary>
        /// <param name="toStringOutput">List of strings.</param>
        protected void ToString(List<string> toStringOutput)
        {
            toStringOutput.Add($"Channel = {this.Channel ?? "null"}");
            toStringOutput.Add($"Message = {(this.Message == null ? "null" : this.Message.ToString())}");
            toStringOutput.Add($"Ok = {this.Ok ?? "null"}");
            toStringOutput.Add($"PostAt = {this.PostAt}");
            toStringOutput.Add($"ScheduledMessageId = {this.ScheduledMessageId ?? "null"}");

            additionalProperties?
                .Select(kvp => $"[{kvp.Key}] = {kvp.Value.ToString(Formatting.None)}")
                .ToList()
                .ForEach(toStringOutput.Add);
        }
    }
}