// <copyright file="Error1.cs" company="APIMatic">
// SlackWebApi.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using APIMatic.Core.Utilities.Converters;
using Newtonsoft.Json;
using System.Runtime.Serialization;

namespace SlackWebApi.Standard.Models
{
    /// <summary>
    /// Error1.
    /// </summary>

    [JsonConverter(typeof(StringEnumConverter))]
    public enum Error1
    {
        /// <summary>
        /// FeatureNotEnabled.
        /// </summary>
        [EnumMember(Value = "feature_not_enabled")]
        FeatureNotEnabled,

        /// <summary>
        /// RestrictedAction.
        /// </summary>
        [EnumMember(Value = "restricted_action")]
        RestrictedAction,

        /// <summary>
        /// NameTaken.
        /// </summary>
        [EnumMember(Value = "name_taken")]
        NameTaken,

        /// <summary>
        /// ChannelNotFound.
        /// </summary>
        [EnumMember(Value = "channel_not_found")]
        ChannelNotFound,

        /// <summary>
        /// ChannelTypeNotSupported.
        /// </summary>
        [EnumMember(Value = "channel_type_not_supported")]
        ChannelTypeNotSupported,

        /// <summary>
        /// DefaultOrgWideChannel.
        /// </summary>
        [EnumMember(Value = "default_org_wide_channel")]
        DefaultOrgWideChannel,

        /// <summary>
        /// MethodNotSupportedForChannelType.
        /// </summary>
        [EnumMember(Value = "method_not_supported_for_channel_type")]
        MethodNotSupportedForChannelType,

        /// <summary>
        /// CouldNotConvertChannel.
        /// </summary>
        [EnumMember(Value = "could_not_convert_channel")]
        CouldNotConvertChannel,

        /// <summary>
        /// ExternalChannelMigrating.
        /// </summary>
        [EnumMember(Value = "external_channel_migrating")]
        ExternalChannelMigrating
    }
}