// <copyright file="Error25.cs" company="APIMatic">
// SlackWebApi.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using APIMatic.Core.Utilities.Converters;
using Newtonsoft.Json;
using System.Runtime.Serialization;

namespace SlackWebApi.Standard.Models
{
    /// <summary>
    /// Error25.
    /// </summary>

    [JsonConverter(typeof(StringEnumConverter))]
    public enum Error25
    {
        /// <summary>
        /// ChannelNotFound.
        /// </summary>
        [EnumMember(Value = "channel_not_found")]
        ChannelNotFound,

        /// <summary>
        /// NotInChannel.
        /// </summary>
        [EnumMember(Value = "not_in_channel")]
        NotInChannel,

        /// <summary>
        /// IsArchived.
        /// </summary>
        [EnumMember(Value = "is_archived")]
        IsArchived,

        /// <summary>
        /// MsgTooLong.
        /// </summary>
        [EnumMember(Value = "msg_too_long")]
        MsgTooLong,

        /// <summary>
        /// NoText.
        /// </summary>
        [EnumMember(Value = "no_text")]
        NoText,

        /// <summary>
        /// TooManyAttachments.
        /// </summary>
        [EnumMember(Value = "too_many_attachments")]
        TooManyAttachments,

        /// <summary>
        /// RateLimited.
        /// </summary>
        [EnumMember(Value = "rate_limited")]
        RateLimited,

        /// <summary>
        /// NotAuthed.
        /// </summary>
        [EnumMember(Value = "not_authed")]
        NotAuthed,

        /// <summary>
        /// InvalidAuth.
        /// </summary>
        [EnumMember(Value = "invalid_auth")]
        InvalidAuth,

        /// <summary>
        /// AccountInactive.
        /// </summary>
        [EnumMember(Value = "account_inactive")]
        AccountInactive,

        /// <summary>
        /// InvalidArgName.
        /// </summary>
        [EnumMember(Value = "invalid_arg_name")]
        InvalidArgName,

        /// <summary>
        /// InvalidArrayArg.
        /// </summary>
        [EnumMember(Value = "invalid_array_arg")]
        InvalidArrayArg,

        /// <summary>
        /// InvalidCharset.
        /// </summary>
        [EnumMember(Value = "invalid_charset")]
        InvalidCharset,

        /// <summary>
        /// InvalidFormData.
        /// </summary>
        [EnumMember(Value = "invalid_form_data")]
        InvalidFormData,

        /// <summary>
        /// InvalidPostType.
        /// </summary>
        [EnumMember(Value = "invalid_post_type")]
        InvalidPostType,

        /// <summary>
        /// MissingPostType.
        /// </summary>
        [EnumMember(Value = "missing_post_type")]
        MissingPostType
    }
}