// <copyright file="Error8.cs" company="APIMatic">
// SlackWebApi.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using APIMatic.Core.Utilities.Converters;
using Newtonsoft.Json;
using System.Runtime.Serialization;

namespace SlackWebApi.Standard.Models
{
    /// <summary>
    /// Error8.
    /// </summary>

    [JsonConverter(typeof(StringEnumConverter))]
    public enum Error8
    {
        /// <summary>
        /// FeatureNotEnabled.
        /// </summary>
        [EnumMember(Value = "feature_not_enabled")]
        FeatureNotEnabled,

        /// <summary>
        /// ChannelNotFound.
        /// </summary>
        [EnumMember(Value = "channel_not_found")]
        ChannelNotFound,

        /// <summary>
        /// ChannelTypeNotSupported.
        /// </summary>
        [EnumMember(Value = "channel_type_not_supported")]
        ChannelTypeNotSupported,

        /// <summary>
        /// RestrictedAction.
        /// </summary>
        [EnumMember(Value = "restricted_action")]
        RestrictedAction,

        /// <summary>
        /// CouldNotRenameChannel.
        /// </summary>
        [EnumMember(Value = "could_not_rename_channel")]
        CouldNotRenameChannel,

        /// <summary>
        /// DefaultOrgWideChannel.
        /// </summary>
        [EnumMember(Value = "default_org_wide_channel")]
        DefaultOrgWideChannel,

        /// <summary>
        /// NameTaken.
        /// </summary>
        [EnumMember(Value = "name_taken")]
        NameTaken
    }
}