// <copyright file="Error32.cs" company="APIMatic">
// SlackWebApi.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using APIMatic.Core.Utilities.Converters;
using Newtonsoft.Json;
using System.Runtime.Serialization;

namespace SlackWebApi.Standard.Models
{
    /// <summary>
    /// Error32.
    /// </summary>

    [JsonConverter(typeof(StringEnumConverter))]
    public enum Error32
    {
        /// <summary>
        /// MethodNotSupportedForChannelType.
        /// </summary>
        [EnumMember(Value = "method_not_supported_for_channel_type")]
        MethodNotSupportedForChannelType,

        /// <summary>
        /// MissingScope.
        /// </summary>
        [EnumMember(Value = "missing_scope")]
        MissingScope,

        /// <summary>
        /// NameTaken.
        /// </summary>
        [EnumMember(Value = "name_taken")]
        NameTaken,

        /// <summary>
        /// RestrictedAction.
        /// </summary>
        [EnumMember(Value = "restricted_action")]
        RestrictedAction,

        /// <summary>
        /// NoChannel.
        /// </summary>
        [EnumMember(Value = "no_channel")]
        NoChannel,

        /// <summary>
        /// InvalidNameRequired.
        /// </summary>
        [EnumMember(Value = "invalid_name_required")]
        InvalidNameRequired,

        /// <summary>
        /// InvalidNamePunctuation.
        /// </summary>
        [EnumMember(Value = "invalid_name_punctuation")]
        InvalidNamePunctuation,

        /// <summary>
        /// InvalidNameMaxlength.
        /// </summary>
        [EnumMember(Value = "invalid_name_maxlength")]
        InvalidNameMaxlength,

        /// <summary>
        /// InvalidNameSpecials.
        /// </summary>
        [EnumMember(Value = "invalid_name_specials")]
        InvalidNameSpecials,

        /// <summary>
        /// InvalidName.
        /// </summary>
        [EnumMember(Value = "invalid_name")]
        InvalidName,

        /// <summary>
        /// NotAuthed.
        /// </summary>
        [EnumMember(Value = "not_authed")]
        NotAuthed,

        /// <summary>
        /// InvalidAuth.
        /// </summary>
        [EnumMember(Value = "invalid_auth")]
        InvalidAuth,

        /// <summary>
        /// AccountInactive.
        /// </summary>
        [EnumMember(Value = "account_inactive")]
        AccountInactive,

        /// <summary>
        /// UserIsBot.
        /// </summary>
        [EnumMember(Value = "user_is_bot")]
        UserIsBot,

        /// <summary>
        /// UserIsRestricted.
        /// </summary>
        [EnumMember(Value = "user_is_restricted")]
        UserIsRestricted,

        /// <summary>
        /// InvalidArgName.
        /// </summary>
        [EnumMember(Value = "invalid_arg_name")]
        InvalidArgName,

        /// <summary>
        /// InvalidArrayArg.
        /// </summary>
        [EnumMember(Value = "invalid_array_arg")]
        InvalidArrayArg,

        /// <summary>
        /// InvalidCharset.
        /// </summary>
        [EnumMember(Value = "invalid_charset")]
        InvalidCharset,

        /// <summary>
        /// InvalidFormData.
        /// </summary>
        [EnumMember(Value = "invalid_form_data")]
        InvalidFormData,

        /// <summary>
        /// InvalidPostType.
        /// </summary>
        [EnumMember(Value = "invalid_post_type")]
        InvalidPostType,

        /// <summary>
        /// MissingPostType.
        /// </summary>
        [EnumMember(Value = "missing_post_type")]
        MissingPostType,

        /// <summary>
        /// TeamAddedToOrg.
        /// </summary>
        [EnumMember(Value = "team_added_to_org")]
        TeamAddedToOrg,

        /// <summary>
        /// InvalidJson.
        /// </summary>
        [EnumMember(Value = "invalid_json")]
        InvalidJson,

        /// <summary>
        /// JsonNotObject.
        /// </summary>
        [EnumMember(Value = "json_not_object")]
        JsonNotObject,

        /// <summary>
        /// RequestTimeout.
        /// </summary>
        [EnumMember(Value = "request_timeout")]
        RequestTimeout,

        /// <summary>
        /// UpgradeRequired.
        /// </summary>
        [EnumMember(Value = "upgrade_required")]
        UpgradeRequired
    }
}