// <copyright file="Error41.cs" company="APIMatic">
// SlackWebApi.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using APIMatic.Core.Utilities.Converters;
using Newtonsoft.Json;
using System.Runtime.Serialization;

namespace SlackWebApi.Standard.Models
{
    /// <summary>
    /// Error41.
    /// </summary>

    [JsonConverter(typeof(StringEnumConverter))]
    public enum Error41
    {
        /// <summary>
        /// MethodNotSupportedForChannelType.
        /// </summary>
        [EnumMember(Value = "method_not_supported_for_channel_type")]
        MethodNotSupportedForChannelType,

        /// <summary>
        /// MissingScope.
        /// </summary>
        [EnumMember(Value = "missing_scope")]
        MissingScope,

        /// <summary>
        /// ChannelNotFound.
        /// </summary>
        [EnumMember(Value = "channel_not_found")]
        ChannelNotFound,

        /// <summary>
        /// InvalidTimestamp.
        /// </summary>
        [EnumMember(Value = "invalid_timestamp")]
        InvalidTimestamp,

        /// <summary>
        /// NotInChannel.
        /// </summary>
        [EnumMember(Value = "not_in_channel")]
        NotInChannel,

        /// <summary>
        /// NotAuthed.
        /// </summary>
        [EnumMember(Value = "not_authed")]
        NotAuthed,

        /// <summary>
        /// InvalidAuth.
        /// </summary>
        [EnumMember(Value = "invalid_auth")]
        InvalidAuth,

        /// <summary>
        /// AccountInactive.
        /// </summary>
        [EnumMember(Value = "account_inactive")]
        AccountInactive,

        /// <summary>
        /// InvalidArgName.
        /// </summary>
        [EnumMember(Value = "invalid_arg_name")]
        InvalidArgName,

        /// <summary>
        /// InvalidArrayArg.
        /// </summary>
        [EnumMember(Value = "invalid_array_arg")]
        InvalidArrayArg,

        /// <summary>
        /// InvalidCharset.
        /// </summary>
        [EnumMember(Value = "invalid_charset")]
        InvalidCharset,

        /// <summary>
        /// InvalidFormData.
        /// </summary>
        [EnumMember(Value = "invalid_form_data")]
        InvalidFormData,

        /// <summary>
        /// InvalidPostType.
        /// </summary>
        [EnumMember(Value = "invalid_post_type")]
        InvalidPostType,

        /// <summary>
        /// MissingPostType.
        /// </summary>
        [EnumMember(Value = "missing_post_type")]
        MissingPostType,

        /// <summary>
        /// InvalidJson.
        /// </summary>
        [EnumMember(Value = "invalid_json")]
        InvalidJson,

        /// <summary>
        /// JsonNotObject.
        /// </summary>
        [EnumMember(Value = "json_not_object")]
        JsonNotObject,

        /// <summary>
        /// RequestTimeout.
        /// </summary>
        [EnumMember(Value = "request_timeout")]
        RequestTimeout,

        /// <summary>
        /// UpgradeRequired.
        /// </summary>
        [EnumMember(Value = "upgrade_required")]
        UpgradeRequired,

        /// <summary>
        /// NotAllowedTokenType.
        /// </summary>
        [EnumMember(Value = "not_allowed_token_type")]
        NotAllowedTokenType
    }
}