// <copyright file="FileObject.cs" company="APIMatic">
// SlackWebApi.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using SlackWebApi.Standard.Utilities;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;

namespace SlackWebApi.Standard.Models
{
    /// <summary>
    /// FileObject.
    /// </summary>
    public class FileObject
    {
        [JsonExtensionData]
        private readonly IDictionary<string, JToken> additionalProperties;

        private readonly IEnumerable<string> propertyName;

        /// <summary>
        /// Get or set the value associated with the specified key in the AdditionalProperties dictionary.
        /// </summary>
        /// <param name="key">The key of the value to get or set. This must be a valid key that is not reserved for internal properties.</param>
        /// <returns>The object value associated with the specified key in the AdditionalProperties dictionary.</returns>
        /// <exception cref="System.ArgumentNullException">
        /// Thrown when <paramref name="key"/> is null or an empty string.
        /// </exception>
        /// <exception cref="System.ArgumentException">
        /// Thrown when the specified <paramref name="key"/> conflicts with an internal property of the object.
        /// </exception>
        /// <exception cref="KeyNotFoundException">
        /// Thrown when the specified <paramref name="key"/> does not exist in the AdditionalProperties dictionary.
        /// </exception>
        [IndexerName("AdditionalPropertiesIndexer")]
        public object this[string key]
        {
            get => additionalProperties.GetValue<object>(key);
            set => additionalProperties.SetValue(key, value, propertyName);
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="FileObject"/> class.
        /// </summary>
        public FileObject()
        {
            this.additionalProperties = new Dictionary<string, JToken>();
            this.propertyName = this.GetPropertyNames();
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="FileObject"/> class.
        /// </summary>
        /// <param name="channels">channels.</param>
        /// <param name="commentsCount">comments_count.</param>
        /// <param name="created">created.</param>
        /// <param name="dateDelete">date_delete.</param>
        /// <param name="displayAsBot">display_as_bot.</param>
        /// <param name="editable">editable.</param>
        /// <param name="editor">editor.</param>
        /// <param name="externalId">external_id.</param>
        /// <param name="externalType">external_type.</param>
        /// <param name="externalUrl">external_url.</param>
        /// <param name="filetype">filetype.</param>
        /// <param name="groups">groups.</param>
        /// <param name="hasRichPreview">has_rich_preview.</param>
        /// <param name="id">id.</param>
        /// <param name="imageExifRotation">image_exif_rotation.</param>
        /// <param name="ims">ims.</param>
        /// <param name="isExternal">is_external.</param>
        /// <param name="isPublic">is_public.</param>
        /// <param name="isStarred">is_starred.</param>
        /// <param name="isTombstoned">is_tombstoned.</param>
        /// <param name="lastEditor">last_editor.</param>
        /// <param name="mimetype">mimetype.</param>
        /// <param name="mode">mode.</param>
        /// <param name="name">name.</param>
        /// <param name="nonOwnerEditable">non_owner_editable.</param>
        /// <param name="numStars">num_stars.</param>
        /// <param name="originalH">original_h.</param>
        /// <param name="originalW">original_w.</param>
        /// <param name="permalink">permalink.</param>
        /// <param name="permalinkPublic">permalink_public.</param>
        /// <param name="pinnedInfo">pinned_info.</param>
        /// <param name="pinnedTo">pinned_to.</param>
        /// <param name="prettyType">pretty_type.</param>
        /// <param name="preview">preview.</param>
        /// <param name="publicUrlShared">public_url_shared.</param>
        /// <param name="reactions">reactions.</param>
        /// <param name="shares">shares.</param>
        /// <param name="size">size.</param>
        /// <param name="sourceTeam">source_team.</param>
        /// <param name="state">state.</param>
        /// <param name="thumb1024">thumb_1024.</param>
        /// <param name="thumb1024H">thumb_1024_h.</param>
        /// <param name="thumb1024W">thumb_1024_w.</param>
        /// <param name="thumb160">thumb_160.</param>
        /// <param name="thumb360">thumb_360.</param>
        /// <param name="thumb360H">thumb_360_h.</param>
        /// <param name="thumb360W">thumb_360_w.</param>
        /// <param name="thumb480">thumb_480.</param>
        /// <param name="thumb480H">thumb_480_h.</param>
        /// <param name="thumb480W">thumb_480_w.</param>
        /// <param name="thumb64">thumb_64.</param>
        /// <param name="thumb720">thumb_720.</param>
        /// <param name="thumb720H">thumb_720_h.</param>
        /// <param name="thumb720W">thumb_720_w.</param>
        /// <param name="thumb80">thumb_80.</param>
        /// <param name="thumb800">thumb_800.</param>
        /// <param name="thumb800H">thumb_800_h.</param>
        /// <param name="thumb800W">thumb_800_w.</param>
        /// <param name="thumb960">thumb_960.</param>
        /// <param name="thumb960H">thumb_960_h.</param>
        /// <param name="thumb960W">thumb_960_w.</param>
        /// <param name="thumbTiny">thumb_tiny.</param>
        /// <param name="timestamp">timestamp.</param>
        /// <param name="title">title.</param>
        /// <param name="updated">updated.</param>
        /// <param name="urlPrivate">url_private.</param>
        /// <param name="urlPrivateDownload">url_private_download.</param>
        /// <param name="user">user.</param>
        /// <param name="userTeam">user_team.</param>
        /// <param name="username">username.</param>
        public FileObject(
            List<string> channels = null,
            int? commentsCount = null,
            int? created = null,
            int? dateDelete = null,
            bool? displayAsBot = null,
            bool? editable = null,
            string editor = null,
            string externalId = null,
            string externalType = null,
            string externalUrl = null,
            string filetype = null,
            List<string> groups = null,
            bool? hasRichPreview = null,
            string id = null,
            int? imageExifRotation = null,
            List<string> ims = null,
            bool? isExternal = null,
            bool? isPublic = null,
            bool? isStarred = null,
            bool? isTombstoned = null,
            string lastEditor = null,
            string mimetype = null,
            string mode = null,
            string name = null,
            bool? nonOwnerEditable = null,
            int? numStars = null,
            int? originalH = null,
            int? originalW = null,
            string permalink = null,
            string permalinkPublic = null,
            object pinnedInfo = null,
            List<string> pinnedTo = null,
            string prettyType = null,
            string preview = null,
            bool? publicUrlShared = null,
            List<Models.ReactionObject> reactions = null,
            Models.Shares shares = null,
            int? size = null,
            string sourceTeam = null,
            string state = null,
            string thumb1024 = null,
            int? thumb1024H = null,
            int? thumb1024W = null,
            string thumb160 = null,
            string thumb360 = null,
            int? thumb360H = null,
            int? thumb360W = null,
            string thumb480 = null,
            int? thumb480H = null,
            int? thumb480W = null,
            string thumb64 = null,
            string thumb720 = null,
            int? thumb720H = null,
            int? thumb720W = null,
            string thumb80 = null,
            string thumb800 = null,
            int? thumb800H = null,
            int? thumb800W = null,
            string thumb960 = null,
            int? thumb960H = null,
            int? thumb960W = null,
            string thumbTiny = null,
            int? timestamp = null,
            string title = null,
            int? updated = null,
            string urlPrivate = null,
            string urlPrivateDownload = null,
            string user = null,
            string userTeam = null,
            string username = null)
        {
            this.additionalProperties = new Dictionary<string, JToken>();
            this.propertyName = this.GetPropertyNames();
            this.Channels = channels;
            this.CommentsCount = commentsCount;
            this.Created = created;
            this.DateDelete = dateDelete;
            this.DisplayAsBot = displayAsBot;
            this.Editable = editable;
            this.Editor = editor;
            this.ExternalId = externalId;
            this.ExternalType = externalType;
            this.ExternalUrl = externalUrl;
            this.Filetype = filetype;
            this.Groups = groups;
            this.HasRichPreview = hasRichPreview;
            this.Id = id;
            this.ImageExifRotation = imageExifRotation;
            this.Ims = ims;
            this.IsExternal = isExternal;
            this.IsPublic = isPublic;
            this.IsStarred = isStarred;
            this.IsTombstoned = isTombstoned;
            this.LastEditor = lastEditor;
            this.Mimetype = mimetype;
            this.Mode = mode;
            this.Name = name;
            this.NonOwnerEditable = nonOwnerEditable;
            this.NumStars = numStars;
            this.OriginalH = originalH;
            this.OriginalW = originalW;
            this.Permalink = permalink;
            this.PermalinkPublic = permalinkPublic;
            this.PinnedInfo = pinnedInfo;
            this.PinnedTo = pinnedTo;
            this.PrettyType = prettyType;
            this.Preview = preview;
            this.PublicUrlShared = publicUrlShared;
            this.Reactions = reactions;
            this.Shares = shares;
            this.Size = size;
            this.SourceTeam = sourceTeam;
            this.State = state;
            this.Thumb1024 = thumb1024;
            this.Thumb1024H = thumb1024H;
            this.Thumb1024W = thumb1024W;
            this.Thumb160 = thumb160;
            this.Thumb360 = thumb360;
            this.Thumb360H = thumb360H;
            this.Thumb360W = thumb360W;
            this.Thumb480 = thumb480;
            this.Thumb480H = thumb480H;
            this.Thumb480W = thumb480W;
            this.Thumb64 = thumb64;
            this.Thumb720 = thumb720;
            this.Thumb720H = thumb720H;
            this.Thumb720W = thumb720W;
            this.Thumb80 = thumb80;
            this.Thumb800 = thumb800;
            this.Thumb800H = thumb800H;
            this.Thumb800W = thumb800W;
            this.Thumb960 = thumb960;
            this.Thumb960H = thumb960H;
            this.Thumb960W = thumb960W;
            this.ThumbTiny = thumbTiny;
            this.Timestamp = timestamp;
            this.Title = title;
            this.Updated = updated;
            this.UrlPrivate = urlPrivate;
            this.UrlPrivateDownload = urlPrivateDownload;
            this.User = user;
            this.UserTeam = userTeam;
            this.Username = username;
        }

        /// <summary>
        /// Gets or sets Channels.
        /// </summary>
        [JsonProperty("channels", NullValueHandling = NullValueHandling.Ignore)]
        public List<string> Channels { get; set; }

        /// <summary>
        /// Gets or sets CommentsCount.
        /// </summary>
        [JsonProperty("comments_count", NullValueHandling = NullValueHandling.Ignore)]
        public int? CommentsCount { get; set; }

        /// <summary>
        /// Gets or sets Created.
        /// </summary>
        [JsonProperty("created", NullValueHandling = NullValueHandling.Ignore)]
        public int? Created { get; set; }

        /// <summary>
        /// Gets or sets DateDelete.
        /// </summary>
        [JsonProperty("date_delete", NullValueHandling = NullValueHandling.Ignore)]
        public int? DateDelete { get; set; }

        /// <summary>
        /// Gets or sets DisplayAsBot.
        /// </summary>
        [JsonProperty("display_as_bot", NullValueHandling = NullValueHandling.Ignore)]
        public bool? DisplayAsBot { get; set; }

        /// <summary>
        /// Gets or sets Editable.
        /// </summary>
        [JsonProperty("editable", NullValueHandling = NullValueHandling.Ignore)]
        public bool? Editable { get; set; }

        /// <summary>
        /// Gets or sets Editor.
        /// </summary>
        [JsonProperty("editor", NullValueHandling = NullValueHandling.Ignore)]
        public string Editor { get; set; }

        /// <summary>
        /// Gets or sets ExternalId.
        /// </summary>
        [JsonProperty("external_id", NullValueHandling = NullValueHandling.Ignore)]
        public string ExternalId { get; set; }

        /// <summary>
        /// Gets or sets ExternalType.
        /// </summary>
        [JsonProperty("external_type", NullValueHandling = NullValueHandling.Ignore)]
        public string ExternalType { get; set; }

        /// <summary>
        /// Gets or sets ExternalUrl.
        /// </summary>
        [JsonProperty("external_url", NullValueHandling = NullValueHandling.Ignore)]
        public string ExternalUrl { get; set; }

        /// <summary>
        /// Gets or sets Filetype.
        /// </summary>
        [JsonProperty("filetype", NullValueHandling = NullValueHandling.Ignore)]
        public string Filetype { get; set; }

        /// <summary>
        /// Gets or sets Groups.
        /// </summary>
        [JsonProperty("groups", NullValueHandling = NullValueHandling.Ignore)]
        public List<string> Groups { get; set; }

        /// <summary>
        /// Gets or sets HasRichPreview.
        /// </summary>
        [JsonProperty("has_rich_preview", NullValueHandling = NullValueHandling.Ignore)]
        public bool? HasRichPreview { get; set; }

        /// <summary>
        /// Gets or sets Id.
        /// </summary>
        [JsonProperty("id", NullValueHandling = NullValueHandling.Ignore)]
        public string Id { get; set; }

        /// <summary>
        /// Gets or sets ImageExifRotation.
        /// </summary>
        [JsonProperty("image_exif_rotation", NullValueHandling = NullValueHandling.Ignore)]
        public int? ImageExifRotation { get; set; }

        /// <summary>
        /// Gets or sets Ims.
        /// </summary>
        [JsonProperty("ims", NullValueHandling = NullValueHandling.Ignore)]
        public List<string> Ims { get; set; }

        /// <summary>
        /// Gets or sets IsExternal.
        /// </summary>
        [JsonProperty("is_external", NullValueHandling = NullValueHandling.Ignore)]
        public bool? IsExternal { get; set; }

        /// <summary>
        /// Gets or sets IsPublic.
        /// </summary>
        [JsonProperty("is_public", NullValueHandling = NullValueHandling.Ignore)]
        public bool? IsPublic { get; set; }

        /// <summary>
        /// Gets or sets IsStarred.
        /// </summary>
        [JsonProperty("is_starred", NullValueHandling = NullValueHandling.Ignore)]
        public bool? IsStarred { get; set; }

        /// <summary>
        /// Gets or sets IsTombstoned.
        /// </summary>
        [JsonProperty("is_tombstoned", NullValueHandling = NullValueHandling.Ignore)]
        public bool? IsTombstoned { get; set; }

        /// <summary>
        /// Gets or sets LastEditor.
        /// </summary>
        [JsonProperty("last_editor", NullValueHandling = NullValueHandling.Ignore)]
        public string LastEditor { get; set; }

        /// <summary>
        /// Gets or sets Mimetype.
        /// </summary>
        [JsonProperty("mimetype", NullValueHandling = NullValueHandling.Ignore)]
        public string Mimetype { get; set; }

        /// <summary>
        /// Gets or sets Mode.
        /// </summary>
        [JsonProperty("mode", NullValueHandling = NullValueHandling.Ignore)]
        public string Mode { get; set; }

        /// <summary>
        /// Gets or sets Name.
        /// </summary>
        [JsonProperty("name", NullValueHandling = NullValueHandling.Ignore)]
        public string Name { get; set; }

        /// <summary>
        /// Gets or sets NonOwnerEditable.
        /// </summary>
        [JsonProperty("non_owner_editable", NullValueHandling = NullValueHandling.Ignore)]
        public bool? NonOwnerEditable { get; set; }

        /// <summary>
        /// Gets or sets NumStars.
        /// </summary>
        [JsonProperty("num_stars", NullValueHandling = NullValueHandling.Ignore)]
        public int? NumStars { get; set; }

        /// <summary>
        /// Gets or sets OriginalH.
        /// </summary>
        [JsonProperty("original_h", NullValueHandling = NullValueHandling.Ignore)]
        public int? OriginalH { get; set; }

        /// <summary>
        /// Gets or sets OriginalW.
        /// </summary>
        [JsonProperty("original_w", NullValueHandling = NullValueHandling.Ignore)]
        public int? OriginalW { get; set; }

        /// <summary>
        /// Gets or sets Permalink.
        /// </summary>
        [JsonProperty("permalink", NullValueHandling = NullValueHandling.Ignore)]
        public string Permalink { get; set; }

        /// <summary>
        /// Gets or sets PermalinkPublic.
        /// </summary>
        [JsonProperty("permalink_public", NullValueHandling = NullValueHandling.Ignore)]
        public string PermalinkPublic { get; set; }

        /// <summary>
        /// Gets or sets PinnedInfo.
        /// </summary>
        [JsonProperty("pinned_info", NullValueHandling = NullValueHandling.Ignore)]
        public object PinnedInfo { get; set; }

        /// <summary>
        /// Gets or sets PinnedTo.
        /// </summary>
        [JsonProperty("pinned_to", NullValueHandling = NullValueHandling.Ignore)]
        public List<string> PinnedTo { get; set; }

        /// <summary>
        /// Gets or sets PrettyType.
        /// </summary>
        [JsonProperty("pretty_type", NullValueHandling = NullValueHandling.Ignore)]
        public string PrettyType { get; set; }

        /// <summary>
        /// Gets or sets Preview.
        /// </summary>
        [JsonProperty("preview", NullValueHandling = NullValueHandling.Ignore)]
        public string Preview { get; set; }

        /// <summary>
        /// Gets or sets PublicUrlShared.
        /// </summary>
        [JsonProperty("public_url_shared", NullValueHandling = NullValueHandling.Ignore)]
        public bool? PublicUrlShared { get; set; }

        /// <summary>
        /// Gets or sets Reactions.
        /// </summary>
        [JsonProperty("reactions", NullValueHandling = NullValueHandling.Ignore)]
        public List<Models.ReactionObject> Reactions { get; set; }

        /// <summary>
        /// Gets or sets Shares.
        /// </summary>
        [JsonProperty("shares", NullValueHandling = NullValueHandling.Ignore)]
        public Models.Shares Shares { get; set; }

        /// <summary>
        /// Gets or sets Size.
        /// </summary>
        [JsonProperty("size", NullValueHandling = NullValueHandling.Ignore)]
        public int? Size { get; set; }

        /// <summary>
        /// Gets or sets SourceTeam.
        /// </summary>
        [JsonProperty("source_team", NullValueHandling = NullValueHandling.Ignore)]
        public string SourceTeam { get; set; }

        /// <summary>
        /// Gets or sets State.
        /// </summary>
        [JsonProperty("state", NullValueHandling = NullValueHandling.Ignore)]
        public string State { get; set; }

        /// <summary>
        /// Gets or sets Thumb1024.
        /// </summary>
        [JsonProperty("thumb_1024", NullValueHandling = NullValueHandling.Ignore)]
        public string Thumb1024 { get; set; }

        /// <summary>
        /// Gets or sets Thumb1024H.
        /// </summary>
        [JsonProperty("thumb_1024_h", NullValueHandling = NullValueHandling.Ignore)]
        public int? Thumb1024H { get; set; }

        /// <summary>
        /// Gets or sets Thumb1024W.
        /// </summary>
        [JsonProperty("thumb_1024_w", NullValueHandling = NullValueHandling.Ignore)]
        public int? Thumb1024W { get; set; }

        /// <summary>
        /// Gets or sets Thumb160.
        /// </summary>
        [JsonProperty("thumb_160", NullValueHandling = NullValueHandling.Ignore)]
        public string Thumb160 { get; set; }

        /// <summary>
        /// Gets or sets Thumb360.
        /// </summary>
        [JsonProperty("thumb_360", NullValueHandling = NullValueHandling.Ignore)]
        public string Thumb360 { get; set; }

        /// <summary>
        /// Gets or sets Thumb360H.
        /// </summary>
        [JsonProperty("thumb_360_h", NullValueHandling = NullValueHandling.Ignore)]
        public int? Thumb360H { get; set; }

        /// <summary>
        /// Gets or sets Thumb360W.
        /// </summary>
        [JsonProperty("thumb_360_w", NullValueHandling = NullValueHandling.Ignore)]
        public int? Thumb360W { get; set; }

        /// <summary>
        /// Gets or sets Thumb480.
        /// </summary>
        [JsonProperty("thumb_480", NullValueHandling = NullValueHandling.Ignore)]
        public string Thumb480 { get; set; }

        /// <summary>
        /// Gets or sets Thumb480H.
        /// </summary>
        [JsonProperty("thumb_480_h", NullValueHandling = NullValueHandling.Ignore)]
        public int? Thumb480H { get; set; }

        /// <summary>
        /// Gets or sets Thumb480W.
        /// </summary>
        [JsonProperty("thumb_480_w", NullValueHandling = NullValueHandling.Ignore)]
        public int? Thumb480W { get; set; }

        /// <summary>
        /// Gets or sets Thumb64.
        /// </summary>
        [JsonProperty("thumb_64", NullValueHandling = NullValueHandling.Ignore)]
        public string Thumb64 { get; set; }

        /// <summary>
        /// Gets or sets Thumb720.
        /// </summary>
        [JsonProperty("thumb_720", NullValueHandling = NullValueHandling.Ignore)]
        public string Thumb720 { get; set; }

        /// <summary>
        /// Gets or sets Thumb720H.
        /// </summary>
        [JsonProperty("thumb_720_h", NullValueHandling = NullValueHandling.Ignore)]
        public int? Thumb720H { get; set; }

        /// <summary>
        /// Gets or sets Thumb720W.
        /// </summary>
        [JsonProperty("thumb_720_w", NullValueHandling = NullValueHandling.Ignore)]
        public int? Thumb720W { get; set; }

        /// <summary>
        /// Gets or sets Thumb80.
        /// </summary>
        [JsonProperty("thumb_80", NullValueHandling = NullValueHandling.Ignore)]
        public string Thumb80 { get; set; }

        /// <summary>
        /// Gets or sets Thumb800.
        /// </summary>
        [JsonProperty("thumb_800", NullValueHandling = NullValueHandling.Ignore)]
        public string Thumb800 { get; set; }

        /// <summary>
        /// Gets or sets Thumb800H.
        /// </summary>
        [JsonProperty("thumb_800_h", NullValueHandling = NullValueHandling.Ignore)]
        public int? Thumb800H { get; set; }

        /// <summary>
        /// Gets or sets Thumb800W.
        /// </summary>
        [JsonProperty("thumb_800_w", NullValueHandling = NullValueHandling.Ignore)]
        public int? Thumb800W { get; set; }

        /// <summary>
        /// Gets or sets Thumb960.
        /// </summary>
        [JsonProperty("thumb_960", NullValueHandling = NullValueHandling.Ignore)]
        public string Thumb960 { get; set; }

        /// <summary>
        /// Gets or sets Thumb960H.
        /// </summary>
        [JsonProperty("thumb_960_h", NullValueHandling = NullValueHandling.Ignore)]
        public int? Thumb960H { get; set; }

        /// <summary>
        /// Gets or sets Thumb960W.
        /// </summary>
        [JsonProperty("thumb_960_w", NullValueHandling = NullValueHandling.Ignore)]
        public int? Thumb960W { get; set; }

        /// <summary>
        /// Gets or sets ThumbTiny.
        /// </summary>
        [JsonProperty("thumb_tiny", NullValueHandling = NullValueHandling.Ignore)]
        public string ThumbTiny { get; set; }

        /// <summary>
        /// Gets or sets Timestamp.
        /// </summary>
        [JsonProperty("timestamp", NullValueHandling = NullValueHandling.Ignore)]
        public int? Timestamp { get; set; }

        /// <summary>
        /// Gets or sets Title.
        /// </summary>
        [JsonProperty("title", NullValueHandling = NullValueHandling.Ignore)]
        public string Title { get; set; }

        /// <summary>
        /// Gets or sets Updated.
        /// </summary>
        [JsonProperty("updated", NullValueHandling = NullValueHandling.Ignore)]
        public int? Updated { get; set; }

        /// <summary>
        /// Gets or sets UrlPrivate.
        /// </summary>
        [JsonProperty("url_private", NullValueHandling = NullValueHandling.Ignore)]
        public string UrlPrivate { get; set; }

        /// <summary>
        /// Gets or sets UrlPrivateDownload.
        /// </summary>
        [JsonProperty("url_private_download", NullValueHandling = NullValueHandling.Ignore)]
        public string UrlPrivateDownload { get; set; }

        /// <summary>
        /// Gets or sets User.
        /// </summary>
        [JsonProperty("user", NullValueHandling = NullValueHandling.Ignore)]
        public string User { get; set; }

        /// <summary>
        /// Gets or sets UserTeam.
        /// </summary>
        [JsonProperty("user_team", NullValueHandling = NullValueHandling.Ignore)]
        public string UserTeam { get; set; }

        /// <summary>
        /// Gets or sets Username.
        /// </summary>
        [JsonProperty("username", NullValueHandling = NullValueHandling.Ignore)]
        public string Username { get; set; }

        /// <inheritdoc/>
        public override string ToString()
        {
            var toStringOutput = new List<string>();
            this.ToString(toStringOutput);
            return $"FileObject : ({string.Join(", ", toStringOutput)})";
        }

        /// <inheritdoc/>
        public override bool Equals(object obj)
        {
            if (obj is null) return false;
            if (ReferenceEquals(this, obj)) return true;

            return obj is FileObject other &&
                (this.Channels == null && other.Channels == null ||
                 this.Channels?.Equals(other.Channels) == true) &&
                (this.CommentsCount == null && other.CommentsCount == null ||
                 this.CommentsCount?.Equals(other.CommentsCount) == true) &&
                (this.Created == null && other.Created == null ||
                 this.Created?.Equals(other.Created) == true) &&
                (this.DateDelete == null && other.DateDelete == null ||
                 this.DateDelete?.Equals(other.DateDelete) == true) &&
                (this.DisplayAsBot == null && other.DisplayAsBot == null ||
                 this.DisplayAsBot?.Equals(other.DisplayAsBot) == true) &&
                (this.Editable == null && other.Editable == null ||
                 this.Editable?.Equals(other.Editable) == true) &&
                (this.Editor == null && other.Editor == null ||
                 this.Editor?.Equals(other.Editor) == true) &&
                (this.ExternalId == null && other.ExternalId == null ||
                 this.ExternalId?.Equals(other.ExternalId) == true) &&
                (this.ExternalType == null && other.ExternalType == null ||
                 this.ExternalType?.Equals(other.ExternalType) == true) &&
                (this.ExternalUrl == null && other.ExternalUrl == null ||
                 this.ExternalUrl?.Equals(other.ExternalUrl) == true) &&
                (this.Filetype == null && other.Filetype == null ||
                 this.Filetype?.Equals(other.Filetype) == true) &&
                (this.Groups == null && other.Groups == null ||
                 this.Groups?.Equals(other.Groups) == true) &&
                (this.HasRichPreview == null && other.HasRichPreview == null ||
                 this.HasRichPreview?.Equals(other.HasRichPreview) == true) &&
                (this.Id == null && other.Id == null ||
                 this.Id?.Equals(other.Id) == true) &&
                (this.ImageExifRotation == null && other.ImageExifRotation == null ||
                 this.ImageExifRotation?.Equals(other.ImageExifRotation) == true) &&
                (this.Ims == null && other.Ims == null ||
                 this.Ims?.Equals(other.Ims) == true) &&
                (this.IsExternal == null && other.IsExternal == null ||
                 this.IsExternal?.Equals(other.IsExternal) == true) &&
                (this.IsPublic == null && other.IsPublic == null ||
                 this.IsPublic?.Equals(other.IsPublic) == true) &&
                (this.IsStarred == null && other.IsStarred == null ||
                 this.IsStarred?.Equals(other.IsStarred) == true) &&
                (this.IsTombstoned == null && other.IsTombstoned == null ||
                 this.IsTombstoned?.Equals(other.IsTombstoned) == true) &&
                (this.LastEditor == null && other.LastEditor == null ||
                 this.LastEditor?.Equals(other.LastEditor) == true) &&
                (this.Mimetype == null && other.Mimetype == null ||
                 this.Mimetype?.Equals(other.Mimetype) == true) &&
                (this.Mode == null && other.Mode == null ||
                 this.Mode?.Equals(other.Mode) == true) &&
                (this.Name == null && other.Name == null ||
                 this.Name?.Equals(other.Name) == true) &&
                (this.NonOwnerEditable == null && other.NonOwnerEditable == null ||
                 this.NonOwnerEditable?.Equals(other.NonOwnerEditable) == true) &&
                (this.NumStars == null && other.NumStars == null ||
                 this.NumStars?.Equals(other.NumStars) == true) &&
                (this.OriginalH == null && other.OriginalH == null ||
                 this.OriginalH?.Equals(other.OriginalH) == true) &&
                (this.OriginalW == null && other.OriginalW == null ||
                 this.OriginalW?.Equals(other.OriginalW) == true) &&
                (this.Permalink == null && other.Permalink == null ||
                 this.Permalink?.Equals(other.Permalink) == true) &&
                (this.PermalinkPublic == null && other.PermalinkPublic == null ||
                 this.PermalinkPublic?.Equals(other.PermalinkPublic) == true) &&
                (this.PinnedInfo == null && other.PinnedInfo == null ||
                 this.PinnedInfo?.Equals(other.PinnedInfo) == true) &&
                (this.PinnedTo == null && other.PinnedTo == null ||
                 this.PinnedTo?.Equals(other.PinnedTo) == true) &&
                (this.PrettyType == null && other.PrettyType == null ||
                 this.PrettyType?.Equals(other.PrettyType) == true) &&
                (this.Preview == null && other.Preview == null ||
                 this.Preview?.Equals(other.Preview) == true) &&
                (this.PublicUrlShared == null && other.PublicUrlShared == null ||
                 this.PublicUrlShared?.Equals(other.PublicUrlShared) == true) &&
                (this.Reactions == null && other.Reactions == null ||
                 this.Reactions?.Equals(other.Reactions) == true) &&
                (this.Shares == null && other.Shares == null ||
                 this.Shares?.Equals(other.Shares) == true) &&
                (this.Size == null && other.Size == null ||
                 this.Size?.Equals(other.Size) == true) &&
                (this.SourceTeam == null && other.SourceTeam == null ||
                 this.SourceTeam?.Equals(other.SourceTeam) == true) &&
                (this.State == null && other.State == null ||
                 this.State?.Equals(other.State) == true) &&
                (this.Thumb1024 == null && other.Thumb1024 == null ||
                 this.Thumb1024?.Equals(other.Thumb1024) == true) &&
                (this.Thumb1024H == null && other.Thumb1024H == null ||
                 this.Thumb1024H?.Equals(other.Thumb1024H) == true) &&
                (this.Thumb1024W == null && other.Thumb1024W == null ||
                 this.Thumb1024W?.Equals(other.Thumb1024W) == true) &&
                (this.Thumb160 == null && other.Thumb160 == null ||
                 this.Thumb160?.Equals(other.Thumb160) == true) &&
                (this.Thumb360 == null && other.Thumb360 == null ||
                 this.Thumb360?.Equals(other.Thumb360) == true) &&
                (this.Thumb360H == null && other.Thumb360H == null ||
                 this.Thumb360H?.Equals(other.Thumb360H) == true) &&
                (this.Thumb360W == null && other.Thumb360W == null ||
                 this.Thumb360W?.Equals(other.Thumb360W) == true) &&
                (this.Thumb480 == null && other.Thumb480 == null ||
                 this.Thumb480?.Equals(other.Thumb480) == true) &&
                (this.Thumb480H == null && other.Thumb480H == null ||
                 this.Thumb480H?.Equals(other.Thumb480H) == true) &&
                (this.Thumb480W == null && other.Thumb480W == null ||
                 this.Thumb480W?.Equals(other.Thumb480W) == true) &&
                (this.Thumb64 == null && other.Thumb64 == null ||
                 this.Thumb64?.Equals(other.Thumb64) == true) &&
                (this.Thumb720 == null && other.Thumb720 == null ||
                 this.Thumb720?.Equals(other.Thumb720) == true) &&
                (this.Thumb720H == null && other.Thumb720H == null ||
                 this.Thumb720H?.Equals(other.Thumb720H) == true) &&
                (this.Thumb720W == null && other.Thumb720W == null ||
                 this.Thumb720W?.Equals(other.Thumb720W) == true) &&
                (this.Thumb80 == null && other.Thumb80 == null ||
                 this.Thumb80?.Equals(other.Thumb80) == true) &&
                (this.Thumb800 == null && other.Thumb800 == null ||
                 this.Thumb800?.Equals(other.Thumb800) == true) &&
                (this.Thumb800H == null && other.Thumb800H == null ||
                 this.Thumb800H?.Equals(other.Thumb800H) == true) &&
                (this.Thumb800W == null && other.Thumb800W == null ||
                 this.Thumb800W?.Equals(other.Thumb800W) == true) &&
                (this.Thumb960 == null && other.Thumb960 == null ||
                 this.Thumb960?.Equals(other.Thumb960) == true) &&
                (this.Thumb960H == null && other.Thumb960H == null ||
                 this.Thumb960H?.Equals(other.Thumb960H) == true) &&
                (this.Thumb960W == null && other.Thumb960W == null ||
                 this.Thumb960W?.Equals(other.Thumb960W) == true) &&
                (this.ThumbTiny == null && other.ThumbTiny == null ||
                 this.ThumbTiny?.Equals(other.ThumbTiny) == true) &&
                (this.Timestamp == null && other.Timestamp == null ||
                 this.Timestamp?.Equals(other.Timestamp) == true) &&
                (this.Title == null && other.Title == null ||
                 this.Title?.Equals(other.Title) == true) &&
                (this.Updated == null && other.Updated == null ||
                 this.Updated?.Equals(other.Updated) == true) &&
                (this.UrlPrivate == null && other.UrlPrivate == null ||
                 this.UrlPrivate?.Equals(other.UrlPrivate) == true) &&
                (this.UrlPrivateDownload == null && other.UrlPrivateDownload == null ||
                 this.UrlPrivateDownload?.Equals(other.UrlPrivateDownload) == true) &&
                (this.User == null && other.User == null ||
                 this.User?.Equals(other.User) == true) &&
                (this.UserTeam == null && other.UserTeam == null ||
                 this.UserTeam?.Equals(other.UserTeam) == true) &&
                (this.Username == null && other.Username == null ||
                 this.Username?.Equals(other.Username) == true) &&
                (this.additionalProperties == null && other.additionalProperties == null ||
                 this.additionalProperties?.Count == other.additionalProperties?.Count &&
                 this.additionalProperties?.All(kv =>
                     other.additionalProperties.TryGetValue(kv.Key, out var value) &&
                     JToken.DeepEquals(kv.Value, value)) == true);
        }

        /// <summary>
        /// ToString overload.
        /// </summary>
        /// <param name="toStringOutput">List of strings.</param>
        protected void ToString(List<string> toStringOutput)
        {
            toStringOutput.Add($"Channels = {(this.Channels == null ? "null" : $"[{string.Join(", ", this.Channels)} ]")}");
            toStringOutput.Add($"CommentsCount = {(this.CommentsCount == null ? "null" : this.CommentsCount.ToString())}");
            toStringOutput.Add($"Created = {(this.Created == null ? "null" : this.Created.ToString())}");
            toStringOutput.Add($"DateDelete = {(this.DateDelete == null ? "null" : this.DateDelete.ToString())}");
            toStringOutput.Add($"DisplayAsBot = {(this.DisplayAsBot == null ? "null" : this.DisplayAsBot.ToString())}");
            toStringOutput.Add($"Editable = {(this.Editable == null ? "null" : this.Editable.ToString())}");
            toStringOutput.Add($"Editor = {this.Editor ?? "null"}");
            toStringOutput.Add($"ExternalId = {this.ExternalId ?? "null"}");
            toStringOutput.Add($"ExternalType = {this.ExternalType ?? "null"}");
            toStringOutput.Add($"ExternalUrl = {this.ExternalUrl ?? "null"}");
            toStringOutput.Add($"Filetype = {this.Filetype ?? "null"}");
            toStringOutput.Add($"Groups = {(this.Groups == null ? "null" : $"[{string.Join(", ", this.Groups)} ]")}");
            toStringOutput.Add($"HasRichPreview = {(this.HasRichPreview == null ? "null" : this.HasRichPreview.ToString())}");
            toStringOutput.Add($"Id = {this.Id ?? "null"}");
            toStringOutput.Add($"ImageExifRotation = {(this.ImageExifRotation == null ? "null" : this.ImageExifRotation.ToString())}");
            toStringOutput.Add($"Ims = {(this.Ims == null ? "null" : $"[{string.Join(", ", this.Ims)} ]")}");
            toStringOutput.Add($"IsExternal = {(this.IsExternal == null ? "null" : this.IsExternal.ToString())}");
            toStringOutput.Add($"IsPublic = {(this.IsPublic == null ? "null" : this.IsPublic.ToString())}");
            toStringOutput.Add($"IsStarred = {(this.IsStarred == null ? "null" : this.IsStarred.ToString())}");
            toStringOutput.Add($"IsTombstoned = {(this.IsTombstoned == null ? "null" : this.IsTombstoned.ToString())}");
            toStringOutput.Add($"LastEditor = {this.LastEditor ?? "null"}");
            toStringOutput.Add($"Mimetype = {this.Mimetype ?? "null"}");
            toStringOutput.Add($"Mode = {this.Mode ?? "null"}");
            toStringOutput.Add($"Name = {this.Name ?? "null"}");
            toStringOutput.Add($"NonOwnerEditable = {(this.NonOwnerEditable == null ? "null" : this.NonOwnerEditable.ToString())}");
            toStringOutput.Add($"NumStars = {(this.NumStars == null ? "null" : this.NumStars.ToString())}");
            toStringOutput.Add($"OriginalH = {(this.OriginalH == null ? "null" : this.OriginalH.ToString())}");
            toStringOutput.Add($"OriginalW = {(this.OriginalW == null ? "null" : this.OriginalW.ToString())}");
            toStringOutput.Add($"Permalink = {this.Permalink ?? "null"}");
            toStringOutput.Add($"PermalinkPublic = {this.PermalinkPublic ?? "null"}");
            toStringOutput.Add($"PinnedInfo = {(this.PinnedInfo == null ? "null" : this.PinnedInfo.ToString())}");
            toStringOutput.Add($"PinnedTo = {(this.PinnedTo == null ? "null" : $"[{string.Join(", ", this.PinnedTo)} ]")}");
            toStringOutput.Add($"PrettyType = {this.PrettyType ?? "null"}");
            toStringOutput.Add($"Preview = {this.Preview ?? "null"}");
            toStringOutput.Add($"PublicUrlShared = {(this.PublicUrlShared == null ? "null" : this.PublicUrlShared.ToString())}");
            toStringOutput.Add($"Reactions = {(this.Reactions == null ? "null" : $"[{string.Join(", ", this.Reactions)} ]")}");
            toStringOutput.Add($"Shares = {(this.Shares == null ? "null" : this.Shares.ToString())}");
            toStringOutput.Add($"Size = {(this.Size == null ? "null" : this.Size.ToString())}");
            toStringOutput.Add($"SourceTeam = {this.SourceTeam ?? "null"}");
            toStringOutput.Add($"State = {this.State ?? "null"}");
            toStringOutput.Add($"Thumb1024 = {this.Thumb1024 ?? "null"}");
            toStringOutput.Add($"Thumb1024H = {(this.Thumb1024H == null ? "null" : this.Thumb1024H.ToString())}");
            toStringOutput.Add($"Thumb1024W = {(this.Thumb1024W == null ? "null" : this.Thumb1024W.ToString())}");
            toStringOutput.Add($"Thumb160 = {this.Thumb160 ?? "null"}");
            toStringOutput.Add($"Thumb360 = {this.Thumb360 ?? "null"}");
            toStringOutput.Add($"Thumb360H = {(this.Thumb360H == null ? "null" : this.Thumb360H.ToString())}");
            toStringOutput.Add($"Thumb360W = {(this.Thumb360W == null ? "null" : this.Thumb360W.ToString())}");
            toStringOutput.Add($"Thumb480 = {this.Thumb480 ?? "null"}");
            toStringOutput.Add($"Thumb480H = {(this.Thumb480H == null ? "null" : this.Thumb480H.ToString())}");
            toStringOutput.Add($"Thumb480W = {(this.Thumb480W == null ? "null" : this.Thumb480W.ToString())}");
            toStringOutput.Add($"Thumb64 = {this.Thumb64 ?? "null"}");
            toStringOutput.Add($"Thumb720 = {this.Thumb720 ?? "null"}");
            toStringOutput.Add($"Thumb720H = {(this.Thumb720H == null ? "null" : this.Thumb720H.ToString())}");
            toStringOutput.Add($"Thumb720W = {(this.Thumb720W == null ? "null" : this.Thumb720W.ToString())}");
            toStringOutput.Add($"Thumb80 = {this.Thumb80 ?? "null"}");
            toStringOutput.Add($"Thumb800 = {this.Thumb800 ?? "null"}");
            toStringOutput.Add($"Thumb800H = {(this.Thumb800H == null ? "null" : this.Thumb800H.ToString())}");
            toStringOutput.Add($"Thumb800W = {(this.Thumb800W == null ? "null" : this.Thumb800W.ToString())}");
            toStringOutput.Add($"Thumb960 = {this.Thumb960 ?? "null"}");
            toStringOutput.Add($"Thumb960H = {(this.Thumb960H == null ? "null" : this.Thumb960H.ToString())}");
            toStringOutput.Add($"Thumb960W = {(this.Thumb960W == null ? "null" : this.Thumb960W.ToString())}");
            toStringOutput.Add($"ThumbTiny = {this.ThumbTiny ?? "null"}");
            toStringOutput.Add($"Timestamp = {(this.Timestamp == null ? "null" : this.Timestamp.ToString())}");
            toStringOutput.Add($"Title = {this.Title ?? "null"}");
            toStringOutput.Add($"Updated = {(this.Updated == null ? "null" : this.Updated.ToString())}");
            toStringOutput.Add($"UrlPrivate = {this.UrlPrivate ?? "null"}");
            toStringOutput.Add($"UrlPrivateDownload = {this.UrlPrivateDownload ?? "null"}");
            toStringOutput.Add($"User = {this.User ?? "null"}");
            toStringOutput.Add($"UserTeam = {this.UserTeam ?? "null"}");
            toStringOutput.Add($"Username = {this.Username ?? "null"}");

            additionalProperties?
                .Select(kvp => $"[{kvp.Key}] = {kvp.Value.ToString(Formatting.None)}")
                .ToList()
                .ForEach(toStringOutput.Add);
        }
    }
}