// <copyright file="FileCommentObject.cs" company="APIMatic">
// SlackWebApi.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using SlackWebApi.Standard.Utilities;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;

namespace SlackWebApi.Standard.Models
{
    /// <summary>
    /// FileCommentObject.
    /// </summary>
    public class FileCommentObject
    {
        [JsonExtensionData]
        private readonly IDictionary<string, JToken> additionalProperties;

        private readonly IEnumerable<string> propertyName;

        /// <summary>
        /// Get or set the value associated with the specified key in the AdditionalProperties dictionary.
        /// </summary>
        /// <param name="key">The key of the value to get or set. This must be a valid key that is not reserved for internal properties.</param>
        /// <returns>The object value associated with the specified key in the AdditionalProperties dictionary.</returns>
        /// <exception cref="System.ArgumentNullException">
        /// Thrown when <paramref name="key"/> is null or an empty string.
        /// </exception>
        /// <exception cref="System.ArgumentException">
        /// Thrown when the specified <paramref name="key"/> conflicts with an internal property of the object.
        /// </exception>
        /// <exception cref="KeyNotFoundException">
        /// Thrown when the specified <paramref name="key"/> does not exist in the AdditionalProperties dictionary.
        /// </exception>
        [IndexerName("AdditionalPropertiesIndexer")]
        public object this[string key]
        {
            get => additionalProperties.GetValue<object>(key);
            set => additionalProperties.SetValue(key, value, propertyName);
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="FileCommentObject"/> class.
        /// </summary>
        public FileCommentObject()
        {
            this.additionalProperties = new Dictionary<string, JToken>();
            this.propertyName = this.GetPropertyNames();
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="FileCommentObject"/> class.
        /// </summary>
        /// <param name="comment">comment.</param>
        /// <param name="created">created.</param>
        /// <param name="id">id.</param>
        /// <param name="isIntro">is_intro.</param>
        /// <param name="timestamp">timestamp.</param>
        /// <param name="user">user.</param>
        /// <param name="isStarred">is_starred.</param>
        /// <param name="numStars">num_stars.</param>
        /// <param name="pinnedInfo">pinned_info.</param>
        /// <param name="pinnedTo">pinned_to.</param>
        /// <param name="reactions">reactions.</param>
        public FileCommentObject(
            string comment,
            int created,
            string id,
            bool isIntro,
            int timestamp,
            string user,
            bool? isStarred = null,
            int? numStars = null,
            object pinnedInfo = null,
            List<string> pinnedTo = null,
            List<Models.ReactionObject> reactions = null)
        {
            this.additionalProperties = new Dictionary<string, JToken>();
            this.propertyName = this.GetPropertyNames();
            this.Comment = comment;
            this.Created = created;
            this.Id = id;
            this.IsIntro = isIntro;
            this.IsStarred = isStarred;
            this.NumStars = numStars;
            this.PinnedInfo = pinnedInfo;
            this.PinnedTo = pinnedTo;
            this.Reactions = reactions;
            this.Timestamp = timestamp;
            this.User = user;
        }

        /// <summary>
        /// Gets or sets Comment.
        /// </summary>
        [JsonProperty("comment")]
        public string Comment { get; set; }

        /// <summary>
        /// Gets or sets Created.
        /// </summary>
        [JsonProperty("created")]
        public int Created { get; set; }

        /// <summary>
        /// Gets or sets Id.
        /// </summary>
        [JsonProperty("id")]
        public string Id { get; set; }

        /// <summary>
        /// Gets or sets IsIntro.
        /// </summary>
        [JsonProperty("is_intro")]
        public bool IsIntro { get; set; }

        /// <summary>
        /// Gets or sets IsStarred.
        /// </summary>
        [JsonProperty("is_starred", NullValueHandling = NullValueHandling.Ignore)]
        public bool? IsStarred { get; set; }

        /// <summary>
        /// Gets or sets NumStars.
        /// </summary>
        [JsonProperty("num_stars", NullValueHandling = NullValueHandling.Ignore)]
        public int? NumStars { get; set; }

        /// <summary>
        /// Gets or sets PinnedInfo.
        /// </summary>
        [JsonProperty("pinned_info", NullValueHandling = NullValueHandling.Ignore)]
        public object PinnedInfo { get; set; }

        /// <summary>
        /// Gets or sets PinnedTo.
        /// </summary>
        [JsonProperty("pinned_to", NullValueHandling = NullValueHandling.Ignore)]
        public List<string> PinnedTo { get; set; }

        /// <summary>
        /// Gets or sets Reactions.
        /// </summary>
        [JsonProperty("reactions", NullValueHandling = NullValueHandling.Ignore)]
        public List<Models.ReactionObject> Reactions { get; set; }

        /// <summary>
        /// Gets or sets Timestamp.
        /// </summary>
        [JsonProperty("timestamp")]
        public int Timestamp { get; set; }

        /// <summary>
        /// Gets or sets User.
        /// </summary>
        [JsonProperty("user")]
        public string User { get; set; }

        /// <inheritdoc/>
        public override string ToString()
        {
            var toStringOutput = new List<string>();
            this.ToString(toStringOutput);
            return $"FileCommentObject : ({string.Join(", ", toStringOutput)})";
        }

        /// <inheritdoc/>
        public override bool Equals(object obj)
        {
            if (obj is null) return false;
            if (ReferenceEquals(this, obj)) return true;

            return obj is FileCommentObject other &&
                (this.Comment == null && other.Comment == null ||
                 this.Comment?.Equals(other.Comment) == true) &&
                (this.Created.Equals(other.Created)) &&
                (this.Id == null && other.Id == null ||
                 this.Id?.Equals(other.Id) == true) &&
                (this.IsIntro.Equals(other.IsIntro)) &&
                (this.IsStarred == null && other.IsStarred == null ||
                 this.IsStarred?.Equals(other.IsStarred) == true) &&
                (this.NumStars == null && other.NumStars == null ||
                 this.NumStars?.Equals(other.NumStars) == true) &&
                (this.PinnedInfo == null && other.PinnedInfo == null ||
                 this.PinnedInfo?.Equals(other.PinnedInfo) == true) &&
                (this.PinnedTo == null && other.PinnedTo == null ||
                 this.PinnedTo?.Equals(other.PinnedTo) == true) &&
                (this.Reactions == null && other.Reactions == null ||
                 this.Reactions?.Equals(other.Reactions) == true) &&
                (this.Timestamp.Equals(other.Timestamp)) &&
                (this.User == null && other.User == null ||
                 this.User?.Equals(other.User) == true) &&
                (this.additionalProperties == null && other.additionalProperties == null ||
                 this.additionalProperties?.Count == other.additionalProperties?.Count &&
                 this.additionalProperties?.All(kv =>
                     other.additionalProperties.TryGetValue(kv.Key, out var value) &&
                     JToken.DeepEquals(kv.Value, value)) == true);
        }

        /// <summary>
        /// ToString overload.
        /// </summary>
        /// <param name="toStringOutput">List of strings.</param>
        protected void ToString(List<string> toStringOutput)
        {
            toStringOutput.Add($"Comment = {this.Comment ?? "null"}");
            toStringOutput.Add($"Created = {this.Created}");
            toStringOutput.Add($"Id = {this.Id ?? "null"}");
            toStringOutput.Add($"IsIntro = {this.IsIntro}");
            toStringOutput.Add($"IsStarred = {(this.IsStarred == null ? "null" : this.IsStarred.ToString())}");
            toStringOutput.Add($"NumStars = {(this.NumStars == null ? "null" : this.NumStars.ToString())}");
            toStringOutput.Add($"PinnedInfo = {(this.PinnedInfo == null ? "null" : this.PinnedInfo.ToString())}");
            toStringOutput.Add($"PinnedTo = {(this.PinnedTo == null ? "null" : $"[{string.Join(", ", this.PinnedTo)} ]")}");
            toStringOutput.Add($"Reactions = {(this.Reactions == null ? "null" : $"[{string.Join(", ", this.Reactions)} ]")}");
            toStringOutput.Add($"Timestamp = {this.Timestamp}");
            toStringOutput.Add($"User = {this.User ?? "null"}");

            additionalProperties?
                .Select(kvp => $"[{kvp.Key}] = {kvp.Value.ToString(Formatting.None)}")
                .ToList()
                .ForEach(toStringOutput.Add);
        }
    }
}