// <copyright file="Login.cs" company="APIMatic">
// SlackWebApi.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using SlackWebApi.Standard.Utilities;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;

namespace SlackWebApi.Standard.Models
{
    /// <summary>
    /// Login.
    /// </summary>
    public class Login
    {
        [JsonExtensionData]
        private readonly IDictionary<string, JToken> additionalProperties;

        private readonly IEnumerable<string> propertyName;

        /// <summary>
        /// Get or set the value associated with the specified key in the AdditionalProperties dictionary.
        /// </summary>
        /// <param name="key">The key of the value to get or set. This must be a valid key that is not reserved for internal properties.</param>
        /// <returns>The object value associated with the specified key in the AdditionalProperties dictionary.</returns>
        /// <exception cref="System.ArgumentNullException">
        /// Thrown when <paramref name="key"/> is null or an empty string.
        /// </exception>
        /// <exception cref="System.ArgumentException">
        /// Thrown when the specified <paramref name="key"/> conflicts with an internal property of the object.
        /// </exception>
        /// <exception cref="KeyNotFoundException">
        /// Thrown when the specified <paramref name="key"/> does not exist in the AdditionalProperties dictionary.
        /// </exception>
        [IndexerName("AdditionalPropertiesIndexer")]
        public object this[string key]
        {
            get => additionalProperties.GetValue<object>(key);
            set => additionalProperties.SetValue(key, value, propertyName);
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="Login"/> class.
        /// </summary>
        public Login()
        {
            this.additionalProperties = new Dictionary<string, JToken>();
            this.propertyName = this.GetPropertyNames();
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="Login"/> class.
        /// </summary>
        /// <param name="count">count.</param>
        /// <param name="dateFirst">date_first.</param>
        /// <param name="dateLast">date_last.</param>
        /// <param name="userAgent">user_agent.</param>
        /// <param name="userId">user_id.</param>
        /// <param name="username">username.</param>
        /// <param name="country">country.</param>
        /// <param name="ip">ip.</param>
        /// <param name="isp">isp.</param>
        /// <param name="region">region.</param>
        public Login(
            int count,
            int dateFirst,
            int dateLast,
            string userAgent,
            string userId,
            string username,
            string country = null,
            string ip = null,
            string isp = null,
            string region = null)
        {
            this.additionalProperties = new Dictionary<string, JToken>();
            this.propertyName = this.GetPropertyNames();
            this.Count = count;
            this.Country = country;
            this.DateFirst = dateFirst;
            this.DateLast = dateLast;
            this.Ip = ip;
            this.Isp = isp;
            this.Region = region;
            this.UserAgent = userAgent;
            this.UserId = userId;
            this.Username = username;
        }

        /// <summary>
        /// Gets or sets Count.
        /// </summary>
        [JsonProperty("count")]
        public int Count { get; set; }

        /// <summary>
        /// Gets or sets Country.
        /// </summary>
        [JsonProperty("country", NullValueHandling = NullValueHandling.Include)]
        public string Country { get; set; }

        /// <summary>
        /// Gets or sets DateFirst.
        /// </summary>
        [JsonProperty("date_first")]
        public int DateFirst { get; set; }

        /// <summary>
        /// Gets or sets DateLast.
        /// </summary>
        [JsonProperty("date_last")]
        public int DateLast { get; set; }

        /// <summary>
        /// Gets or sets Ip.
        /// </summary>
        [JsonProperty("ip", NullValueHandling = NullValueHandling.Include)]
        public string Ip { get; set; }

        /// <summary>
        /// Gets or sets Isp.
        /// </summary>
        [JsonProperty("isp", NullValueHandling = NullValueHandling.Include)]
        public string Isp { get; set; }

        /// <summary>
        /// Gets or sets Region.
        /// </summary>
        [JsonProperty("region", NullValueHandling = NullValueHandling.Include)]
        public string Region { get; set; }

        /// <summary>
        /// Gets or sets UserAgent.
        /// </summary>
        [JsonProperty("user_agent")]
        public string UserAgent { get; set; }

        /// <summary>
        /// Gets or sets UserId.
        /// </summary>
        [JsonProperty("user_id")]
        public string UserId { get; set; }

        /// <summary>
        /// Gets or sets Username.
        /// </summary>
        [JsonProperty("username")]
        public string Username { get; set; }

        /// <inheritdoc/>
        public override string ToString()
        {
            var toStringOutput = new List<string>();
            this.ToString(toStringOutput);
            return $"Login : ({string.Join(", ", toStringOutput)})";
        }

        /// <inheritdoc/>
        public override bool Equals(object obj)
        {
            if (obj is null) return false;
            if (ReferenceEquals(this, obj)) return true;

            return obj is Login other &&
                (this.Count.Equals(other.Count)) &&
                (this.Country == null && other.Country == null ||
                 this.Country?.Equals(other.Country) == true) &&
                (this.DateFirst.Equals(other.DateFirst)) &&
                (this.DateLast.Equals(other.DateLast)) &&
                (this.Ip == null && other.Ip == null ||
                 this.Ip?.Equals(other.Ip) == true) &&
                (this.Isp == null && other.Isp == null ||
                 this.Isp?.Equals(other.Isp) == true) &&
                (this.Region == null && other.Region == null ||
                 this.Region?.Equals(other.Region) == true) &&
                (this.UserAgent == null && other.UserAgent == null ||
                 this.UserAgent?.Equals(other.UserAgent) == true) &&
                (this.UserId == null && other.UserId == null ||
                 this.UserId?.Equals(other.UserId) == true) &&
                (this.Username == null && other.Username == null ||
                 this.Username?.Equals(other.Username) == true) &&
                (this.additionalProperties == null && other.additionalProperties == null ||
                 this.additionalProperties?.Count == other.additionalProperties?.Count &&
                 this.additionalProperties?.All(kv =>
                     other.additionalProperties.TryGetValue(kv.Key, out var value) &&
                     JToken.DeepEquals(kv.Value, value)) == true);
        }

        /// <summary>
        /// ToString overload.
        /// </summary>
        /// <param name="toStringOutput">List of strings.</param>
        protected void ToString(List<string> toStringOutput)
        {
            toStringOutput.Add($"Count = {this.Count}");
            toStringOutput.Add($"Country = {this.Country ?? "null"}");
            toStringOutput.Add($"DateFirst = {this.DateFirst}");
            toStringOutput.Add($"DateLast = {this.DateLast}");
            toStringOutput.Add($"Ip = {this.Ip ?? "null"}");
            toStringOutput.Add($"Isp = {this.Isp ?? "null"}");
            toStringOutput.Add($"Region = {this.Region ?? "null"}");
            toStringOutput.Add($"UserAgent = {this.UserAgent ?? "null"}");
            toStringOutput.Add($"UserId = {this.UserId ?? "null"}");
            toStringOutput.Add($"Username = {this.Username ?? "null"}");

            additionalProperties?
                .Select(kvp => $"[{kvp.Key}] = {kvp.Value.ToString(Formatting.None)}")
                .ToList()
                .ForEach(toStringOutput.Add);
        }
    }
}