// <copyright file="ObjsUserProfileShort.cs" company="APIMatic">
// SlackWebApi.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using SlackWebApi.Standard.Utilities;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;

namespace SlackWebApi.Standard.Models
{
    /// <summary>
    /// ObjsUserProfileShort.
    /// </summary>
    public class ObjsUserProfileShort
    {
        [JsonExtensionData]
        private readonly IDictionary<string, JToken> additionalProperties;

        private readonly IEnumerable<string> propertyName;

        /// <summary>
        /// Get or set the value associated with the specified key in the AdditionalProperties dictionary.
        /// </summary>
        /// <param name="key">The key of the value to get or set. This must be a valid key that is not reserved for internal properties.</param>
        /// <returns>The object value associated with the specified key in the AdditionalProperties dictionary.</returns>
        /// <exception cref="System.ArgumentNullException">
        /// Thrown when <paramref name="key"/> is null or an empty string.
        /// </exception>
        /// <exception cref="System.ArgumentException">
        /// Thrown when the specified <paramref name="key"/> conflicts with an internal property of the object.
        /// </exception>
        /// <exception cref="KeyNotFoundException">
        /// Thrown when the specified <paramref name="key"/> does not exist in the AdditionalProperties dictionary.
        /// </exception>
        [IndexerName("AdditionalPropertiesIndexer")]
        public object this[string key]
        {
            get => additionalProperties.GetValue<object>(key);
            set => additionalProperties.SetValue(key, value, propertyName);
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="ObjsUserProfileShort"/> class.
        /// </summary>
        public ObjsUserProfileShort()
        {
            this.additionalProperties = new Dictionary<string, JToken>();
            this.propertyName = this.GetPropertyNames();
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="ObjsUserProfileShort"/> class.
        /// </summary>
        /// <param name="avatarHash">avatar_hash.</param>
        /// <param name="displayName">display_name.</param>
        /// <param name="image72">image_72.</param>
        /// <param name="isRestricted">is_restricted.</param>
        /// <param name="isUltraRestricted">is_ultra_restricted.</param>
        /// <param name="name">name.</param>
        /// <param name="realName">real_name.</param>
        /// <param name="team">team.</param>
        /// <param name="displayNameNormalized">display_name_normalized.</param>
        /// <param name="firstName">first_name.</param>
        /// <param name="realNameNormalized">real_name_normalized.</param>
        public ObjsUserProfileShort(
            string avatarHash,
            string displayName,
            string image72,
            bool isRestricted,
            bool isUltraRestricted,
            string name,
            string realName,
            string team,
            string displayNameNormalized = null,
            string firstName = null,
            string realNameNormalized = null)
        {
            this.additionalProperties = new Dictionary<string, JToken>();
            this.propertyName = this.GetPropertyNames();
            this.AvatarHash = avatarHash;
            this.DisplayName = displayName;
            this.DisplayNameNormalized = displayNameNormalized;
            this.FirstName = firstName;
            this.Image72 = image72;
            this.IsRestricted = isRestricted;
            this.IsUltraRestricted = isUltraRestricted;
            this.Name = name;
            this.RealName = realName;
            this.RealNameNormalized = realNameNormalized;
            this.Team = team;
        }

        /// <summary>
        /// Gets or sets AvatarHash.
        /// </summary>
        [JsonProperty("avatar_hash")]
        public string AvatarHash { get; set; }

        /// <summary>
        /// Gets or sets DisplayName.
        /// </summary>
        [JsonProperty("display_name")]
        public string DisplayName { get; set; }

        /// <summary>
        /// Gets or sets DisplayNameNormalized.
        /// </summary>
        [JsonProperty("display_name_normalized", NullValueHandling = NullValueHandling.Ignore)]
        public string DisplayNameNormalized { get; set; }

        /// <summary>
        /// Gets or sets FirstName.
        /// </summary>
        [JsonProperty("first_name", NullValueHandling = NullValueHandling.Include)]
        public string FirstName { get; set; }

        /// <summary>
        /// Gets or sets Image72.
        /// </summary>
        [JsonProperty("image_72")]
        public string Image72 { get; set; }

        /// <summary>
        /// Gets or sets IsRestricted.
        /// </summary>
        [JsonProperty("is_restricted")]
        public bool IsRestricted { get; set; }

        /// <summary>
        /// Gets or sets IsUltraRestricted.
        /// </summary>
        [JsonProperty("is_ultra_restricted")]
        public bool IsUltraRestricted { get; set; }

        /// <summary>
        /// Gets or sets Name.
        /// </summary>
        [JsonProperty("name")]
        public string Name { get; set; }

        /// <summary>
        /// Gets or sets RealName.
        /// </summary>
        [JsonProperty("real_name")]
        public string RealName { get; set; }

        /// <summary>
        /// Gets or sets RealNameNormalized.
        /// </summary>
        [JsonProperty("real_name_normalized", NullValueHandling = NullValueHandling.Ignore)]
        public string RealNameNormalized { get; set; }

        /// <summary>
        /// Gets or sets Team.
        /// </summary>
        [JsonProperty("team")]
        public string Team { get; set; }

        /// <inheritdoc/>
        public override string ToString()
        {
            var toStringOutput = new List<string>();
            this.ToString(toStringOutput);
            return $"ObjsUserProfileShort : ({string.Join(", ", toStringOutput)})";
        }

        /// <inheritdoc/>
        public override bool Equals(object obj)
        {
            if (obj is null) return false;
            if (ReferenceEquals(this, obj)) return true;

            return obj is ObjsUserProfileShort other &&
                (this.AvatarHash == null && other.AvatarHash == null ||
                 this.AvatarHash?.Equals(other.AvatarHash) == true) &&
                (this.DisplayName == null && other.DisplayName == null ||
                 this.DisplayName?.Equals(other.DisplayName) == true) &&
                (this.DisplayNameNormalized == null && other.DisplayNameNormalized == null ||
                 this.DisplayNameNormalized?.Equals(other.DisplayNameNormalized) == true) &&
                (this.FirstName == null && other.FirstName == null ||
                 this.FirstName?.Equals(other.FirstName) == true) &&
                (this.Image72 == null && other.Image72 == null ||
                 this.Image72?.Equals(other.Image72) == true) &&
                (this.IsRestricted.Equals(other.IsRestricted)) &&
                (this.IsUltraRestricted.Equals(other.IsUltraRestricted)) &&
                (this.Name == null && other.Name == null ||
                 this.Name?.Equals(other.Name) == true) &&
                (this.RealName == null && other.RealName == null ||
                 this.RealName?.Equals(other.RealName) == true) &&
                (this.RealNameNormalized == null && other.RealNameNormalized == null ||
                 this.RealNameNormalized?.Equals(other.RealNameNormalized) == true) &&
                (this.Team == null && other.Team == null ||
                 this.Team?.Equals(other.Team) == true) &&
                (this.additionalProperties == null && other.additionalProperties == null ||
                 this.additionalProperties?.Count == other.additionalProperties?.Count &&
                 this.additionalProperties?.All(kv =>
                     other.additionalProperties.TryGetValue(kv.Key, out var value) &&
                     JToken.DeepEquals(kv.Value, value)) == true);
        }

        /// <summary>
        /// ToString overload.
        /// </summary>
        /// <param name="toStringOutput">List of strings.</param>
        protected void ToString(List<string> toStringOutput)
        {
            toStringOutput.Add($"AvatarHash = {this.AvatarHash ?? "null"}");
            toStringOutput.Add($"DisplayName = {this.DisplayName ?? "null"}");
            toStringOutput.Add($"DisplayNameNormalized = {this.DisplayNameNormalized ?? "null"}");
            toStringOutput.Add($"FirstName = {this.FirstName ?? "null"}");
            toStringOutput.Add($"Image72 = {this.Image72 ?? "null"}");
            toStringOutput.Add($"IsRestricted = {this.IsRestricted}");
            toStringOutput.Add($"IsUltraRestricted = {this.IsUltraRestricted}");
            toStringOutput.Add($"Name = {this.Name ?? "null"}");
            toStringOutput.Add($"RealName = {this.RealName ?? "null"}");
            toStringOutput.Add($"RealNameNormalized = {this.RealNameNormalized ?? "null"}");
            toStringOutput.Add($"Team = {this.Team ?? "null"}");

            additionalProperties?
                .Select(kvp => $"[{kvp.Key}] = {kvp.Value.ToString(Formatting.None)}")
                .ToList()
                .ForEach(toStringOutput.Add);
        }
    }
}