// <copyright file="Plan.cs" company="APIMatic">
// SlackWebApi.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using APIMatic.Core.Utilities.Converters;
using Newtonsoft.Json;
using System.Runtime.Serialization;

namespace SlackWebApi.Standard.Models
{
    /// <summary>
    /// Plan.
    /// </summary>

    [JsonConverter(typeof(StringEnumConverter))]
    public enum Plan
    {
        /// <summary>
        /// Std.
        /// </summary>
        [EnumMember(Value = "std")]
        Std,

        /// <summary>
        /// Plus.
        /// </summary>
        [EnumMember(Value = "plus")]
        Plus,

        /// <summary>
        /// Compliance.
        /// </summary>
        [EnumMember(Value = "compliance")]
        Compliance,

        /// <summary>
        /// Enterprise.
        /// </summary>
        [EnumMember(Value = "enterprise")]
        Enterprise
    }
}