// <copyright file="Profile1.cs" company="APIMatic">
// SlackWebApi.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using SlackWebApi.Standard.Utilities;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;

namespace SlackWebApi.Standard.Models
{
    /// <summary>
    /// Profile1.
    /// </summary>
    public class Profile1
    {
        [JsonExtensionData]
        private readonly IDictionary<string, JToken> additionalProperties;

        private readonly IEnumerable<string> propertyName;

        /// <summary>
        /// Get or set the value associated with the specified key in the AdditionalProperties dictionary.
        /// </summary>
        /// <param name="key">The key of the value to get or set. This must be a valid key that is not reserved for internal properties.</param>
        /// <returns>The object value associated with the specified key in the AdditionalProperties dictionary.</returns>
        /// <exception cref="System.ArgumentNullException">
        /// Thrown when <paramref name="key"/> is null or an empty string.
        /// </exception>
        /// <exception cref="System.ArgumentException">
        /// Thrown when the specified <paramref name="key"/> conflicts with an internal property of the object.
        /// </exception>
        /// <exception cref="KeyNotFoundException">
        /// Thrown when the specified <paramref name="key"/> does not exist in the AdditionalProperties dictionary.
        /// </exception>
        [IndexerName("AdditionalPropertiesIndexer")]
        public object this[string key]
        {
            get => additionalProperties.GetValue<object>(key);
            set => additionalProperties.SetValue(key, value, propertyName);
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="Profile1"/> class.
        /// </summary>
        public Profile1()
        {
            this.additionalProperties = new Dictionary<string, JToken>();
            this.propertyName = this.GetPropertyNames();
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="Profile1"/> class.
        /// </summary>
        /// <param name="avatarHash">avatar_hash.</param>
        /// <param name="image1024">image_1024.</param>
        /// <param name="image192">image_192.</param>
        /// <param name="image24">image_24.</param>
        /// <param name="image32">image_32.</param>
        /// <param name="image48">image_48.</param>
        /// <param name="image512">image_512.</param>
        /// <param name="image72">image_72.</param>
        /// <param name="imageOriginal">image_original.</param>
        public Profile1(
            string avatarHash,
            string image1024,
            string image192,
            string image24,
            string image32,
            string image48,
            string image512,
            string image72,
            string imageOriginal)
        {
            this.additionalProperties = new Dictionary<string, JToken>();
            this.propertyName = this.GetPropertyNames();
            this.AvatarHash = avatarHash;
            this.Image1024 = image1024;
            this.Image192 = image192;
            this.Image24 = image24;
            this.Image32 = image32;
            this.Image48 = image48;
            this.Image512 = image512;
            this.Image72 = image72;
            this.ImageOriginal = imageOriginal;
        }

        /// <summary>
        /// Gets or sets AvatarHash.
        /// </summary>
        [JsonProperty("avatar_hash")]
        public string AvatarHash { get; set; }

        /// <summary>
        /// Gets or sets Image1024.
        /// </summary>
        [JsonProperty("image_1024")]
        public string Image1024 { get; set; }

        /// <summary>
        /// Gets or sets Image192.
        /// </summary>
        [JsonProperty("image_192")]
        public string Image192 { get; set; }

        /// <summary>
        /// Gets or sets Image24.
        /// </summary>
        [JsonProperty("image_24")]
        public string Image24 { get; set; }

        /// <summary>
        /// Gets or sets Image32.
        /// </summary>
        [JsonProperty("image_32")]
        public string Image32 { get; set; }

        /// <summary>
        /// Gets or sets Image48.
        /// </summary>
        [JsonProperty("image_48")]
        public string Image48 { get; set; }

        /// <summary>
        /// Gets or sets Image512.
        /// </summary>
        [JsonProperty("image_512")]
        public string Image512 { get; set; }

        /// <summary>
        /// Gets or sets Image72.
        /// </summary>
        [JsonProperty("image_72")]
        public string Image72 { get; set; }

        /// <summary>
        /// Gets or sets ImageOriginal.
        /// </summary>
        [JsonProperty("image_original")]
        public string ImageOriginal { get; set; }

        /// <inheritdoc/>
        public override string ToString()
        {
            var toStringOutput = new List<string>();
            this.ToString(toStringOutput);
            return $"Profile1 : ({string.Join(", ", toStringOutput)})";
        }

        /// <inheritdoc/>
        public override bool Equals(object obj)
        {
            if (obj is null) return false;
            if (ReferenceEquals(this, obj)) return true;

            return obj is Profile1 other &&
                (this.AvatarHash == null && other.AvatarHash == null ||
                 this.AvatarHash?.Equals(other.AvatarHash) == true) &&
                (this.Image1024 == null && other.Image1024 == null ||
                 this.Image1024?.Equals(other.Image1024) == true) &&
                (this.Image192 == null && other.Image192 == null ||
                 this.Image192?.Equals(other.Image192) == true) &&
                (this.Image24 == null && other.Image24 == null ||
                 this.Image24?.Equals(other.Image24) == true) &&
                (this.Image32 == null && other.Image32 == null ||
                 this.Image32?.Equals(other.Image32) == true) &&
                (this.Image48 == null && other.Image48 == null ||
                 this.Image48?.Equals(other.Image48) == true) &&
                (this.Image512 == null && other.Image512 == null ||
                 this.Image512?.Equals(other.Image512) == true) &&
                (this.Image72 == null && other.Image72 == null ||
                 this.Image72?.Equals(other.Image72) == true) &&
                (this.ImageOriginal == null && other.ImageOriginal == null ||
                 this.ImageOriginal?.Equals(other.ImageOriginal) == true) &&
                (this.additionalProperties == null && other.additionalProperties == null ||
                 this.additionalProperties?.Count == other.additionalProperties?.Count &&
                 this.additionalProperties?.All(kv =>
                     other.additionalProperties.TryGetValue(kv.Key, out var value) &&
                     JToken.DeepEquals(kv.Value, value)) == true);
        }

        /// <summary>
        /// ToString overload.
        /// </summary>
        /// <param name="toStringOutput">List of strings.</param>
        protected void ToString(List<string> toStringOutput)
        {
            toStringOutput.Add($"AvatarHash = {this.AvatarHash ?? "null"}");
            toStringOutput.Add($"Image1024 = {this.Image1024 ?? "null"}");
            toStringOutput.Add($"Image192 = {this.Image192 ?? "null"}");
            toStringOutput.Add($"Image24 = {this.Image24 ?? "null"}");
            toStringOutput.Add($"Image32 = {this.Image32 ?? "null"}");
            toStringOutput.Add($"Image48 = {this.Image48 ?? "null"}");
            toStringOutput.Add($"Image512 = {this.Image512 ?? "null"}");
            toStringOutput.Add($"Image72 = {this.Image72 ?? "null"}");
            toStringOutput.Add($"ImageOriginal = {this.ImageOriginal ?? "null"}");

            additionalProperties?
                .Select(kvp => $"[{kvp.Key}] = {kvp.Value.ToString(Formatting.None)}")
                .ToList()
                .ForEach(toStringOutput.Add);
        }
    }
}