// <copyright file="IAuthorizationCodeAuth.cs" company="APIMatic">
// SlackWebApi.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using System.Threading.Tasks;
using System.Collections.Generic;

namespace SlackWebApi.Standard.Authentication
{
    public interface IAuthorizationCodeAuth
    {
        /// <summary>
        /// Gets string value for oauthClientId.
        /// </summary>
        string OauthClientId { get; }

        /// <summary>
        /// Gets string value for oauthClientSecret.
        /// </summary>
        string OauthClientSecret { get; }

        /// <summary>
        /// Gets string value for oauthRedirectUri.
        /// </summary>
        string OauthRedirectUri { get; }

        /// <summary>
        /// Gets Models.OauthToken value for oauthToken.
        /// </summary>
        Models.OauthToken OauthToken { get; }

        /// <summary>
        /// Gets List of Models.OauthScope value for oauthScopes.
        /// </summary>
        List<Models.OauthScope> OauthScopes { get; }

        /// <summary>
        ///  Returns true if credentials matched.
        /// </summary>
        /// <param name="oauthClientId"> The string value for credentials.</param>
        /// <param name="oauthClientSecret"> The string value for credentials.</param>
        /// <param name="oauthRedirectUri"> The string value for credentials.</param>
        /// <param name="oauthToken"> The Models.OauthToken value for credentials.</param>
        /// <param name="oauthScopes"> The List of Models.OauthScope value for credentials.</param>
        /// <returns>True if credentials matched.</returns>
        bool Equals(string oauthClientId, string oauthClientSecret, string oauthRedirectUri, Models.OauthToken oauthToken, List<Models.OauthScope> oauthScopes);

        /// <summary>
        /// Fetch the OAuth token asynchronously.
        /// </summary>
        /// <param name="authorizationCode">Authorization code returned by the OAuth provider.</param>
        /// <param name="additionalParameters">Dictionary of additional parameters.</param>
        /// <returns>OAuthToken.</returns>
        Task<Models.OauthToken> FetchTokenAsync(string authorizationCode, Dictionary<string, object> additionalParameters = null);

        /// <summary>
        /// Fetch the OAuth token.
        /// </summary>
        /// <param name="authorizationCode">Authorization code returned by the OAuth provider.</param>
        /// <param name="additionalParameters">Dictionary of additional parameters.</param>
        /// <returns>OAuthToken.</returns>
        Models.OauthToken FetchToken(string authorizationCode, Dictionary<string, object> additionalParameters = null);

        /// <summary>
        /// Checks if token is expired.
        /// </summary>
        /// <returns> Returns true if token is expired.</returns>
        bool IsTokenExpired();

        /// <summary>
        /// Refresh the OAuth token.
        /// </summary>
        /// <param name="additionalParameters">Dictionary of additional parameters.</param>
        /// <returns>OAuthToken.</returns>
        Models.OauthToken RefreshToken(Dictionary<string, object> additionalParameters = null);

        /// <summary>
        /// Refresh the OAuth token asynchronously.
        /// </summary>
        /// <param name="additionalParameters">Dictionary of additional parameters.</param>
        /// <returns>OAuthToken.</returns>
        Task<Models.OauthToken> RefreshTokenAsync(Dictionary<string, object> additionalParameters = null);

        /// <summary>
        /// Build an authorization URL for taking the user's consent to access data.
        /// </summary>
        /// <param name="state">An opaque state string.</param>
        /// <param name="additionalParameters">Additional parameters to add the the authorization URL.</param>
        /// <returns>Authorization URL.</returns>
        Task<string> BuildAuthorizationUrl(string state = null, Dictionary<string, object> additionalParameters = null);
    }
}